In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
data=pd.read_excel('赛题1数据材料\赛题1数据集\上市信息财务信息运营能力指标.xlsx')
data

       企业编号      标题          日期  总资产周转率(次) 应收账款周转天数(天) 存货周转天数(天)
0      1001  运营能力指标  2018-09-30       0.02          --        --
1      1001  运营能力指标  2018-06-30       0.01          --        --
2      1001  运营能力指标  2018-03-31       0.01          --        --
3      1001  运营能力指标  2017-12-31       0.03          --        --
4      1001  运营能力指标  2017-09-30       0.02          --        --
5      1001  运营能力指标  2017-06-30       0.01          --        --
6      1001  运营能力指标  2017-03-31       0.01          --        --
7      1001  运营能力指标  2016-12-31       0.03          --        --
8      1001  运营能力指标  2016-09-30       0.02          --        --
9      1002  运营能力指标  2018-09-30       0.23       41.90      5.01
10     1002  运营能力指标  2018-06-30       0.15       52.87      5.72
11     1002  运营能力指标  2018-03-31       0.07       56.59      7.04
12     1002  运营能力指标  2017-12-31       0.34       42.44      6.76
13     1002  运营能力指标  2017-09-30       0.26       47.49      6.44
14     1002  运营能力指标  2017-06-30       0.17       43.14      6.60
15     1002  运营能力指标  2017-03-31       0.09       54.58      7.04
16     1002  运营能力指标  2016-12-31       0.41       39.83      7.01
17     1002  运营能力指标  2016-09-30       0.31       43.29      6.94
18     1003  运营能力指标  2018-09-30       0.53      123.41     53.82
19     1003  运营能力指标  2018-06-30       0.33      119.72     61.74
20     1003  运营能力指标  2018-03-31       0.14      139.91     75.54
21     1003  运营能力指标  2017-12-31       0.93       64.15     38.01
22     1003  运营能力指标  2017-09-30       0.59       64.51     55.69
23     1003  运营能力指标  2017-06-30       0.38       60.82     61.44
24     1003  运营能力指标  2017-03-31       0.18       62.20     56.30
25     1003  运营能力指标  2016-12-31       0.77       56.02     43.04
26     1003  运营能力指标  2016-09-30       0.53       67.74     48.69
27     1004  运营能力指标  2018-09-30       0.20       17.29      6.50
28     1004  运营能力指标  2018-06-30       0.14       35.36      6.43
29     1004  运营能力指标  2018-03-31       0.07       35.06      6.24
...     ...     ...         ...        ...         ...       ...
28857  3997  运营能力指标  2017-03-31       0.14      255.70    178.62
28858  3997  运营能力指标  2016-12-31       0.49      244.28     82.86
28859  3997  运营能力指标  2016-09-30       0.37      238.59     28.87
28860  3998  运营能力指标  2018-09-30       0.20      413.83     53.65
28861  3998  运营能力指标  2018-06-30       0.12      443.70     56.40
28862  3998  运营能力指标  2018-03-31       0.05      548.89     78.86
28863  3998  运营能力指标  2017-12-31       0.39      269.27     26.83
28864  3998  运营能力指标  2017-09-30       0.22      352.30     43.73
28865  3998  运营能力指标  2017-06-30       0.12      400.90     45.82
28866  3998  运营能力指标  2017-03-31       0.05      466.78     53.34
28867  3998  运营能力指标  2016-12-31       0.42      201.69     29.04
28868  3998  运营能力指标  2016-09-30       0.27      234.54     44.15
28869  3999  运营能力指标  2018-09-30       0.14      372.61    437.35
28870  3999  运营能力指标  2018-06-30       0.10      363.35    478.84
28871  3999  运营能力指标  2018-03-31       0.04      409.70    546.36
28872  3999  运营能力指标  2017-12-31       0.18      393.54    469.26
28873  3999  运营能力指标  2017-09-30       0.16      369.15    458.36
28874  3999  运营能力指标  2017-06-30       0.09      408.63    440.55
28875  3999  运营能力指标  2017-03-31       0.06      336.85    340.74
28876  3999  运营能力指标  2016-12-31       0.24      317.77    312.11
28877  3999  运营能力指标  2016-09-30       0.15      402.05    345.15
28878  4000  运营能力指标  2018-09-30       0.18      342.19     67.21
28879  4000  运营能力指标  2018-06-30       0.13      330.30     68.48
28880  4000  运营能力指标  2018-03-31       0.07      302.32     62.61
28881  4000  运营能力指标  2017-12-31       0.29      273.50     64.18
28882  4000  运营能力指标  2017-09-30       0.20      305.74     66.95
28883  4000  运营能力指标  2017-06-30       0.14      296.83     65.16
28884  4000  运营能力指标  2017-03-31       0.07      296.09     64.42
28885  4000  运营能力指标  2016-12-31       0.37      226.11     55.46
28886  4000  运营能力指标  2016-09-30       0.29      238.95     58.91

[28887 rows x 6 columns]

In [3]:
#查看在表的公司总数
len(data['企业编号'].unique())

2986

In [4]:
#将缺失值变为nan
data=data.replace('--',np.nan)

In [5]:
#查看出现较多的时间
data['日期'].value_counts()

2016-12-31    3208
2017-09-30    3204
2017-06-30    3195
2017-03-31    3178
2017-12-31    3133
2018-03-31    3104
2016-09-30    3092
2018-06-30    3065
2018-09-30    3031
2016-06-30     193
2016-03-31     142
2015-12-31     140
2015-09-30      71
2018-12-31      46
2014-12-31      31
2015-06-30       6
2013-12-31       5
16-06-30         4
15-09-30         4
15-06-30         4
15-12-31         4
16-03-31         4
15-03-31         4
14-12-31         3
2011-12-31       2
2015-03-31       2
16-09-30         2
2012-12-31       2
14-09-30         2
16-12-31         2
14-06-30         2
2010-12-31       1
17-03-31         1
Name: 日期, dtype: int64

In [6]:
#补全时间，规整时间的格式
pattern='\d\d\d\d-\d\d-\d\d'
for i in range(len(data)):
    if re.findall(pattern,data.iloc[i,2])==[]:
        data.iloc[i,2]='20'+data.iloc[i,2]

In [7]:
#去除企业编号与日期值相同的行，保留第一次出现的行
data.drop_duplicates(subset=['企业编号','日期'],keep='first',inplace=True)

In [8]:
#再次查看出现较多的时间
data['日期'].value_counts()

2016-12-31    2985
2017-09-30    2982
2017-12-31    2980
2018-06-30    2974
2018-09-30    2973
2017-06-30    2972
2018-03-31    2957
2017-03-31    2956
2016-09-30    2873
2016-06-30     156
2015-12-31     128
2016-03-31     112
2015-09-30      60
2018-12-31      45
2014-12-31      33
2015-06-30      10
2015-03-31       6
2013-12-31       5
2011-12-31       2
2014-06-30       2
2014-09-30       2
2012-12-31       2
2010-12-31       1
Name: 日期, dtype: int64

In [9]:
#将数量较少的日期全部丢弃
timelist=list(['2016-12-31','2017-09-30','2017-12-31','2018-06-30','2018-09-30','2017-06-30','2018-03-31','2017-03-31','2016-09-30'])
data=data[data['日期'].isin(timelist)]
data

       企业编号      标题          日期  总资产周转率(次) 应收账款周转天数(天) 存货周转天数(天)
0      1001  运营能力指标  2018-09-30       0.02         NaN       NaN
1      1001  运营能力指标  2018-06-30       0.01         NaN       NaN
2      1001  运营能力指标  2018-03-31       0.01         NaN       NaN
3      1001  运营能力指标  2017-12-31       0.03         NaN       NaN
4      1001  运营能力指标  2017-09-30       0.02         NaN       NaN
5      1001  运营能力指标  2017-06-30       0.01         NaN       NaN
6      1001  运营能力指标  2017-03-31       0.01         NaN       NaN
7      1001  运营能力指标  2016-12-31       0.03         NaN       NaN
8      1001  运营能力指标  2016-09-30       0.02         NaN       NaN
9      1002  运营能力指标  2018-09-30       0.23       41.90      5.01
10     1002  运营能力指标  2018-06-30       0.15       52.87      5.72
11     1002  运营能力指标  2018-03-31       0.07       56.59      7.04
12     1002  运营能力指标  2017-12-31       0.34       42.44      6.76
13     1002  运营能力指标  2017-09-30       0.26       47.49      6.44
14     1002  运营能力指标  2017-06-30       0.17       43.14      6.60
15     1002  运营能力指标  2017-03-31       0.09       54.58      7.04
16     1002  运营能力指标  2016-12-31       0.41       39.83      7.01
17     1002  运营能力指标  2016-09-30       0.31       43.29      6.94
18     1003  运营能力指标  2018-09-30       0.53      123.41     53.82
19     1003  运营能力指标  2018-06-30       0.33      119.72     61.74
20     1003  运营能力指标  2018-03-31       0.14      139.91     75.54
21     1003  运营能力指标  2017-12-31       0.93       64.15     38.01
22     1003  运营能力指标  2017-09-30       0.59       64.51     55.69
23     1003  运营能力指标  2017-06-30       0.38       60.82     61.44
24     1003  运营能力指标  2017-03-31       0.18       62.20     56.30
25     1003  运营能力指标  2016-12-31       0.77       56.02     43.04
26     1003  运营能力指标  2016-09-30       0.53       67.74     48.69
27     1004  运营能力指标  2018-09-30       0.20       17.29      6.50
28     1004  运营能力指标  2018-06-30       0.14       35.36      6.43
29     1004  运营能力指标  2018-03-31       0.07       35.06      6.24
...     ...     ...         ...        ...         ...       ...
28857  3997  运营能力指标  2017-03-31       0.14      255.70    178.62
28858  3997  运营能力指标  2016-12-31       0.49      244.28     82.86
28859  3997  运营能力指标  2016-09-30       0.37      238.59     28.87
28860  3998  运营能力指标  2018-09-30       0.20      413.83     53.65
28861  3998  运营能力指标  2018-06-30       0.12      443.70     56.40
28862  3998  运营能力指标  2018-03-31       0.05      548.89     78.86
28863  3998  运营能力指标  2017-12-31       0.39      269.27     26.83
28864  3998  运营能力指标  2017-09-30       0.22      352.30     43.73
28865  3998  运营能力指标  2017-06-30       0.12      400.90     45.82
28866  3998  运营能力指标  2017-03-31       0.05      466.78     53.34
28867  3998  运营能力指标  2016-12-31       0.42      201.69     29.04
28868  3998  运营能力指标  2016-09-30       0.27      234.54     44.15
28869  3999  运营能力指标  2018-09-30       0.14      372.61    437.35
28870  3999  运营能力指标  2018-06-30       0.10      363.35    478.84
28871  3999  运营能力指标  2018-03-31       0.04      409.70    546.36
28872  3999  运营能力指标  2017-12-31       0.18      393.54    469.26
28873  3999  运营能力指标  2017-09-30       0.16      369.15    458.36
28874  3999  运营能力指标  2017-06-30       0.09      408.63    440.55
28875  3999  运营能力指标  2017-03-31       0.06      336.85    340.74
28876  3999  运营能力指标  2016-12-31       0.24      317.77    312.11
28877  3999  运营能力指标  2016-09-30       0.15      402.05    345.15
28878  4000  运营能力指标  2018-09-30       0.18      342.19     67.21
28879  4000  运营能力指标  2018-06-30       0.13      330.30     68.48
28880  4000  运营能力指标  2018-03-31       0.07      302.32     62.61
28881  4000  运营能力指标  2017-12-31       0.29      273.50     64.18
28882  4000  运营能力指标  2017-09-30       0.20      305.74     66.95
28883  4000  运营能力指标  2017-06-30       0.14      296.83     65.16
28884  4000  运营能力指标  2017-03-31       0.07      296.09     64.42
28885  4000  运营能力指标  2016-12-31       0.37      226.11     55.46
28886  4000  运营能力指标  2016-09-30       0.29      238.95     58.91

[26652 rows x 6 columns]

In [10]:
data.sort_values(by=['企业编号','日期'],inplace=True)

In [11]:
#查看排序结果是否达到目标效果
data

       企业编号      标题          日期  总资产周转率(次) 应收账款周转天数(天) 存货周转天数(天)
8      1001  运营能力指标  2016-09-30       0.02         NaN       NaN
7      1001  运营能力指标  2016-12-31       0.03         NaN       NaN
6      1001  运营能力指标  2017-03-31       0.01         NaN       NaN
5      1001  运营能力指标  2017-06-30       0.01         NaN       NaN
4      1001  运营能力指标  2017-09-30       0.02         NaN       NaN
3      1001  运营能力指标  2017-12-31       0.03         NaN       NaN
2      1001  运营能力指标  2018-03-31       0.01         NaN       NaN
1      1001  运营能力指标  2018-06-30       0.01         NaN       NaN
0      1001  运营能力指标  2018-09-30       0.02         NaN       NaN
17     1002  运营能力指标  2016-09-30       0.31       43.29      6.94
16     1002  运营能力指标  2016-12-31       0.41       39.83      7.01
15     1002  运营能力指标  2017-03-31       0.09       54.58      7.04
14     1002  运营能力指标  2017-06-30       0.17       43.14      6.60
13     1002  运营能力指标  2017-09-30       0.26       47.49      6.44
12     1002  运营能力指标  2017-12-31       0.34       42.44      6.76
11     1002  运营能力指标  2018-03-31       0.07       56.59      7.04
10     1002  运营能力指标  2018-06-30       0.15       52.87      5.72
9      1002  运营能力指标  2018-09-30       0.23       41.90      5.01
26     1003  运营能力指标  2016-09-30       0.53       67.74     48.69
25     1003  运营能力指标  2016-12-31       0.77       56.02     43.04
24     1003  运营能力指标  2017-03-31       0.18       62.20     56.30
23     1003  运营能力指标  2017-06-30       0.38       60.82     61.44
22     1003  运营能力指标  2017-09-30       0.59       64.51     55.69
21     1003  运营能力指标  2017-12-31       0.93       64.15     38.01
20     1003  运营能力指标  2018-03-31       0.14      139.91     75.54
19     1003  运营能力指标  2018-06-30       0.33      119.72     61.74
18     1003  运营能力指标  2018-09-30       0.53      123.41     53.82
35     1004  运营能力指标  2016-09-30       0.16       23.15      7.67
34     1004  运营能力指标  2016-12-31       0.22       21.90      7.90
33     1004  运营能力指标  2017-03-31       0.05       23.25      7.41
...     ...     ...         ...        ...         ...       ...
28853  3997  运营能力指标  2018-03-31       0.10      153.91    695.02
28852  3997  运营能力指标  2018-06-30       0.19      153.49    664.90
28851  3997  运营能力指标  2018-09-30       0.24      175.64    863.69
28868  3998  运营能力指标  2016-09-30       0.27      234.54     44.15
28867  3998  运营能力指标  2016-12-31       0.42      201.69     29.04
28866  3998  运营能力指标  2017-03-31       0.05      466.78     53.34
28865  3998  运营能力指标  2017-06-30       0.12      400.90     45.82
28864  3998  运营能力指标  2017-09-30       0.22      352.30     43.73
28863  3998  运营能力指标  2017-12-31       0.39      269.27     26.83
28862  3998  运营能力指标  2018-03-31       0.05      548.89     78.86
28861  3998  运营能力指标  2018-06-30       0.12      443.70     56.40
28860  3998  运营能力指标  2018-09-30       0.20      413.83     53.65
28877  3999  运营能力指标  2016-09-30       0.15      402.05    345.15
28876  3999  运营能力指标  2016-12-31       0.24      317.77    312.11
28875  3999  运营能力指标  2017-03-31       0.06      336.85    340.74
28874  3999  运营能力指标  2017-06-30       0.09      408.63    440.55
28873  3999  运营能力指标  2017-09-30       0.16      369.15    458.36
28872  3999  运营能力指标  2017-12-31       0.18      393.54    469.26
28871  3999  运营能力指标  2018-03-31       0.04      409.70    546.36
28870  3999  运营能力指标  2018-06-30       0.10      363.35    478.84
28869  3999  运营能力指标  2018-09-30       0.14      372.61    437.35
28886  4000  运营能力指标  2016-09-30       0.29      238.95     58.91
28885  4000  运营能力指标  2016-12-31       0.37      226.11     55.46
28884  4000  运营能力指标  2017-03-31       0.07      296.09     64.42
28883  4000  运营能力指标  2017-06-30       0.14      296.83     65.16
28882  4000  运营能力指标  2017-09-30       0.20      305.74     66.95
28881  4000  运营能力指标  2017-12-31       0.29      273.50     64.18
28880  4000  运营能力指标  2018-03-31       0.07      302.32     62.61
28879  4000  运营能力指标  2018-06-30       0.13      330.30     68.48
28878  4000  运营能力指标  2018-09-30       0.18      342.19     67.21

[26652 rows x 6 columns]

In [12]:
data=data.set_index(['企业编号','日期'])
data=data.unstack().reset_index().set_index('企业编号').T.drop('标题')

In [13]:
data

企业编号                    1001   1002    1003   1004    1005   1006    1007  \
            日期
总资产周转率(次)   2016-09-30  0.02   0.31    0.53   0.16    0.12    NaN    0.14
            2016-12-31  0.03   0.41    0.77   0.22    0.21   0.26    0.22
            2017-03-31  0.01   0.09    0.18   0.05    0.04   0.07    0.07
            2017-06-30  0.01   0.17    0.38   0.11     0.1   0.14    0.15
            2017-09-30  0.02   0.26    0.59   0.17    0.15   0.22    0.24
            2017-12-31  0.03   0.34    0.93   0.24     0.2    0.3    0.37
            2018-03-31  0.01   0.07    0.14   0.07    0.04   0.08    0.09
            2018-06-30  0.01   0.15    0.33   0.14    0.08   0.16    0.22
            2018-09-30  0.02   0.23    0.53    0.2    0.13   0.24    0.33
应收账款周转天数(天) 2016-09-30   NaN  43.29   67.74  23.15   92.68    NaN   22.34
            2016-12-31   NaN  39.83   56.02  21.90   77.85  49.69   17.04
            2017-03-31   NaN  54.58   62.20  23.25  110.26  56.05   14.08
            2017-06-30   NaN  43.14   60.82  26.74   95.87  52.18   14.15
            2017-09-30   NaN  47.49   64.51  28.87   90.66  56.43   17.38
            2017-12-31   NaN  42.44   64.15  28.86   84.15  49.52   15.56
            2018-03-31   NaN  56.59  139.91  35.06  102.99  54.21   22.24
            2018-06-30   NaN  52.87  119.72  35.36   98.99  49.91   18.12
            2018-09-30   NaN  41.90  123.41  17.29   93.00  51.52   20.64
存货周转天数(天)   2016-09-30   NaN   6.94   48.69   7.67  357.19    NaN  208.29
            2016-12-31   NaN   7.01   43.04   7.90  173.02   1.89  185.20
            2017-03-31   NaN   7.04   56.30   7.41   95.58   1.73  148.77
            2017-06-30   NaN   6.60   61.44   7.30   79.43   1.68  152.21
            2017-09-30   NaN   6.44   55.69   6.71   84.06   1.63  147.17
            2017-12-31   NaN   6.76   38.01   6.43   52.12   1.74  135.98
            2018-03-31   NaN   7.04   75.54   6.24   44.65   1.62  174.27
            2018-06-30   NaN   5.72   61.74   6.43   44.16   1.77  130.61
            2018-09-30   NaN   5.01   53.82   6.50   47.05   1.87  132.37

企业编号                     1008  1009  1010   ...      3991    3992    3993  \
            日期                              ...
总资产周转率(次)   2016-09-30   0.28  0.15  0.02   ...      0.22     0.3    0.47
            2016-12-31   0.37   0.2  0.03   ...      0.42    0.49    0.63
            2017-03-31   0.11  0.05  0.01   ...      0.04    0.07    0.14
            2017-06-30   0.21   0.1  0.01   ...      0.09    0.18     0.3
            2017-09-30   0.32  0.16  0.02   ...      0.15     0.3    0.45
            2017-12-31   0.44  0.21  0.03   ...      0.26    0.47    0.56
            2018-03-31   0.11  0.05  0.01   ...      0.08    0.08     0.1
            2018-06-30   0.22   0.1  0.01   ...      0.13     0.2    0.17
            2018-09-30   0.33  0.16  0.02   ...      0.19    0.34    0.23
应收账款周转天数(天) 2016-09-30  43.14   NaN   NaN   ...    408.78  260.40   66.94
            2016-12-31  44.85   NaN   NaN   ...    272.90  199.37   66.25
            2017-03-31  37.56   NaN   NaN   ...    813.26  380.45   65.51
            2017-06-30  39.23   NaN   NaN   ...    695.24  283.45   68.03
            2017-09-30  38.06   NaN   NaN   ...    612.02  261.36   63.81
            2017-12-31  42.26   NaN   NaN   ...    400.34  207.09   61.92
            2018-03-31  44.95   NaN   NaN   ...    296.47  304.23   66.44
            2018-06-30  46.69   NaN   NaN   ...    392.97  236.76   69.43
            2018-09-30  23.40   NaN   NaN   ...    410.59  218.64   68.22
存货周转天数(天)   2016-09-30  24.70  1.90   NaN   ...    312.15  242.03  125.48
            2016-12-31  24.77  1.79   NaN   ...    178.77  160.83  146.42
            2017-03-31  18.91  1.63   NaN   ...    309.09  336.02  193.31
            2017-06-30  21.75  1.60   NaN   ...    292.40  242.20  170.30
            2017-09-30  20.03  1.69   NaN   ...    273.13  239.34  159.88
            2017-12-31  18.99  1.93   NaN   ...    181.59  181.66  163.83
            2018-03-31  18.88  2.02   NaN   ...    110.10  304.30  151.08
            2018-06-30  20.54  2.05   NaN   ...    175.53  254.02  177.08
            2018-09-30  20.08  1.87   NaN   ...    205.52  246.14  175.64

企业编号                      3994    3995   3996    3997    3998    3999    4000
            日期
总资产周转率(次)   2016-09-30    0.67    0.35   0.83    0.37    0.27    0.15    0.29
            2016-12-31    0.97    0.48   1.15    0.49    0.42    0.24    0.37
            2017-03-31    0.31    0.14   0.27    0.14    0.05    0.06    0.07
            2017-06-30    0.58    0.28   0.61    0.27    0.12    0.09    0.14
            2017-09-30    0.81    0.43   0.95    0.36    0.22    0.16     0.2
            2017-12-31    1.11    0.58   1.31    0.46    0.39    0.18    0.29
            2018-03-31    0.24    0.16   0.25     0.1    0.05    0.04    0.07
            2018-06-30    0.59    0.34   0.51    0.19    0.12     0.1    0.13
            2018-09-30     0.8    0.51   0.84    0.24     0.2    0.14    0.18
应收账款周转天数(天) 2016-09-30  141.48   31.19  84.38  238.59  234.54  402.05  238.95
            2016-12-31  105.80   31.32  83.60  244.28  201.69  317.77  226.11
            2017-03-31  104.17   31.40  77.50  255.70  466.78  336.85  296.09
            2017-06-30  109.28   33.52  84.30  231.20  400.90  408.63  296.83
            2017-09-30  112.08   34.42  67.96  260.82  352.30  369.15  305.74
            2017-12-31   89.95   30.54  80.22  205.93  269.27  393.54  273.50
            2018-03-31  125.08   25.26  83.10  153.91  548.89  409.70  302.32
            2018-06-30  117.22   27.09  96.97  153.49  443.70  363.35  330.30
            2018-09-30  112.18   29.00  86.95  175.64  413.83  372.61  342.19
存货周转天数(天)   2016-09-30  139.34  148.92  63.35   28.87   44.15  345.15   58.91
            2016-12-31  124.85  145.72  60.44   82.86   29.04  312.11   55.46
            2017-03-31   93.07  148.94  71.19  178.62   53.34  340.74   64.42
            2017-06-30   90.58  147.00  56.28  253.37   45.82  440.55   65.16
            2017-09-30   99.68  145.81  62.89  307.26   43.73  458.36   66.95
            2017-12-31   91.83  139.07  56.11  387.58   26.83  469.26   64.18
            2018-03-31   83.77  125.11  66.44  695.02   78.86  546.36   62.61
            2018-06-30   64.26  132.03  69.82  664.90   56.40  478.84   68.48
            2018-09-30   74.06  133.00  74.17  863.69   53.65  437.35   67.21

[27 rows x 2985 columns]