In [32]:
import pandas as pd
import numpy as np
import re

In [33]:
data=pd.read_excel('赛题1测试数据集/上市信息财务信息资产负债表.xlsx')

In [34]:
data

,企业编号s,标题,日期,资产:货币资金(元),资产:应收账款(元),资产:其它应收款(元),资产:存货(元),资产:流动资产合计(元),资产:长期股权投资(元),资产:累计折旧(元),...,负债:预收账款(元),负债:存货跌价准备(元),负债:流动负债合计(元),负债:长期负债合计(元),负债:负债合计(元),权益:实收资本(或股本)(元),权益:资本公积金(元),权益:盈余公积金(元),权益:股东权益合计(元),流动比率
0,4001,资产负债表,2018-09-30,-20.0018967774905,28.8375765408752,36.5039659507049,-0.971724107848274,3.4416265725397,274.666408322165,NaN,...,-26.1018803895912,NaN,19.9500989584298,-1.42853887678532,11.6712848103277,21.8558833179902,-0.170197623203871,13.1975225098742,9.15334629070048,NaN
1,4001,资产负债表,2018-06-30,-51.8631401663309,17.2362826984732,-27.1388501777185,2.05544943760258,-3.95942146160391,909.019254051886,NaN,...,-40.7134556707884,NaN,10.8761954713467,14.6637336705321,12.1266356876905,21.8558833179902,-0.170197623203871,13.1975225098742,16.3635208581447,NaN
2,4001,资产负债表,2018-03-31,-28.1911867099508,24.9793645148393,33.1458861357762,6.66500735296153,8.90036174213149,1028.09338942222,NaN,...,1.93568836902487,NaN,14.6386987432037,74.8357009643142,32.0280326640151,1.54656952180068,4.67099829416082,13.1975225098742,17.868936454965,NaN
3,4001,资产负债表,2017-12-31,57.6106491133635,46.2034331920527,12.5264612293939,13.805135544459,25.6045042338564,859.914563393134,NaN,...,-15.4798406401432,NaN,34.0136782271546,168.478891597327,60.8850208023843,0,0.044612176278595,13.1975225098742,15.2207992417913,NaN
4,4001,资产负债表,2017-09-30,228.908313246004,92.3178851782632,26.8767843253717,43.1117523971108,61.2938548693283,613.61552454555,NaN,...,188.14790362917,NaN,73.448185013665,307.758004735338,123.091256925406,0,0.0000162515811426267,8.79586765468184,14.53773466991,NaN
5,4001,资产负债表,2017-06-30,525.904111515149,98.5523752137099,101.587861235582,38.3123156779038,75.8170141805266,109.823900776914,NaN,...,165.737266101686,NaN,98.2947596130979,283.383824913928,135.893043359352,0,0.0000162515811426267,8.79586765468184,8.27765346560193,NaN
6,4002,资产负债表,2018-09-30,-2.4862762134382,5.04056652232327,48.8169500086462,93.60140108092,23.6377597150454,-6.12594343129359,NaN,...,153.255078972354,NaN,45.7795775133591,336.215054851594,63.8494363534094,0,-6.79992145491188,14.9326239609204,0.822769209056567,NaN
7,4002,资产负债表,2018-06-30,16.348821070719,32.8406657290712,35.116547934118,38.7240619526961,38.371684908717,-99.2613694291671,NaN,...,86.8097007570686,NaN,73.8218281623707,305.333525580277,91.9734390324281,3.52577020792311,26.6132381355038,14.9326239609204,16.6523971514367,NaN
8,4002,资产负债表,2018-03-31,17.0190854033921,31.5829904578714,20.8391642873932,22.2967220571351,29.3356817116881,-99.0759445689659,NaN,...,110.964527667953,NaN,34.4712471728347,256.057908062804,53.1915652764375,107.051540415846,-8.89464241781505,14.9326239609204,21.2300061305085,NaN
9,4002,资产负债表,2017-12-31,6.42817067932192,61.800902126843,20.7729572998542,16.9089276342772,26.0784064632665,-98.9215123628553,NaN,...,42.8248709339951,NaN,46.1141793554206,-13.5375127346181,40.9099605083278,107.051540415846,-8.89464241781505,14.9326239609204,20.6443509576707,NaN
10,4002,资产负债表,2017-09-30,450.023508039971,18.3249513069246,0.949488463723915,15.2228770979042,66.4447829098473,-99.0766701376809,NaN,...,117.231253689159,NaN,-12.5756090761851,-27.6477587163548,-13.6941923573661,127.927365371759,216.181076030951,16.798794546231,103.595569810666,NaN
11,4002,资产负债表,2017-06-30,112.697730858052,22.704945763411,14.200821176593,0.170851954855221,39.449219840917,4899.82454976211,NaN,...,29.821344243445,NaN,-20.9084042256342,-25.4411677335258,-21.283611592479,120.164858386454,134.95033995889,16.798794546231,81.0649515606113,NaN
12,4003,资产负债表,2018-09-30,-4.20234322408519,-7.10769294657838,62.2098919926415,25.9825069166784,-1.27522917552,NaN,NaN,...,-60.6223785113463,NaN,-15.0797516259298,0.682148451559306,-14.8173320930958,0,0,13.1969044538423,2.52989343014383,NaN
13,4003,资产负债表,2018-06-30,-2.09248854660494,-24.896002864003,2837.61834725575,17.123588112174,16.3341419293089,NaN,NaN,...,-30.8724397255863,NaN,8.10445536657994,-5.12997188351023,7.8386500947945,5.13891703703704,30.0009483066834,13.1969044538423,15.1623913690589,NaN
14,4003,资产负债表,2018-03-31,-32.7031980846981,-24.2444595345473,1285.09162178608,-47.7864864634908,20.9929880823726,NaN,NaN,...,-60.3077785640722,NaN,-4.90952914508275,29.1038828945848,-4.12639266220995,5.13891703703704,30.0009483066834,13.1969044538423,18.6804092728618,NaN
15,4003,资产负债表,2017-12-31,34.1219395508518,22.7782913846214,1300.16866044221,19.3715926968286,24.2265290438283,NaN,NaN,...,9.5848957740453,NaN,21.2719829649505,29.2668745424533,21.5121968524215,5.13891703703704,30.0009483066834,13.1969044538423,16.937567734517,NaN
16,4003,资产负债表,2017-09-30,-46.4864426059535,23.3800472719129,-8.53278394101907,12.4566304640951,21.6464546534834,NaN,NaN,...,13.9171311828198,NaN,9.55604001157909,-35.6427991179108,8.28983100646664,5.13891703703704,30.0009483066834,15.6424601649827,16.7829167539817,NaN
17,4003,资产负债表,2017-06-30,8.95287183639432,17.4526698648894,9.67820441939548,15.3618253289421,2.48689911796687,NaN,NaN,...,157.044432217919,NaN,25.4332103360409,-32.7266275857931,23.292416759405,0,0,15.6424601649827,3.89930797666047,NaN
18,4003,资产负债表,2017-09-30,7.51亿,5.13亿,2298万,4.35亿,18.5亿,3264万,--,...,4978万,--,10.1亿,6.79亿,16.9亿,7.13亿,11.2亿,3800万,26.3亿,1.84
19,4003,资产负债表,2017-06-30,5.60亿,7.81亿,1554万,4.32亿,19.8亿,2927万,6984万,...,4373万,--,14.4亿,4.43亿,18.8亿,7.14亿,11.2亿,3800万,25.9亿,1.37
20,4003,资产负债表,2017-03-31,6.57亿,6.62亿,1731万,3.99亿,18.4亿,3524万,--,...,2917万,--,11.8亿,3.90亿,15.7亿,6.71亿,6.23亿,3800万,19.8亿,1.55
21,4003,资产负债表,2016-12-31,7.39亿,5.17亿,988万,2.95亿,16.5亿,2841万,9941万,...,2214万,--,9.95亿,4.34亿,14.3亿,6.71亿,6.23亿,3800万,19.0亿,1.66
22,4003,资产负债表,2016-09-30,9.43亿,4.63亿,1536万,2.77亿,17.8亿,3802万,--,...,1428万,--,9.79亿,4.21亿,14.0亿,6.71亿,6.48亿,3609万,19.1亿,1.82
23,4003,资产负债表,2016-06-30,9.37亿,4.47亿,1285万,2.43亿,16.7亿,3858万,4449万,...,2136万,--,8.35亿,3.79亿,12.1亿,6.71亿,6.35亿,3609万,18.4亿,2.01
24,4003,资产负债表,2016-03-31,2.57亿,4.03亿,1095万,2.41亿,9.54亿,1644万,--,...,2059万,--,7.50亿,3.02亿,10.5亿,6.15亿,--,3609万,10.6亿,1.27
25,4003,资产负债表,2015-12-31,4.05亿,3.24亿,1131万,1.72亿,9.59亿,494万,7506万,...,2183万,--,7.28亿,2.55亿,9.83亿,6.15亿,2852万,3609万,10.8亿,1.32
26,4004,资产负债表,2018-09-30,27.261557279805,31.6573915474896,-78.3600904481522,-1.01029652840609,0.064550225278914,NaN,NaN,...,-30.1986851778224,NaN,-36.3341706547124,108.351133892639,-7.04836695726162,0,0,18.5380218474681,2.71719030357153,NaN
27,4004,资产负债表,2018-06-30,7.69153859921538,37.7119870770976,-68.2540086488966,-4.9968008291877,6.74295260755112,NaN,NaN,...,-15.2614299570417,NaN,-26.6706107134964,88.2321048580894,-3.04691212740927,0,0,18.5380218474681,2.69633425797522,NaN
28,4004,资产负债表,2018-03-31,22.2921247479952,74.1838684423957,0.216450304343801,14.1135878538585,21.1543234619921,NaN,NaN,...,-18.4074914695317,NaN,-8.07434935151496,23.6120243212728,1.12893487964822,0,0,18.5380218474681,4.59168905454901,NaN
29,4004,资产负债表,2017-12-31,11.5534611162565,25.8430799335558,-21.1336914022191,8.14444870355084,13.0545780068494,NaN,NaN,...,26.4146833414166,NaN,21.6698757466324,-39.2843829422996,-1.77288327258693,0,0,18.5380218474681,4.4326609712963,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3294,4521,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3295,4521,资产负债表,2018-06-30,83.9596891141757,NaN,263.584837789737,106.390674933461,78.4686698708396,NaN,NaN,...,NaN,NaN,89.8029172279087,153.65723078171,90.8881868229085,0,0,200.59500271783,62.3045974841384,NaN
3296,4521,资产负债表,2017-12-31,9.37719037617333,NaN,-43.5592054015827,106.021652235336,56.1763231402441,NaN,NaN,...,NaN,NaN,73.0157446953147,-48.3267077923672,65.0756687246036,0,0,200.59500271783,52.7744930954003,NaN
3297,4521,资产负债表,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3298,4521,资产负债表,2016-12-31,461.581565839801,NaN,8.08538671883626,15.7176260322484,54.583487127809,NaN,NaN,...,NaN,NaN,20.3344783344313,-30.8720028271983,14.7713834854301,29.4276492508069,340.144399333883,99.3911320463477,164.164350531729,NaN
3299,4521,资产负债表,2015-12-31,-17.7300058968966,NaN,47.5325445605914,98.7393502349426,31.7263805236292,NaN,NaN,...,NaN,NaN,11.9227597887334,26.0660402923448,13.3037411745223,321.053,1530.37422390555,63.2729755665233,168.850051028796,NaN
3300,4522,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3301,4522,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3302,4522,资产负债表,2017-12-31,19.8286197787456,NaN,25.8674166383217,16.6561011295377,16.5631997349376,-15.9400668500802,NaN,...,-23.7805882683134,NaN,-18.1293090184176,NaN,-17.0201774585462,0,0,123.046173556964,21.6903123656086,NaN
3303,4522,资产负债表,2016-12-31,91.307021017384,NaN,32.9840559962883,58.3798264161355,57.0905175331186,NaN,NaN,...,18.1640132672527,NaN,86.1156959370099,NaN,86.1156959370099,111.68640287234,233.545530751822,-73.1556937059994,57.8984663647151,NaN
3304,4522,资产负债表,2015-12-31,508.961284603816,NaN,-63.69714622689,-1.38923541784211,57.1926891265011,NaN,NaN,...,-1.67427503151575,NaN,1.31495375890863,NaN,1.31495375890863,7.27844107176316,NaN,23.5294986196494,78.6812504044915,NaN
3305,4522,资产负债表,2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3306,4523,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3307,4523,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3308,4523,资产负债表,2017-12-31,23.1463378579444,NaN,-5.52532276132575,6.78347113384426,14.5707005095799,NaN,NaN,...,-2.01163598914243,NaN,-0.546121686140467,96.8569612021802,-0.478221252099212,0,0,0,32.2731337093465,NaN
3309,4523,资产负债表,2017-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3310,4523,资产负债表,2016-12-31,23.6885662949004,NaN,-3.0767026252637,10.7226349637066,18.141503442162,NaN,NaN,...,3.8475470006109,NaN,5.17962311335551,-45.9271928078314,5.11036904104552,0,0,0.916442736163798,38.8694659638213,NaN
3311,4523,资产负债表,2016-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3312,4524,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3313,4524,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3314,4524,资产负债表,2017-12-31,29.081694204374,NaN,-25.9689082475092,73.2929319696042,65.8842569508352,-0.951859816830326,NaN,...,59.2466444147172,NaN,63.8288183648333,NaN,63.8288183648333,0,0,232.933507407866,64.0134557936678,NaN
3315,4524,资产负债表,2016-12-31,2188.65400719632,NaN,233.533731895995,132.292058457657,168.724887161953,NaN,NaN,...,175.653248780033,NaN,131.456519544413,NaN,131.456519544413,300,114.060822771493,318.794127187998,262.818882966414,NaN
3316,4524,资产负债表,2015-12-31,-54.5834441511538,NaN,-16.3476043591003,93.2882744991038,104.32779085937,NaN,NaN,...,115.43911979771,NaN,99.731738556,NaN,99.731738556,50,0,NaN,243.906355641849,NaN
3317,4524,资产负债表,2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3318,4525,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3319,4525,资产负债表,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3320,4525,资产负债表,2017-12-31,17.9875751411618,38.5876800572698,123.067834260676,52.0053453165736,17.5120703224056,NaN,NaN,...,30.6581958287727,NaN,11.8466531359955,-44.6628016259238,-7.0340208112611,0,-4.003785842743,45.8289961711806,44.6314841753617,NaN
3321,4525,资产负债表,2016-12-31,121.127099986108,-15.4106105225374,-25.472724570899,2.96326292700026,4.40522794916509,NaN,NaN,...,143.913521685191,NaN,10.5577899318956,257.829486131994,43.7466554550902,212.597504571429,924.971120236824,114.358949714286,-29.6308006920738,NaN
3322,4525,资产负债表,2015-12-31,13.186003968145,-11.4922123001871,-25.1600404499937,8.86390330386085,-24.611806399396,NaN,NaN,...,86.1574911083031,NaN,54.2820071603886,-52.6369340443632,18.4058447386634,0,-62.567172414029,0,-32.3314547424324,NaN
3323,4525,资产负债表,2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
data.columns=pd.Index(['企业编号', '标题', '日期', '资产:货币资金(元)', '资产:应收账款(元)', '资产:其它应收款(元)',
       '资产:存货(元)', '资产:流动资产合计(元)', '资产:长期股权投资(元)', '资产:累计折旧(元)', '资产:固定资产(元)',
       '资产:无形资产(元)', '资产:资产总计(元)', '负债:应付账款(元)', '负债:预收账款(元)', '负债:存货跌价准备(元)',
       '负债:流动负债合计(元)', '负债:长期负债合计(元)', '负债:负债合计(元)', '权益:实收资本(或股本)(元)',
       '权益:资本公积金(元)', '权益:盈余公积金(元)', '权益:股东权益合计(元)', '流动比率'])

In [36]:
#将数字后的单位全部去除,只匹配数字，其余置为nan。
def convert(cell):
    pattern=r'[-\d.]'
    if cell == '--' or len(re.findall(pattern,cell)) == 0:
        return np.nan
    return float(''.join(re.findall(pattern, cell)))

In [37]:
datanew=data.iloc[:,3:]

In [38]:
datanew.applymap(str).applymap(convert)

,资产:货币资金(元),资产:应收账款(元),资产:其它应收款(元),资产:存货(元),资产:流动资产合计(元),资产:长期股权投资(元),资产:累计折旧(元),资产:固定资产(元),资产:无形资产(元),资产:资产总计(元),...,负债:预收账款(元),负债:存货跌价准备(元),负债:流动负债合计(元),负债:长期负债合计(元),负债:负债合计(元),权益:实收资本(或股本)(元),权益:资本公积金(元),权益:盈余公积金(元),权益:股东权益合计(元),流动比率
0,-20.001897,28.837577,36.503966,-0.971724,3.441627,274.666408,NaN,2.306479,-18.748927,10.759245,...,-26.101880,NaN,19.950099,-1.428539,11.671285,21.855883,-0.170198,13.197523,9.153346,NaN
1,-51.863140,17.236283,-27.138850,2.055449,-3.959421,909.019254,NaN,170.989391,22.025703,13.657832,...,-40.713456,NaN,10.876195,14.663734,12.126636,21.855883,-0.170198,13.197523,16.363521,NaN
2,-28.191187,24.979365,33.145886,6.665007,8.900362,1028.093389,NaN,149.840768,25.314413,26.195312,...,1.935688,NaN,14.638699,74.835701,32.028033,1.546570,4.670998,13.197523,17.868936,NaN
3,57.610649,46.203433,12.526461,13.805136,25.604504,859.914563,NaN,151.195772,25.030443,40.908690,...,-15.479841,NaN,34.013678,168.478892,60.885021,0.000000,0.044612,13.197523,15.220799,NaN
4,228.908313,92.317885,26.876784,43.111752,61.293855,613.615525,NaN,153.897403,124.151921,66.077966,...,188.147904,NaN,73.448185,307.758005,123.091257,0.000000,0.000016,8.795868,14.537735,NaN
5,525.904112,98.552375,101.587861,38.312316,75.817014,109.823901,NaN,-3.895977,76.070545,65.429841,...,165.737266,NaN,98.294760,283.383825,135.893043,0.000000,0.000016,8.795868,8.277653,NaN
6,-2.486276,5.040567,48.816950,93.601401,23.637760,-6.125943,NaN,-2.838222,9.692486,17.867093,...,153.255079,NaN,45.779578,336.215055,63.849436,0.000000,-6.799921,14.932624,0.822769,NaN
7,16.348821,32.840666,35.116548,38.724062,38.371685,-99.261369,NaN,-0.376246,30.830759,37.314928,...,86.809701,NaN,73.821828,305.333526,91.973439,3.525770,26.613238,14.932624,16.652397,NaN
8,17.019085,31.582990,20.839164,22.296722,29.335682,-99.075945,NaN,0.519832,20.009430,30.486713,...,110.964528,NaN,34.471247,256.057908,53.191565,107.051540,-8.894642,14.932624,21.230006,NaN
9,6.428171,61.800902,20.772957,16.908928,26.078406,-98.921512,NaN,1.257300,19.761091,26.850838,...,42.824871,NaN,46.114179,-13.537513,40.909961,107.051540,-8.894642,14.932624,20.644351,NaN
10,450.023508,18.324951,0.949488,15.222877,66.444783,-99.076670,NaN,-0.567575,15.657964,48.879911,...,117.231254,NaN,-12.575609,-27.647759,-13.694192,127.927365,216.181076,16.798795,103.595570,NaN
11,112.697731,22.704946,14.200821,0.170852,39.449220,4899.824550,NaN,-2.307250,-1.706758,33.461392,...,29.821344,NaN,-20.908404,-25.441168,-21.283612,120.164858,134.950340,16.798795,81.064952,NaN
12,-4.202343,-7.107693,62.209892,25.982507,-1.275229,NaN,NaN,-15.214989,-4.179436,1.023373,...,-60.622379,NaN,-15.079752,0.682148,-14.817332,0.000000,0.000000,13.196904,2.529893,NaN
13,-2.092489,-24.896003,2837.618347,17.123588,16.334142,NaN,NaN,-15.718727,-4.148325,14.481109,...,-30.872440,NaN,8.104455,-5.129972,7.838650,5.138917,30.000948,13.196904,15.162391,NaN
14,-32.703198,-24.244460,1285.091622,-47.786486,20.992988,NaN,NaN,-15.777898,-4.133759,16.591415,...,-60.307779,NaN,-4.909529,29.103883,-4.126393,5.138917,30.000948,13.196904,18.680409,NaN
15,34.121940,22.778291,1300.168660,19.371593,24.226529,NaN,NaN,-13.475336,-2.325119,17.300781,...,9.584896,NaN,21.271983,29.266875,21.512197,5.138917,30.000948,13.196904,16.937568,NaN
16,-46.486443,23.380047,-8.532784,12.456630,21.646455,NaN,NaN,-5.147994,51.153609,15.992867,...,13.917131,NaN,9.556040,-35.642799,8.289831,5.138917,30.000948,15.642460,16.782917,NaN
17,8.952872,17.452670,9.678204,15.361825,2.486899,NaN,NaN,-4.537528,51.138266,5.442143,...,157.044432,NaN,25.433210,-32.726628,23.292417,0.000000,0.000000,15.642460,3.899308,NaN
18,7.510000,5.130000,2298.000000,4.350000,18.500000,3264.000000,NaN,8.640000,1.210000,43.200000,...,4978.000000,NaN,10.100000,6.790000,16.900000,7.130000,11.200000,3800.000000,26.300000,1.84
19,5.600000,7.810000,1554.000000,4.320000,19.800000,2927.000000,6984.0,8.630000,1.210000,44.800000,...,4373.000000,NaN,14.400000,4.430000,18.800000,7.140000,11.200000,3800.000000,25.900000,1.37
20,6.570000,6.620000,1731.000000,3.990000,18.400000,3524.000000,NaN,8.620000,8058.000000,35.500000,...,2917.000000,NaN,11.800000,3.900000,15.700000,6.710000,6.230000,3800.000000,19.800000,1.55
21,7.390000,5.170000,988.000000,2.950000,16.500000,2841.000000,9941.0,8.670000,8055.000000,33.300000,...,2214.000000,NaN,9.950000,4.340000,14.300000,6.710000,6.230000,3800.000000,19.000000,1.66
22,9.430000,4.630000,1536.000000,2.770000,17.800000,3802.000000,NaN,7.180000,7961.000000,33.100000,...,1428.000000,NaN,9.790000,4.210000,14.000000,6.710000,6.480000,3609.000000,19.100000,1.82
23,9.370000,4.470000,1285.000000,2.430000,16.700000,3858.000000,4449.0,5.950000,8007.000000,30.500000,...,2136.000000,NaN,8.350000,3.790000,12.100000,6.710000,6.350000,3609.000000,18.400000,2.01
24,2.570000,4.030000,1095.000000,2.410000,9.540000,1644.000000,NaN,6.000000,8097.000000,21.200000,...,2059.000000,NaN,7.500000,3.020000,10.500000,6.150000,NaN,3609.000000,10.600000,1.27
25,4.050000,3.240000,1131.000000,1.720000,9.590000,494.000000,7506.0,5.990000,8181.000000,20.600000,...,2183.000000,NaN,7.280000,2.550000,9.830000,6.150000,2852.000000,3609.000000,10.800000,1.32
26,27.261557,31.657392,-78.360090,-1.010297,0.064550,NaN,NaN,0.055765,-2.700083,-1.940220,...,-30.198685,NaN,-36.334171,108.351134,-7.048367,0.000000,0.000000,18.538022,2.717190,NaN
27,7.691539,37.711987,-68.254009,-4.996801,6.742953,NaN,NaN,8.477509,-1.963466,-0.225179,...,-15.261430,NaN,-26.670611,88.232105,-3.046912,0.000000,0.000000,18.538022,2.696334,NaN
28,22.292125,74.183868,0.216450,14.113588,21.154323,NaN,NaN,17.996622,-1.873128,2.876352,...,-18.407491,NaN,-8.074349,23.612024,1.128935,0.000000,0.000000,18.538022,4.591689,NaN
29,11.553461,25.843080,-21.133691,8.144449,13.054578,NaN,NaN,20.489313,-1.697047,1.397746,...,26.414683,NaN,21.669876,-39.284383,-1.772883,0.000000,0.000000,18.538022,4.432661,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3295,83.959689,NaN,263.584838,106.390675,78.468670,NaN,NaN,81.322898,76.917016,77.424315,...,NaN,NaN,89.802917,153.657231,90.888187,0.000000,0.000000,200.595003,62.304597,NaN
3296,9.377190,NaN,-43.559205,106.021652,56.176323,NaN,NaN,84.999844,-1.225436,59.860333,...,NaN,NaN,73.015745,-48.326708,65.075669,0.000000,0.000000,200.595003,52.774493,NaN
3297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3298,461.581566,NaN,8.085387,15.717626,54.583487,NaN,NaN,14.100867,3116.158105,50.968933,...,NaN,NaN,20.334478,-30.872003,14.771383,29.427649,340.144399,99.391132,164.164351,NaN
3299,-17.730006,NaN,47.532545,98.739350,31.726381,NaN,NaN,25.732484,59.605764,31.776738,...,NaN,NaN,11.922760,26.066040,13.303741,321.053000,1530.374224,63.272976,168.850051,NaN
3300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3302,19.828620,NaN,25.867417,16.656101,16.563200,-15.940067,NaN,-4.228092,15.505166,13.157099,...,-23.780588,NaN,-18.129309,NaN,-17.020177,0.000000,0.000000,123.046174,21.690312,NaN
3303,91.307021,NaN,32.984056,58.379826,57.090518,NaN,NaN,24.454103,1486.920490,63.358002,...,18.164013,NaN,86.115696,NaN,86.115696,111.686403,233.545531,-73.155694,57.898466,NaN
3304,508.961285,NaN,-63.697146,-1.389235,57.192689,NaN,NaN,-0.806069,-2.652395,55.679956,...,-1.674275,NaN,1.314954,NaN,1.314954,7.278441,NaN,23.529499,78.681250,NaN
3305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3308,23.146338,NaN,-5.525323,6.783471,14.570701,NaN,NaN,-1.921088,-1.351118,11.096974,...,-2.011636,NaN,-0.546122,96.856961,-0.478221,0.000000,0.000000,0.000000,32.273134,NaN
3309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3310,23.688566,NaN,-3.076703,10.722635,18.141503,NaN,NaN,18.239397,-2.764218,14.990061,...,3.847547,NaN,5.179623,-45.927193,5.110369,0.000000,0.000000,0.916443,38.869466,NaN
3311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3314,29.081694,NaN,-25.968908,73.292932,65.884257,-0.951860,NaN,51.763195,322.659382,63.886233,...,59.246644,NaN,63.828818,NaN,63.828818,0.000000,0.000000,232.933507,64.013456,NaN
3315,2188.654007,NaN,233.533732,132.292058,168.724887,NaN,NaN,9910.954271,17.805630,160.821165,...,175.653249,NaN,131.456520,NaN,131.456520,300.000000,114.060823,318.794127,262.818883,NaN
3316,-54.583444,NaN,-16.347604,93.288274,104.327791,NaN,NaN,11.405130,-2.659988,120.384779,...,115.439120,NaN,99.731739,NaN,99.731739,50.000000,0.000000,NaN,243.906356,NaN
3317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3320,17.987575,38.587680,123.067834,52.005345,17.512070,NaN,NaN,14.515205,1.156648,11.287173,...,30.658196,NaN,11.846653,-44.662802,-7.034021,0.000000,-4.003786,45.828996,44.631484,NaN
3321,121.127100,-15.410611,-25.472725,2.963263,4.405228,NaN,NaN,16.214355,-5.778160,4.942089,...,143.913522,NaN,10.557790,257.829486,43.746655,212.597505,924.971120,114.358950,-29.630801,NaN
3322,13.186004,-11.492212,-25.160040,8.863903,-24.611806,NaN,NaN,3.777758,-24.624454,-15.213398,...,86.157491,NaN,54.282007,-52.636934,18.405845,0.000000,-62.567172,0.000000,-32.331455,NaN
3323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
#将两个表链接起来
data=data.iloc[:,:3].join(datanew)

In [40]:
data

,企业编号,标题,日期,资产:货币资金(元),资产:应收账款(元),资产:其它应收款(元),资产:存货(元),资产:流动资产合计(元),资产:长期股权投资(元),资产:累计折旧(元),...,负债:预收账款(元),负债:存货跌价准备(元),负债:流动负债合计(元),负债:长期负债合计(元),负债:负债合计(元),权益:实收资本(或股本)(元),权益:资本公积金(元),权益:盈余公积金(元),权益:股东权益合计(元),流动比率
0,4001,资产负债表,2018-09-30,-20.0018967774905,28.8375765408752,36.5039659507049,-0.971724107848274,3.4416265725397,274.666408322165,NaN,...,-26.1018803895912,NaN,19.9500989584298,-1.42853887678532,11.6712848103277,21.8558833179902,-0.170197623203871,13.1975225098742,9.15334629070048,NaN
1,4001,资产负债表,2018-06-30,-51.8631401663309,17.2362826984732,-27.1388501777185,2.05544943760258,-3.95942146160391,909.019254051886,NaN,...,-40.7134556707884,NaN,10.8761954713467,14.6637336705321,12.1266356876905,21.8558833179902,-0.170197623203871,13.1975225098742,16.3635208581447,NaN
2,4001,资产负债表,2018-03-31,-28.1911867099508,24.9793645148393,33.1458861357762,6.66500735296153,8.90036174213149,1028.09338942222,NaN,...,1.93568836902487,NaN,14.6386987432037,74.8357009643142,32.0280326640151,1.54656952180068,4.67099829416082,13.1975225098742,17.868936454965,NaN
3,4001,资产负债表,2017-12-31,57.6106491133635,46.2034331920527,12.5264612293939,13.805135544459,25.6045042338564,859.914563393134,NaN,...,-15.4798406401432,NaN,34.0136782271546,168.478891597327,60.8850208023843,0,0.044612176278595,13.1975225098742,15.2207992417913,NaN
4,4001,资产负债表,2017-09-30,228.908313246004,92.3178851782632,26.8767843253717,43.1117523971108,61.2938548693283,613.61552454555,NaN,...,188.14790362917,NaN,73.448185013665,307.758004735338,123.091256925406,0,0.0000162515811426267,8.79586765468184,14.53773466991,NaN
5,4001,资产负债表,2017-06-30,525.904111515149,98.5523752137099,101.587861235582,38.3123156779038,75.8170141805266,109.823900776914,NaN,...,165.737266101686,NaN,98.2947596130979,283.383824913928,135.893043359352,0,0.0000162515811426267,8.79586765468184,8.27765346560193,NaN
6,4002,资产负债表,2018-09-30,-2.4862762134382,5.04056652232327,48.8169500086462,93.60140108092,23.6377597150454,-6.12594343129359,NaN,...,153.255078972354,NaN,45.7795775133591,336.215054851594,63.8494363534094,0,-6.79992145491188,14.9326239609204,0.822769209056567,NaN
7,4002,资产负债表,2018-06-30,16.348821070719,32.8406657290712,35.116547934118,38.7240619526961,38.371684908717,-99.2613694291671,NaN,...,86.8097007570686,NaN,73.8218281623707,305.333525580277,91.9734390324281,3.52577020792311,26.6132381355038,14.9326239609204,16.6523971514367,NaN
8,4002,资产负债表,2018-03-31,17.0190854033921,31.5829904578714,20.8391642873932,22.2967220571351,29.3356817116881,-99.0759445689659,NaN,...,110.964527667953,NaN,34.4712471728347,256.057908062804,53.1915652764375,107.051540415846,-8.89464241781505,14.9326239609204,21.2300061305085,NaN
9,4002,资产负债表,2017-12-31,6.42817067932192,61.800902126843,20.7729572998542,16.9089276342772,26.0784064632665,-98.9215123628553,NaN,...,42.8248709339951,NaN,46.1141793554206,-13.5375127346181,40.9099605083278,107.051540415846,-8.89464241781505,14.9326239609204,20.6443509576707,NaN
10,4002,资产负债表,2017-09-30,450.023508039971,18.3249513069246,0.949488463723915,15.2228770979042,66.4447829098473,-99.0766701376809,NaN,...,117.231253689159,NaN,-12.5756090761851,-27.6477587163548,-13.6941923573661,127.927365371759,216.181076030951,16.798794546231,103.595569810666,NaN
11,4002,资产负债表,2017-06-30,112.697730858052,22.704945763411,14.200821176593,0.170851954855221,39.449219840917,4899.82454976211,NaN,...,29.821344243445,NaN,-20.9084042256342,-25.4411677335258,-21.283611592479,120.164858386454,134.95033995889,16.798794546231,81.0649515606113,NaN
12,4003,资产负债表,2018-09-30,-4.20234322408519,-7.10769294657838,62.2098919926415,25.9825069166784,-1.27522917552,NaN,NaN,...,-60.6223785113463,NaN,-15.0797516259298,0.682148451559306,-14.8173320930958,0,0,13.1969044538423,2.52989343014383,NaN
13,4003,资产负债表,2018-06-30,-2.09248854660494,-24.896002864003,2837.61834725575,17.123588112174,16.3341419293089,NaN,NaN,...,-30.8724397255863,NaN,8.10445536657994,-5.12997188351023,7.8386500947945,5.13891703703704,30.0009483066834,13.1969044538423,15.1623913690589,NaN
14,4003,资产负债表,2018-03-31,-32.7031980846981,-24.2444595345473,1285.09162178608,-47.7864864634908,20.9929880823726,NaN,NaN,...,-60.3077785640722,NaN,-4.90952914508275,29.1038828945848,-4.12639266220995,5.13891703703704,30.0009483066834,13.1969044538423,18.6804092728618,NaN
15,4003,资产负债表,2017-12-31,34.1219395508518,22.7782913846214,1300.16866044221,19.3715926968286,24.2265290438283,NaN,NaN,...,9.5848957740453,NaN,21.2719829649505,29.2668745424533,21.5121968524215,5.13891703703704,30.0009483066834,13.1969044538423,16.937567734517,NaN
16,4003,资产负债表,2017-09-30,-46.4864426059535,23.3800472719129,-8.53278394101907,12.4566304640951,21.6464546534834,NaN,NaN,...,13.9171311828198,NaN,9.55604001157909,-35.6427991179108,8.28983100646664,5.13891703703704,30.0009483066834,15.6424601649827,16.7829167539817,NaN
17,4003,资产负债表,2017-06-30,8.95287183639432,17.4526698648894,9.67820441939548,15.3618253289421,2.48689911796687,NaN,NaN,...,157.044432217919,NaN,25.4332103360409,-32.7266275857931,23.292416759405,0,0,15.6424601649827,3.89930797666047,NaN
18,4003,资产负债表,2017-09-30,7.51亿,5.13亿,2298万,4.35亿,18.5亿,3264万,--,...,4978万,--,10.1亿,6.79亿,16.9亿,7.13亿,11.2亿,3800万,26.3亿,1.84
19,4003,资产负债表,2017-06-30,5.60亿,7.81亿,1554万,4.32亿,19.8亿,2927万,6984万,...,4373万,--,14.4亿,4.43亿,18.8亿,7.14亿,11.2亿,3800万,25.9亿,1.37
20,4003,资产负债表,2017-03-31,6.57亿,6.62亿,1731万,3.99亿,18.4亿,3524万,--,...,2917万,--,11.8亿,3.90亿,15.7亿,6.71亿,6.23亿,3800万,19.8亿,1.55
21,4003,资产负债表,2016-12-31,7.39亿,5.17亿,988万,2.95亿,16.5亿,2841万,9941万,...,2214万,--,9.95亿,4.34亿,14.3亿,6.71亿,6.23亿,3800万,19.0亿,1.66
22,4003,资产负债表,2016-09-30,9.43亿,4.63亿,1536万,2.77亿,17.8亿,3802万,--,...,1428万,--,9.79亿,4.21亿,14.0亿,6.71亿,6.48亿,3609万,19.1亿,1.82
23,4003,资产负债表,2016-06-30,9.37亿,4.47亿,1285万,2.43亿,16.7亿,3858万,4449万,...,2136万,--,8.35亿,3.79亿,12.1亿,6.71亿,6.35亿,3609万,18.4亿,2.01
24,4003,资产负债表,2016-03-31,2.57亿,4.03亿,1095万,2.41亿,9.54亿,1644万,--,...,2059万,--,7.50亿,3.02亿,10.5亿,6.15亿,--,3609万,10.6亿,1.27
25,4003,资产负债表,2015-12-31,4.05亿,3.24亿,1131万,1.72亿,9.59亿,494万,7506万,...,2183万,--,7.28亿,2.55亿,9.83亿,6.15亿,2852万,3609万,10.8亿,1.32
26,4004,资产负债表,2018-09-30,27.261557279805,31.6573915474896,-78.3600904481522,-1.01029652840609,0.064550225278914,NaN,NaN,...,-30.1986851778224,NaN,-36.3341706547124,108.351133892639,-7.04836695726162,0,0,18.5380218474681,2.71719030357153,NaN
27,4004,资产负债表,2018-06-30,7.69153859921538,37.7119870770976,-68.2540086488966,-4.9968008291877,6.74295260755112,NaN,NaN,...,-15.2614299570417,NaN,-26.6706107134964,88.2321048580894,-3.04691212740927,0,0,18.5380218474681,2.69633425797522,NaN
28,4004,资产负债表,2018-03-31,22.2921247479952,74.1838684423957,0.216450304343801,14.1135878538585,21.1543234619921,NaN,NaN,...,-18.4074914695317,NaN,-8.07434935151496,23.6120243212728,1.12893487964822,0,0,18.5380218474681,4.59168905454901,NaN
29,4004,资产负债表,2017-12-31,11.5534611162565,25.8430799335558,-21.1336914022191,8.14444870355084,13.0545780068494,NaN,NaN,...,26.4146833414166,NaN,21.6698757466324,-39.2843829422996,-1.77288327258693,0,0,18.5380218474681,4.4326609712963,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3294,4521,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3295,4521,资产负债表,2018-06-30,83.9596891141757,NaN,263.584837789737,106.390674933461,78.4686698708396,NaN,NaN,...,NaN,NaN,89.8029172279087,153.65723078171,90.8881868229085,0,0,200.59500271783,62.3045974841384,NaN
3296,4521,资产负债表,2017-12-31,9.37719037617333,NaN,-43.5592054015827,106.021652235336,56.1763231402441,NaN,NaN,...,NaN,NaN,73.0157446953147,-48.3267077923672,65.0756687246036,0,0,200.59500271783,52.7744930954003,NaN
3297,4521,资产负债表,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3298,4521,资产负债表,2016-12-31,461.581565839801,NaN,8.08538671883626,15.7176260322484,54.583487127809,NaN,NaN,...,NaN,NaN,20.3344783344313,-30.8720028271983,14.7713834854301,29.4276492508069,340.144399333883,99.3911320463477,164.164350531729,NaN
3299,4521,资产负债表,2015-12-31,-17.7300058968966,NaN,47.5325445605914,98.7393502349426,31.7263805236292,NaN,NaN,...,NaN,NaN,11.9227597887334,26.0660402923448,13.3037411745223,321.053,1530.37422390555,63.2729755665233,168.850051028796,NaN
3300,4522,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3301,4522,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3302,4522,资产负债表,2017-12-31,19.8286197787456,NaN,25.8674166383217,16.6561011295377,16.5631997349376,-15.9400668500802,NaN,...,-23.7805882683134,NaN,-18.1293090184176,NaN,-17.0201774585462,0,0,123.046173556964,21.6903123656086,NaN
3303,4522,资产负债表,2016-12-31,91.307021017384,NaN,32.9840559962883,58.3798264161355,57.0905175331186,NaN,NaN,...,18.1640132672527,NaN,86.1156959370099,NaN,86.1156959370099,111.68640287234,233.545530751822,-73.1556937059994,57.8984663647151,NaN
3304,4522,资产负债表,2015-12-31,508.961284603816,NaN,-63.69714622689,-1.38923541784211,57.1926891265011,NaN,NaN,...,-1.67427503151575,NaN,1.31495375890863,NaN,1.31495375890863,7.27844107176316,NaN,23.5294986196494,78.6812504044915,NaN
3305,4522,资产负债表,2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3306,4523,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3307,4523,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3308,4523,资产负债表,2017-12-31,23.1463378579444,NaN,-5.52532276132575,6.78347113384426,14.5707005095799,NaN,NaN,...,-2.01163598914243,NaN,-0.546121686140467,96.8569612021802,-0.478221252099212,0,0,0,32.2731337093465,NaN
3309,4523,资产负债表,2017-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3310,4523,资产负债表,2016-12-31,23.6885662949004,NaN,-3.0767026252637,10.7226349637066,18.141503442162,NaN,NaN,...,3.8475470006109,NaN,5.17962311335551,-45.9271928078314,5.11036904104552,0,0,0.916442736163798,38.8694659638213,NaN
3311,4523,资产负债表,2016-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3312,4524,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3313,4524,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3314,4524,资产负债表,2017-12-31,29.081694204374,NaN,-25.9689082475092,73.2929319696042,65.8842569508352,-0.951859816830326,NaN,...,59.2466444147172,NaN,63.8288183648333,NaN,63.8288183648333,0,0,232.933507407866,64.0134557936678,NaN
3315,4524,资产负债表,2016-12-31,2188.65400719632,NaN,233.533731895995,132.292058457657,168.724887161953,NaN,NaN,...,175.653248780033,NaN,131.456519544413,NaN,131.456519544413,300,114.060822771493,318.794127187998,262.818882966414,NaN
3316,4524,资产负债表,2015-12-31,-54.5834441511538,NaN,-16.3476043591003,93.2882744991038,104.32779085937,NaN,NaN,...,115.43911979771,NaN,99.731738556,NaN,99.731738556,50,0,NaN,243.906355641849,NaN
3317,4524,资产负债表,2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3318,4525,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3319,4525,资产负债表,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3320,4525,资产负债表,2017-12-31,17.9875751411618,38.5876800572698,123.067834260676,52.0053453165736,17.5120703224056,NaN,NaN,...,30.6581958287727,NaN,11.8466531359955,-44.6628016259238,-7.0340208112611,0,-4.003785842743,45.8289961711806,44.6314841753617,NaN
3321,4525,资产负债表,2016-12-31,121.127099986108,-15.4106105225374,-25.472724570899,2.96326292700026,4.40522794916509,NaN,NaN,...,143.913521685191,NaN,10.5577899318956,257.829486131994,43.7466554550902,212.597504571429,924.971120236824,114.358949714286,-29.6308006920738,NaN
3322,4525,资产负债表,2015-12-31,13.186003968145,-11.4922123001871,-25.1600404499937,8.86390330386085,-24.611806399396,NaN,NaN,...,86.1574911083031,NaN,54.2820071603886,-52.6369340443632,18.4058447386634,0,-62.567172414029,0,-32.3314547424324,NaN
3323,4525,资产负债表,2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
data['日期'].value_counts()

2017-12-31    535
2017-06-30    532
2018-09-30    527
2018-06-30    527
2018-03-31    524
2017-09-30    522
2016-12-31     48
2017-03-31     24
2016-06-30     21
2016-09-30     20
2015-12-31     19
2016-03-31     12
2014-12-31      7
2018-12-31      4
2015-09-30      1
2013-12-31      1
Name: 日期, dtype: int64

In [42]:
#补全时间，规整时间的格式
pattern='\d\d\d\d-\d\d-\d\d'
for i in range(len(data)):
    if re.findall(pattern,data.iloc[i,2])==[]:
        data.iloc[i,2]='20'+data.iloc[i,2]

In [43]:
#去除企业编号与日期值同时相同的行，保留第一次出现的行
data.drop_duplicates(subset=['企业编号','日期'],keep='first',inplace=True)

In [44]:
#再次查看出现较多的时间
data['日期'].value_counts()

2017-12-31    523
2018-09-30    523
2018-06-30    522
2018-03-31    513
2017-06-30    509
2017-09-30    499
2016-12-31     45
2017-03-31     21
2016-06-30     18
2016-09-30     17
2015-12-31     16
2016-03-31      9
2014-12-31      7
2018-12-31      4
2015-09-30      1
2013-12-31      1
Name: 日期, dtype: int64

In [45]:
#将数量较少的日期全部丢弃
timelist=list(['2017-09-30','2017-12-31','2018-06-30','2018-09-30','2017-06-30','2018-03-31'])
data=data[data['日期'].isin(timelist)]
data

,企业编号,标题,日期,资产:货币资金(元),资产:应收账款(元),资产:其它应收款(元),资产:存货(元),资产:流动资产合计(元),资产:长期股权投资(元),资产:累计折旧(元),...,负债:预收账款(元),负债:存货跌价准备(元),负债:流动负债合计(元),负债:长期负债合计(元),负债:负债合计(元),权益:实收资本(或股本)(元),权益:资本公积金(元),权益:盈余公积金(元),权益:股东权益合计(元),流动比率
0,4001,资产负债表,2018-09-30,-20.0018967774905,28.8375765408752,36.5039659507049,-0.971724107848274,3.4416265725397,274.666408322165,NaN,...,-26.1018803895912,NaN,19.9500989584298,-1.42853887678532,11.6712848103277,21.8558833179902,-0.170197623203871,13.1975225098742,9.15334629070048,NaN
1,4001,资产负债表,2018-06-30,-51.8631401663309,17.2362826984732,-27.1388501777185,2.05544943760258,-3.95942146160391,909.019254051886,NaN,...,-40.7134556707884,NaN,10.8761954713467,14.6637336705321,12.1266356876905,21.8558833179902,-0.170197623203871,13.1975225098742,16.3635208581447,NaN
2,4001,资产负债表,2018-03-31,-28.1911867099508,24.9793645148393,33.1458861357762,6.66500735296153,8.90036174213149,1028.09338942222,NaN,...,1.93568836902487,NaN,14.6386987432037,74.8357009643142,32.0280326640151,1.54656952180068,4.67099829416082,13.1975225098742,17.868936454965,NaN
3,4001,资产负债表,2017-12-31,57.6106491133635,46.2034331920527,12.5264612293939,13.805135544459,25.6045042338564,859.914563393134,NaN,...,-15.4798406401432,NaN,34.0136782271546,168.478891597327,60.8850208023843,0,0.044612176278595,13.1975225098742,15.2207992417913,NaN
4,4001,资产负债表,2017-09-30,228.908313246004,92.3178851782632,26.8767843253717,43.1117523971108,61.2938548693283,613.61552454555,NaN,...,188.14790362917,NaN,73.448185013665,307.758004735338,123.091256925406,0,0.0000162515811426267,8.79586765468184,14.53773466991,NaN
5,4001,资产负债表,2017-06-30,525.904111515149,98.5523752137099,101.587861235582,38.3123156779038,75.8170141805266,109.823900776914,NaN,...,165.737266101686,NaN,98.2947596130979,283.383824913928,135.893043359352,0,0.0000162515811426267,8.79586765468184,8.27765346560193,NaN
6,4002,资产负债表,2018-09-30,-2.4862762134382,5.04056652232327,48.8169500086462,93.60140108092,23.6377597150454,-6.12594343129359,NaN,...,153.255078972354,NaN,45.7795775133591,336.215054851594,63.8494363534094,0,-6.79992145491188,14.9326239609204,0.822769209056567,NaN
7,4002,资产负债表,2018-06-30,16.348821070719,32.8406657290712,35.116547934118,38.7240619526961,38.371684908717,-99.2613694291671,NaN,...,86.8097007570686,NaN,73.8218281623707,305.333525580277,91.9734390324281,3.52577020792311,26.6132381355038,14.9326239609204,16.6523971514367,NaN
8,4002,资产负债表,2018-03-31,17.0190854033921,31.5829904578714,20.8391642873932,22.2967220571351,29.3356817116881,-99.0759445689659,NaN,...,110.964527667953,NaN,34.4712471728347,256.057908062804,53.1915652764375,107.051540415846,-8.89464241781505,14.9326239609204,21.2300061305085,NaN
9,4002,资产负债表,2017-12-31,6.42817067932192,61.800902126843,20.7729572998542,16.9089276342772,26.0784064632665,-98.9215123628553,NaN,...,42.8248709339951,NaN,46.1141793554206,-13.5375127346181,40.9099605083278,107.051540415846,-8.89464241781505,14.9326239609204,20.6443509576707,NaN
10,4002,资产负债表,2017-09-30,450.023508039971,18.3249513069246,0.949488463723915,15.2228770979042,66.4447829098473,-99.0766701376809,NaN,...,117.231253689159,NaN,-12.5756090761851,-27.6477587163548,-13.6941923573661,127.927365371759,216.181076030951,16.798794546231,103.595569810666,NaN
11,4002,资产负债表,2017-06-30,112.697730858052,22.704945763411,14.200821176593,0.170851954855221,39.449219840917,4899.82454976211,NaN,...,29.821344243445,NaN,-20.9084042256342,-25.4411677335258,-21.283611592479,120.164858386454,134.95033995889,16.798794546231,81.0649515606113,NaN
12,4003,资产负债表,2018-09-30,-4.20234322408519,-7.10769294657838,62.2098919926415,25.9825069166784,-1.27522917552,NaN,NaN,...,-60.6223785113463,NaN,-15.0797516259298,0.682148451559306,-14.8173320930958,0,0,13.1969044538423,2.52989343014383,NaN
13,4003,资产负债表,2018-06-30,-2.09248854660494,-24.896002864003,2837.61834725575,17.123588112174,16.3341419293089,NaN,NaN,...,-30.8724397255863,NaN,8.10445536657994,-5.12997188351023,7.8386500947945,5.13891703703704,30.0009483066834,13.1969044538423,15.1623913690589,NaN
14,4003,资产负债表,2018-03-31,-32.7031980846981,-24.2444595345473,1285.09162178608,-47.7864864634908,20.9929880823726,NaN,NaN,...,-60.3077785640722,NaN,-4.90952914508275,29.1038828945848,-4.12639266220995,5.13891703703704,30.0009483066834,13.1969044538423,18.6804092728618,NaN
15,4003,资产负债表,2017-12-31,34.1219395508518,22.7782913846214,1300.16866044221,19.3715926968286,24.2265290438283,NaN,NaN,...,9.5848957740453,NaN,21.2719829649505,29.2668745424533,21.5121968524215,5.13891703703704,30.0009483066834,13.1969044538423,16.937567734517,NaN
16,4003,资产负债表,2017-09-30,-46.4864426059535,23.3800472719129,-8.53278394101907,12.4566304640951,21.6464546534834,NaN,NaN,...,13.9171311828198,NaN,9.55604001157909,-35.6427991179108,8.28983100646664,5.13891703703704,30.0009483066834,15.6424601649827,16.7829167539817,NaN
17,4003,资产负债表,2017-06-30,8.95287183639432,17.4526698648894,9.67820441939548,15.3618253289421,2.48689911796687,NaN,NaN,...,157.044432217919,NaN,25.4332103360409,-32.7266275857931,23.292416759405,0,0,15.6424601649827,3.89930797666047,NaN
26,4004,资产负债表,2018-09-30,27.261557279805,31.6573915474896,-78.3600904481522,-1.01029652840609,0.064550225278914,NaN,NaN,...,-30.1986851778224,NaN,-36.3341706547124,108.351133892639,-7.04836695726162,0,0,18.5380218474681,2.71719030357153,NaN
27,4004,资产负债表,2018-06-30,7.69153859921538,37.7119870770976,-68.2540086488966,-4.9968008291877,6.74295260755112,NaN,NaN,...,-15.2614299570417,NaN,-26.6706107134964,88.2321048580894,-3.04691212740927,0,0,18.5380218474681,2.69633425797522,NaN
28,4004,资产负债表,2018-03-31,22.2921247479952,74.1838684423957,0.216450304343801,14.1135878538585,21.1543234619921,NaN,NaN,...,-18.4074914695317,NaN,-8.07434935151496,23.6120243212728,1.12893487964822,0,0,18.5380218474681,4.59168905454901,NaN
29,4004,资产负债表,2017-12-31,11.5534611162565,25.8430799335558,-21.1336914022191,8.14444870355084,13.0545780068494,NaN,NaN,...,26.4146833414166,NaN,21.6698757466324,-39.2843829422996,-1.77288327258693,0,0,18.5380218474681,4.4326609712963,NaN
30,4004,资产负债表,2017-09-30,-35.8753008610072,30.3028420121683,215.11271375906,-17.2253730178698,-24.2432277146135,NaN,NaN,...,62.5844097371401,NaN,1.1538823025581,-42.0368493272416,-12.1031048476978,0,0,11.1997212951275,3.66363771183865,NaN
31,4004,资产负债表,2017-06-30,66.7119921219164,99.7244991929844,174.61549022666,-19.7051563933227,53.2089983656207,NaN,NaN,...,14.270699462854,NaN,-0.203262011649788,-38.1390330242271,-11.3769491590699,5.32256763888889,194.248376133524,11.1997212951275,43.4230885536764,NaN
32,4005,资产负债表,2018-09-30,-85.3643862944838,-21.923521109933,6.62442551557273,8.04706264653328,28.3056970764846,0.200907820565937,NaN,...,12.4820893513133,NaN,120.446557246519,-80.4680726626201,23.7177573951867,0,0.882812001034535,0,-74.5114016728988,NaN
33,4005,资产负债表,2018-06-30,-92.3905506375679,-20.4352003212423,31.6332615003667,19.4634526155482,31.5517008337531,-1.11508330721634,NaN,...,45.6729006149364,NaN,133.806091676537,-72.0072683297873,27.5330762661949,0,0.882812001034535,0,-59.6048964857443,NaN
34,4005,资产负债表,2018-03-31,-87.1325486644514,-15.2049445339332,87.5484731680266,14.2990993355886,24.7165733161785,71.597334450053,NaN,...,20.210529481977,NaN,152.349605704746,-65.499308500382,25.4125861153089,0,3.92100031073919,0,-49.0151616629299,NaN
35,4005,资产负债表,2017-12-31,-74.0359568027974,24.6011940349071,1719.14123233023,27.1416445205717,40.8762748969834,73.035667245938,NaN,...,13.9093763150675,NaN,73.8102860068708,-0.191702805634023,40.4620153673395,0,3.92100031073919,0,-41.8472021205637,NaN
36,4005,资产负债表,2017-09-30,-61.1850135141491,41.9535672184956,1640.86312185327,26.3063979331188,0.761378270323147,61.495587129506,NaN,...,8.75194940158604,NaN,7.33741042556857,21.4857142779618,13.7132048269239,0,3.0116015299747,0,1.76537324721495,NaN
37,4005,资产负债表,2017-06-30,3.91282003835159,104.013234509147,730.338583683178,9.63595546054164,39.0770198918936,NaN,NaN,...,2.13189306921284,NaN,29.4065010170487,61.739291589668,44.3017853477334,0,3.0116015299747,49.2448104343527,24.2127154056509,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,4517,资产负债表,2017-12-31,0.0938637626436153,NaN,71.1959311842491,18.9493077850138,15.5436753503943,-11.9115073054777,NaN,...,-12.6301980428562,NaN,9.64262436355952,88.5916489657096,23.6883155012089,100,-43.8589068534171,80.6776377028394,15.396586594425,NaN
3274,4517,资产负债表,2017-06-30,39.6841966645117,47.7724145187526,-67.0840310942756,-3.00888732976821,21.5889171576682,-9.35881631751801,NaN,...,5.00883226756544,NaN,-11.7766445878127,54.7878496218337,-4.11851704164958,116.592408691093,9.28512736719273,55.7809873607062,53.7339044434553,NaN
3276,4518,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3277,4518,资产负债表,2018-06-30,31.881479477826,7.95593935064921,160.944052156179,16.6470658620089,22.2403320778455,NaN,NaN,...,18.4713889584878,NaN,-18.6166474767878,-14.6802722063117,-18.2200962876828,0,0,35.6971398244324,33.2614774383071,NaN
3278,4518,资产负债表,2017-12-31,52.7233218762722,38.9210281040023,166.473097785174,-1.98819257562841,29.5688842412753,NaN,NaN,...,-10.6390960269428,NaN,-7.73105474380127,-11.787047679581,-8.19282307201446,0,0,35.6971398244324,23.7559687249508,NaN
3279,4518,资产负债表,2017-06-30,39.2154365745236,152.03451766919,6.611825292606,-8.75260505154222,24.2475059902427,NaN,NaN,...,-23.1902545555795,NaN,3.19121349183222,-2.04858012441261,2.63809929165607,1.76547619047619,20.5508420192814,24.9296431538753,20.5015988983846,NaN
3282,4519,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3283,4519,资产负债表,2018-06-30,879.299816689012,42.0232729569393,265.64678403316,24.3968417894233,41.2215625389856,194.070755133263,NaN,...,81.1964912285854,NaN,11.6943632238856,95.4871626400335,27.5829399830678,11.1111129864585,36.1349640874008,112.863838409814,41.7638630288737,NaN
3284,4519,资产负债表,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3285,4519,资产负债表,2017-12-31,473.204147511338,-5.43093440867844,-22.2328874031294,151.347747840042,51.7972975430647,366.247626687696,NaN,...,131.58795444888,NaN,75.6884455344832,102.786864194219,81.2244489257497,218.787505515049,32.269599073373,112.863838409814,67.6337124946379,NaN
3286,4519,资产负债表,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3288,4520,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3289,4520,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3290,4520,资产负债表,2017-12-31,11.6727444551576,NaN,-82.2346005097223,102.071200490477,81.3293761315292,NaN,NaN,...,88.2916396236622,NaN,95.7034797448433,14.4734290611856,93.6730016256803,0,0,125.913002138225,51.2366821213198,NaN
3294,4521,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3295,4521,资产负债表,2018-06-30,83.9596891141757,NaN,263.584837789737,106.390674933461,78.4686698708396,NaN,NaN,...,NaN,NaN,89.8029172279087,153.65723078171,90.8881868229085,0,0,200.59500271783,62.3045974841384,NaN
3296,4521,资产负债表,2017-12-31,9.37719037617333,NaN,-43.5592054015827,106.021652235336,56.1763231402441,NaN,NaN,...,NaN,NaN,73.0157446953147,-48.3267077923672,65.0756687246036,0,0,200.59500271783,52.7744930954003,NaN
3297,4521,资产负债表,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3300,4522,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3301,4522,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3302,4522,资产负债表,2017-12-31,19.8286197787456,NaN,25.8674166383217,16.6561011295377,16.5631997349376,-15.9400668500802,NaN,...,-23.7805882683134,NaN,-18.1293090184176,NaN,-17.0201774585462,0,0,123.046173556964,21.6903123656086,NaN
3306,4523,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3307,4523,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3308,4523,资产负债表,2017-12-31,23.1463378579444,NaN,-5.52532276132575,6.78347113384426,14.5707005095799,NaN,NaN,...,-2.01163598914243,NaN,-0.546121686140467,96.8569612021802,-0.478221252099212,0,0,0,32.2731337093465,NaN
3312,4524,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3313,4524,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3314,4524,资产负债表,2017-12-31,29.081694204374,NaN,-25.9689082475092,73.2929319696042,65.8842569508352,-0.951859816830326,NaN,...,59.2466444147172,NaN,63.8288183648333,NaN,63.8288183648333,0,0,232.933507407866,64.0134557936678,NaN
3318,4525,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3319,4525,资产负债表,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3320,4525,资产负债表,2017-12-31,17.9875751411618,38.5876800572698,123.067834260676,52.0053453165736,17.5120703224056,NaN,NaN,...,30.6581958287727,NaN,11.8466531359955,-44.6628016259238,-7.0340208112611,0,-4.003785842743,45.8289961711806,44.6314841753617,NaN

In [46]:
#转换数据格式
def get_number(cell):
    if not isinstance(cell, str):
        return cell
    _ = re.findall(r'[\d.]+',cell)
    if not _:
        return None
    return float(_[0])

In [47]:
data.iloc[:,3:]=data.iloc[:,3:].applymap(get_number)

D:\ANACONDA2\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [48]:
data.sort_values(by=['企业编号','日期'],inplace=True)

D:\ANACONDA2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [49]:
#查看排序结果是否达到目标效果
data

,企业编号,标题,日期,资产:货币资金(元),资产:应收账款(元),资产:其它应收款(元),资产:存货(元),资产:流动资产合计(元),资产:长期股权投资(元),资产:累计折旧(元),...,负债:预收账款(元),负债:存货跌价准备(元),负债:流动负债合计(元),负债:长期负债合计(元),负债:负债合计(元),权益:实收资本(或股本)(元),权益:资本公积金(元),权益:盈余公积金(元),权益:股东权益合计(元),流动比率
5,4001,资产负债表,2017-06-30,525.904112,98.552375,101.587861,38.312316,75.817014,109.823901,NaN,...,165.737266,NaN,98.294760,283.383825,135.893043,0.000000,0.000016,8.795868,8.277653,NaN
4,4001,资产负债表,2017-09-30,228.908313,92.317885,26.876784,43.111752,61.293855,613.615525,NaN,...,188.147904,NaN,73.448185,307.758005,123.091257,0.000000,0.000016,8.795868,14.537735,NaN
3,4001,资产负债表,2017-12-31,57.610649,46.203433,12.526461,13.805136,25.604504,859.914563,NaN,...,15.479841,NaN,34.013678,168.478892,60.885021,0.000000,0.044612,13.197523,15.220799,NaN
2,4001,资产负债表,2018-03-31,28.191187,24.979365,33.145886,6.665007,8.900362,1028.093389,NaN,...,1.935688,NaN,14.638699,74.835701,32.028033,1.546570,4.670998,13.197523,17.868936,NaN
1,4001,资产负债表,2018-06-30,51.863140,17.236283,27.138850,2.055449,3.959421,909.019254,NaN,...,40.713456,NaN,10.876195,14.663734,12.126636,21.855883,0.170198,13.197523,16.363521,NaN
0,4001,资产负债表,2018-09-30,20.001897,28.837577,36.503966,0.971724,3.441627,274.666408,NaN,...,26.101880,NaN,19.950099,1.428539,11.671285,21.855883,0.170198,13.197523,9.153346,NaN
11,4002,资产负债表,2017-06-30,112.697731,22.704946,14.200821,0.170852,39.449220,4899.824550,NaN,...,29.821344,NaN,20.908404,25.441168,21.283612,120.164858,134.950340,16.798795,81.064952,NaN
10,4002,资产负债表,2017-09-30,450.023508,18.324951,0.949488,15.222877,66.444783,99.076670,NaN,...,117.231254,NaN,12.575609,27.647759,13.694192,127.927365,216.181076,16.798795,103.595570,NaN
9,4002,资产负债表,2017-12-31,6.428171,61.800902,20.772957,16.908928,26.078406,98.921512,NaN,...,42.824871,NaN,46.114179,13.537513,40.909961,107.051540,8.894642,14.932624,20.644351,NaN
8,4002,资产负债表,2018-03-31,17.019085,31.582990,20.839164,22.296722,29.335682,99.075945,NaN,...,110.964528,NaN,34.471247,256.057908,53.191565,107.051540,8.894642,14.932624,21.230006,NaN
7,4002,资产负债表,2018-06-30,16.348821,32.840666,35.116548,38.724062,38.371685,99.261369,NaN,...,86.809701,NaN,73.821828,305.333526,91.973439,3.525770,26.613238,14.932624,16.652397,NaN
6,4002,资产负债表,2018-09-30,2.486276,5.040567,48.816950,93.601401,23.637760,6.125943,NaN,...,153.255079,NaN,45.779578,336.215055,63.849436,0.000000,6.799921,14.932624,0.822769,NaN
17,4003,资产负债表,2017-06-30,8.952872,17.452670,9.678204,15.361825,2.486899,NaN,NaN,...,157.044432,NaN,25.433210,32.726628,23.292417,0.000000,0.000000,15.642460,3.899308,NaN
16,4003,资产负债表,2017-09-30,46.486443,23.380047,8.532784,12.456630,21.646455,NaN,NaN,...,13.917131,NaN,9.556040,35.642799,8.289831,5.138917,30.000948,15.642460,16.782917,NaN
15,4003,资产负债表,2017-12-31,34.121940,22.778291,1300.168660,19.371593,24.226529,NaN,NaN,...,9.584896,NaN,21.271983,29.266875,21.512197,5.138917,30.000948,13.196904,16.937568,NaN
14,4003,资产负债表,2018-03-31,32.703198,24.244460,1285.091622,47.786486,20.992988,NaN,NaN,...,60.307779,NaN,4.909529,29.103883,4.126393,5.138917,30.000948,13.196904,18.680409,NaN
13,4003,资产负债表,2018-06-30,2.092489,24.896003,2837.618347,17.123588,16.334142,NaN,NaN,...,30.872440,NaN,8.104455,5.129972,7.838650,5.138917,30.000948,13.196904,15.162391,NaN
12,4003,资产负债表,2018-09-30,4.202343,7.107693,62.209892,25.982507,1.275229,NaN,NaN,...,60.622379,NaN,15.079752,0.682148,14.817332,0.000000,0.000000,13.196904,2.529893,NaN
31,4004,资产负债表,2017-06-30,66.711992,99.724499,174.615490,19.705156,53.208998,NaN,NaN,...,14.270699,NaN,0.203262,38.139033,11.376949,5.322568,194.248376,11.199721,43.423089,NaN
30,4004,资产负债表,2017-09-30,35.875301,30.302842,215.112714,17.225373,24.243228,NaN,NaN,...,62.584410,NaN,1.153882,42.036849,12.103105,0.000000,0.000000,11.199721,3.663638,NaN
29,4004,资产负债表,2017-12-31,11.553461,25.843080,21.133691,8.144449,13.054578,NaN,NaN,...,26.414683,NaN,21.669876,39.284383,1.772883,0.000000,0.000000,18.538022,4.432661,NaN
28,4004,资产负债表,2018-03-31,22.292125,74.183868,0.216450,14.113588,21.154323,NaN,NaN,...,18.407491,NaN,8.074349,23.612024,1.128935,0.000000,0.000000,18.538022,4.591689,NaN
27,4004,资产负债表,2018-06-30,7.691539,37.711987,68.254009,4.996801,6.742953,NaN,NaN,...,15.261430,NaN,26.670611,88.232105,3.046912,0.000000,0.000000,18.538022,2.696334,NaN
26,4004,资产负债表,2018-09-30,27.261557,31.657392,78.360090,1.010297,0.064550,NaN,NaN,...,30.198685,NaN,36.334171,108.351134,7.048367,0.000000,0.000000,18.538022,2.717190,NaN
37,4005,资产负债表,2017-06-30,3.912820,104.013235,730.338584,9.635955,39.077020,NaN,NaN,...,2.131893,NaN,29.406501,61.739292,44.301785,0.000000,3.011602,49.244810,24.212715,NaN
36,4005,资产负债表,2017-09-30,61.185014,41.953567,1640.863122,26.306398,0.761378,61.495587,NaN,...,8.751949,NaN,7.337410,21.485714,13.713205,0.000000,3.011602,0.000000,1.765373,NaN
35,4005,资产负债表,2017-12-31,74.035957,24.601194,1719.141232,27.141645,40.876275,73.035667,NaN,...,13.909376,NaN,73.810286,0.191703,40.462015,0.000000,3.921000,0.000000,41.847202,NaN
34,4005,资产负债表,2018-03-31,87.132549,15.204945,87.548473,14.299099,24.716573,71.597334,NaN,...,20.210529,NaN,152.349606,65.499309,25.412586,0.000000,3.921000,0.000000,49.015162,NaN
33,4005,资产负债表,2018-06-30,92.390551,20.435200,31.633262,19.463453,31.551701,1.115083,NaN,...,45.672901,NaN,133.806092,72.007268,27.533076,0.000000,0.882812,0.000000,59.604896,NaN
32,4005,资产负债表,2018-09-30,85.364386,21.923521,6.624426,8.047063,28.305697,0.200908,NaN,...,12.482089,NaN,120.446557,80.468073,23.717757,0.000000,0.882812,0.000000,74.511402,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3272,4517,资产负债表,2018-06-30,2.075078,NaN,9.111376,3.887055,17.980607,18.071991,NaN,...,11.386085,NaN,17.383888,80.841977,29.169960,0.000000,0.000000,80.610596,10.967846,NaN
3271,4517,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3279,4518,资产负债表,2017-06-30,39.215437,152.034518,6.611825,8.752605,24.247506,NaN,NaN,...,23.190255,NaN,3.191213,2.048580,2.638099,1.765476,20.550842,24.929643,20.501599,NaN
3278,4518,资产负债表,2017-12-31,52.723322,38.921028,166.473098,1.988193,29.568884,NaN,NaN,...,10.639096,NaN,7.731055,11.787048,8.192823,0.000000,0.000000,35.697140,23.755969,NaN
3277,4518,资产负债表,2018-06-30,31.881479,7.955939,160.944052,16.647066,22.240332,NaN,NaN,...,18.471389,NaN,18.616647,14.680272,18.220096,0.000000,0.000000,35.697140,33.261477,NaN
3276,4518,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3286,4519,资产负债表,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3285,4519,资产负债表,2017-12-31,473.204148,5.430934,22.232887,151.347748,51.797298,366.247627,NaN,...,131.587954,NaN,75.688446,102.786864,81.224449,218.787506,32.269599,112.863838,67.633712,NaN
3284,4519,资产负债表,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3283,4519,资产负债表,2018-06-30,879.299817,42.023273,265.646784,24.396842,41.221563,194.070755,NaN,...,81.196491,NaN,11.694363,95.487163,27.582940,11.111113,36.134964,112.863838,41.763863,NaN
3282,4519,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3290,4520,资产负债表,2017-12-31,11.672744,NaN,82.234601,102.071200,81.329376,NaN,NaN,...,88.291640,NaN,95.703480,14.473429,93.673002,0.000000,0.000000,125.913002,51.236682,NaN
3289,4520,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3288,4520,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3297,4521,资产负债表,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3296,4521,资产负债表,2017-12-31,9.377190,NaN,43.559205,106.021652,56.176323,NaN,NaN,...,NaN,NaN,73.015745,48.326708,65.075669,0.000000,0.000000,200.595003,52.774493,NaN
3295,4521,资产负债表,2018-06-30,83.959689,NaN,263.584838,106.390675,78.468670,NaN,NaN,...,NaN,NaN,89.802917,153.657231,90.888187,0.000000,0.000000,200.595003,62.304597,NaN
3294,4521,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3302,4522,资产负债表,2017-12-31,19.828620,NaN,25.867417,16.656101,16.563200,15.940067,NaN,...,23.780588,NaN,18.129309,NaN,17.020177,0.000000,0.000000,123.046174,21.690312,NaN
3301,4522,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3300,4522,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3308,4523,资产负债表,2017-12-31,23.146338,NaN,5.525323,6.783471,14.570701,NaN,NaN,...,2.011636,NaN,0.546122,96.856961,0.478221,0.000000,0.000000,0.000000,32.273134,NaN
3307,4523,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3306,4523,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3314,4524,资产负债表,2017-12-31,29.081694,NaN,25.968908,73.292932,65.884257,0.951860,NaN,...,59.246644,NaN,63.828818,NaN,63.828818,0.000000,0.000000,232.933507,64.013456,NaN
3313,4524,资产负债表,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3312,4524,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3320,4525,资产负债表,2017-12-31,17.987575,38.587680,123.067834,52.005345,17.512070,NaN,NaN,...,30.658196,NaN,11.846653,44.662802,7.034021,0.000000,4.003786,45.828996,44.631484,NaN
3319,4525,资产负债表,2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3318,4525,资产负债表,2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
data=data.set_index(['企业编号','日期'])
data=data.unstack().reset_index().set_index('企业编号').T.drop('标题').drop('流动比率')

In [51]:
data=data.reindex(columns=list(range(4001,4526)))
data.to_pickle('上市信息财务信息资产负债表-testing.pickle')
data

企业编号                               4001      4002     4003       4004  \
                日期
资产:货币资金(元)      2017-06-30      525.904   112.698  8.95287     66.712
                2017-09-30      228.908   450.024  46.4864    35.8753
                2017-12-31      57.6106   6.42817  34.1219    11.5535
                2018-03-31      28.1912   17.0191  32.7032    22.2921
                2018-06-30      51.8631   16.3488  2.09249    7.69154
                2018-09-30      20.0019   2.48628  4.20234    27.2616
资产:应收账款(元)      2017-06-30      98.5524   22.7049  17.4527    99.7245
                2017-09-30      92.3179    18.325    23.38    30.3028
                2017-12-31      46.2034   61.8009  22.7783    25.8431
                2018-03-31      24.9794    31.583  24.2445    74.1839
                2018-06-30      17.2363   32.8407   24.896     37.712
                2018-09-30      28.8376   5.04057  7.10769    31.6574
资产:其它应收款(元)     2017-06-30      101.588   14.2008   9.6782    174.615
                2017-09-30      26.8768  0.949488  8.53278    215.113
                2017-12-31      12.5265    20.773  1300.17    21.1337
                2018-03-31      33.1459   20.8392  1285.09    0.21645
                2018-06-30      27.1389   35.1165  2837.62     68.254
                2018-09-30       36.504    48.817  62.2099    78.3601
资产:存货(元)        2017-06-30      38.3123  0.170852  15.3618    19.7052
                2017-09-30      43.1118   15.2229  12.4566    17.2254
                2017-12-31      13.8051   16.9089  19.3716    8.14445
                2018-03-31      6.66501   22.2967  47.7865    14.1136
                2018-06-30      2.05545   38.7241  17.1236     4.9968
                2018-09-30     0.971724   93.6014  25.9825     1.0103
资产:流动资产合计(元)    2017-06-30       75.817   39.4492   2.4869     53.209
                2017-09-30      61.2939   66.4448  21.6465    24.2432
                2017-12-31      25.6045   26.0784  24.2265    13.0546
                2018-03-31      8.90036   29.3357   20.993    21.1543
                2018-06-30      3.95942   38.3717  16.3341    6.74295
                2018-09-30      3.44163   23.6378  1.27523  0.0645502
...                                 ...       ...      ...        ...
负债:负债合计(元)      2017-06-30      135.893   21.2836  23.2924    11.3769
                2017-09-30      123.091   13.6942  8.28983    12.1031
                2017-12-31       60.885     40.91  21.5122    1.77288
                2018-03-31       32.028   53.1916  4.12639    1.12893
                2018-06-30      12.1266   91.9734  7.83865    3.04691
                2018-09-30      11.6713   63.8494  14.8173    7.04837
权益:实收资本(或股本)(元) 2017-06-30            0   120.165        0    5.32257
                2017-09-30            0   127.927  5.13892          0
                2017-12-31            0   107.052  5.13892          0
                2018-03-31      1.54657   107.052  5.13892          0
                2018-06-30      21.8559   3.52577  5.13892          0
                2018-09-30      21.8559         0        0          0
权益:资本公积金(元)     2017-06-30  1.62516e-05    134.95        0    194.248
                2017-09-30  1.62516e-05   216.181  30.0009          0
                2017-12-31    0.0446122   8.89464  30.0009          0
                2018-03-31        4.671   8.89464  30.0009          0
                2018-06-30     0.170198   26.6132  30.0009          0
                2018-09-30     0.170198   6.79992        0          0
权益:盈余公积金(元)     2017-06-30      8.79587   16.7988  15.6425    11.1997
                2017-09-30      8.79587   16.7988  15.6425    11.1997
                2017-12-31      13.1975   14.9326  13.1969     18.538
                2018-03-31      13.1975   14.9326  13.1969     18.538
                2018-06-30      13.1975   14.9326  13.1969     18.538
                2018-09-30      13.1975   14.9326  13.1969     18.538
权益:股东权益合计(元)    2017-06-30      8.27765    81.065  3.89931    43.4231
                2017-09-30      14.5377   103.596  16.7829    3.66364
                2017-12-31      15.2208   20.6444  16.9376    4.43266
                2018-03-31      17.8689     21.23  18.6804    4.59169
                2018-06-30      16.3635   16.6524  15.1624    2.69633
                2018-09-30      9.15335  0.822769  2.52989    2.71719

企业编号                            4005       4006      4007      4008      4009  \
                日期
资产:货币资金(元)      2017-06-30   3.91282    46.8075   32.9039   86.3702   67.5715
                2017-09-30    61.185    6.56332   17.2099   49.5799   67.8984
                2017-12-31    74.036    36.4955   1.05028   53.3756   90.6338
                2018-03-31   87.1325    10.4131   6.53249   60.3107   33.0722
                2018-06-30   92.3906    12.8639   20.7056   32.8428   2.38943
                2018-09-30   85.3644    41.3163   14.3382   59.3096   8.84618
资产:应收账款(元)      2017-06-30   104.013    89.9526  0.645266   25.1279   134.972
                2017-09-30   41.9536     74.796   5.90938   30.1638   114.038
                2017-12-31   24.6012    2.39312   3.96204   30.8829   42.3011
                2018-03-31   15.2049     7.2906   8.49565   10.6721   15.0467
                2018-06-30   20.4352    26.0025   12.8224   44.4148    37.209
                2018-09-30   21.9235    3.83651   22.9388   18.7647    32.943
资产:其它应收款(元)     2017-06-30   730.339    172.349   29.7508   88.6453   252.006
                2017-09-30   1640.86    139.194   6.85686   75.2501   190.394
                2017-12-31   1719.14    235.344   9.49654   22.8122   123.788
                2018-03-31   87.5485    1.95564   18.4041   16.7885   4.12171
                2018-06-30   31.6333    32.1055   6.22749   58.2124   6.73303
                2018-09-30   6.62443    8.04828   54.6951    47.296   1.14443
资产:存货(元)        2017-06-30   9.63596    60.0326     33.61    4.8622   59.8001
                2017-09-30   26.3064    81.3395   32.1764   9.62467   83.4082
                2017-12-31   27.1416    55.9665   4.39844   14.6643   45.2394
                2018-03-31   14.2991    44.0613  0.962285   14.7956   2.47899
                2018-06-30   19.4635    74.9542   9.59036   19.4622   4.83691
                2018-09-30   8.04706    49.9323   27.6116   17.5373   9.68282
资产:流动资产合计(元)    2017-06-30    39.077    12.2205   22.4988   13.2262   96.1618
                2017-09-30  0.761378    13.5754   21.8222   28.0059   93.1087
                2017-12-31   40.8763    7.04189   3.66045    31.705   79.5718
                2018-03-31   24.7166    13.9538    5.5902   33.2461   12.4363
                2018-06-30   31.5517    28.1716    2.2471   29.0528   1.72484
                2018-09-30   28.3057    31.5698   7.83818   3.92882   11.1268
...                              ...        ...       ...       ...       ...
负债:负债合计(元)      2017-06-30   44.3018    89.3525   14.7972    9.1154   94.0948
                2017-09-30   13.7132    85.2367   16.1222   43.8122   86.8994
                2017-12-31    40.462    27.1144   5.86406   18.0483   72.0693
                2018-03-31   25.4126    58.4139   8.70305   21.1111   3.69275
                2018-06-30   27.5331    93.9512  0.347575   22.9468   3.33163
                2018-09-30   23.7178    93.0191   4.92096   55.7696   6.73174
权益:实收资本(或股本)(元) 2017-06-30         0          0         0         0   25.7093
                2017-09-30         0          0         0         0   25.7093
                2017-12-31         0          0         0         0   25.7093
                2018-03-31         0          0         0         0   1.01981
                2018-06-30         0          0         0         0         0
                2018-09-30         0          0         0         0  0.221533
权益:资本公积金(元)     2017-06-30    3.0116  0.0174945         0  0.450668   770.662
                2017-09-30    3.0116  0.0174945         0  0.450668   737.519
                2017-12-31     3.921   0.453661         0   1.90868   731.994
                2018-03-31     3.921   0.453661         0   1.90868   3.98605
                2018-06-30  0.882812   0.453661         0   1.90868  0.466284
                2018-09-30  0.882812    1.05593         0   1.90868   1.14598
权益:盈余公积金(元)     2017-06-30   49.2448    11.0524   11.8773   5.39768   61.3851
                2017-09-30         0    11.0524   11.8773   5.39768   61.3851
                2017-12-31         0    12.6709         0         0   4.76808
                2018-03-31         0    12.6709         0         0   4.76808
                2018-06-30         0    12.6709         0         0   4.76808
                2018-09-30         0    12.6709         0         0   4.76808
权益:股东权益合计(元)    2017-06-30   24.2127    12.3224  0.924789   0.47233   146.372
                2017-09-30   1.76537    12.9975   1.07384   8.43594   138.147
                2017-12-31   41.8472    2.12747   1.98412   26.8989   144.219
                2018-03-31   49.0152    2.61772   3.36255   25.5377   11.0545
                2018-06-30   59.6049    3.69701   1.90529   25.9683   4.95188
                2018-09-30   74.5114    5.00797  0.259081   21.1862   0.29991

企业编号                             4010   ...        4516       4517     4518  \
                日期                      ...
资产:货币资金(元)      2017-06-30    105.807   ...         NaN    39.6842  39.2154
                2017-09-30    3.18369   ...         NaN        NaN      NaN
                2017-12-31    17.6325   ...     29.0193  0.0938638  52.7233
                2018-03-31    33.2167   ...         NaN        NaN      NaN
                2018-06-30    146.181   ...         NaN    2.07508  31.8815
                2018-09-30     184.06   ...         NaN        NaN      NaN
资产:应收账款(元)      2017-06-30    84.6373   ...         NaN    47.7724  152.035
                2017-09-30     61.476   ...         NaN        NaN      NaN
                2017-12-31    69.3621   ...     17.2968        NaN   38.921
                2018-03-31    68.7914   ...         NaN        NaN      NaN
                2018-06-30    84.2129   ...         NaN        NaN  7.95594
                2018-09-30    65.7301   ...         NaN        NaN      NaN
资产:其它应收款(元)     2017-06-30    57.3811   ...         NaN     67.084  6.61183
                2017-09-30    89.5597   ...         NaN        NaN      NaN
                2017-12-31    35.9256   ...     33.1916    71.1959  166.473
                2018-03-31    81.1057   ...         NaN        NaN      NaN
                2018-06-30    75.9433   ...         NaN    9.11138  160.944
                2018-09-30    63.1655   ...         NaN        NaN      NaN
资产:存货(元)        2017-06-30    67.2526   ...         NaN    3.00889  8.75261
                2017-09-30    66.1219   ...         NaN        NaN      NaN
                2017-12-31     86.964   ...     62.6232    18.9493  1.98819
                2018-03-31    90.5438   ...         NaN        NaN      NaN
                2018-06-30    70.9877   ...         NaN    3.88705  16.6471
                2018-09-30    90.9111   ...         NaN        NaN      NaN
资产:流动资产合计(元)    2017-06-30    72.8874   ...         NaN    21.5889  24.2475
                2017-09-30     14.187   ...         NaN        NaN      NaN
                2017-12-31    22.4835   ...     70.8839    15.5437  29.5689
                2018-03-31    36.3398   ...         NaN        NaN      NaN
                2018-06-30    37.7907   ...         NaN    17.9806  22.2403
                2018-09-30    50.3178   ...         NaN        NaN      NaN
...                               ...   ...         ...        ...      ...
负债:负债合计(元)      2017-06-30    49.4887   ...         NaN    4.11852   2.6381
                2017-09-30     36.103   ...         NaN        NaN      NaN
                2017-12-31    52.1755   ...     21.9673    23.6883  8.19282
                2018-03-31    71.0071   ...         NaN        NaN      NaN
                2018-06-30    81.8931   ...         NaN      29.17  18.2201
                2018-09-30    107.058   ...         NaN        NaN      NaN
权益:实收资本(或股本)(元) 2017-06-30    9.44077   ...         NaN    116.592  1.76548
                2017-09-30   0.233051   ...         NaN        NaN      NaN
                2017-12-31   0.233051   ...           0        100        0
                2018-03-31   0.233051   ...         NaN        NaN      NaN
                2018-06-30   0.233051   ...         NaN          0        0
                2018-09-30  0.0372694   ...         NaN        NaN      NaN
权益:资本公积金(元)     2017-06-30    61.4657   ...         NaN    9.28513  20.5508
                2017-09-30    2.55453   ...         NaN        NaN      NaN
                2017-12-31    2.04095   ...     50.0665    43.8589        0
                2018-03-31    1.98002   ...         NaN        NaN      NaN
                2018-06-30      2.498   ...         NaN          0        0
                2018-09-30    3.84041   ...         NaN        NaN      NaN
权益:盈余公积金(元)     2017-06-30    42.5234   ...         NaN     55.781  24.9296
                2017-09-30    42.5234   ...         NaN        NaN      NaN
                2017-12-31    29.0632   ...     209.063    80.6776  35.6971
                2018-03-31    29.0632   ...         NaN        NaN      NaN
                2018-06-30    29.0632   ...         NaN    80.6106  35.6971
                2018-09-30    29.0632   ...         NaN        NaN      NaN
权益:股东权益合计(元)    2017-06-30    42.7633   ...         NaN    53.7339  20.5016
                2017-09-30     12.896   ...         NaN        NaN      NaN
                2017-12-31    12.9874   ...       64.21    15.3966   23.756
                2018-03-31    12.7726   ...         NaN        NaN      NaN
                2018-06-30    10.4786   ...         NaN    10.9678  33.2615
                2018-09-30    9.79367   ...         NaN        NaN      NaN

企业编号                           4519     4520     4521     4522      4523  \
                日期
资产:货币资金(元)      2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  473.204  11.6727  9.37719  19.8286   23.1463
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30    879.3      NaN  83.9597      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
资产:应收账款(元)      2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  5.43093      NaN      NaN      NaN       NaN
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  42.0233      NaN      NaN      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
资产:其它应收款(元)     2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  22.2329  82.2346  43.5592  25.8674   5.52532
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  265.647      NaN  263.585      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
资产:存货(元)        2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  151.348  102.071  106.022  16.6561   6.78347
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  24.3968      NaN  106.391      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
资产:流动资产合计(元)    2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  51.7973  81.3294  56.1763  16.5632   14.5707
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  41.2216      NaN  78.4687      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
...                             ...      ...      ...      ...       ...
负债:负债合计(元)      2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  81.2244   93.673  65.0757  17.0202  0.478221
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  27.5829      NaN  90.8882      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
权益:实收资本(或股本)(元) 2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  218.788        0        0        0         0
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  11.1111      NaN        0      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
权益:资本公积金(元)     2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  32.2696        0        0        0         0
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30   36.135      NaN        0      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
权益:盈余公积金(元)     2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  112.864  125.913  200.595  123.046         0
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  112.864      NaN  200.595      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN
权益:股东权益合计(元)    2017-06-30      NaN      NaN      NaN      NaN       NaN
                2017-09-30      NaN      NaN      NaN      NaN       NaN
                2017-12-31  67.6337  51.2367  52.7745  21.6903   32.2731
                2018-03-31      NaN      NaN      NaN      NaN       NaN
                2018-06-30  41.7639      NaN  62.3046      NaN       NaN
                2018-09-30      NaN      NaN      NaN      NaN       NaN

企业编号                           4524     4525
                日期
资产:货币资金(元)      2017-06-30      NaN      NaN
                2017-09-30      NaN      NaN
                2017-12-31  29.0817  17.9876
                2018-03-31      NaN      NaN
                2018-06-30      NaN      NaN
                2018-09-30      NaN      NaN
资产:应收账款(元)      2017-06-30      NaN      NaN
                2017-09-30      NaN      NaN
                2017-12-31      NaN  38.5877
                2018-03-31      NaN      NaN
                2018-06-30      NaN      NaN
                2018-09-30      NaN      NaN
资产:其它应收款(元)     2017-06-30      NaN      NaN
                2017-09-30      NaN      NaN
                2017-12-31  25.9689  123.068
                2018-03-31      NaN      NaN
                2018-06-30      NaN      NaN
                2018-09-30      NaN      NaN
资产:存货(元)        2017-06-30      NaN      NaN
                2017-09-30      NaN      NaN
                2017-12-31  73.2929  52.0053
                2018-03-31      NaN      NaN
                2018-06-30      NaN      NaN
                2018-09-30      NaN      NaN
资产:流动资产合计(元)    2017-06-30      NaN      NaN
                2017-09-30      NaN      NaN
                2017-12-31  65.8843  17.5121
                2018-03-31      NaN      NaN
                2018-06-30      NaN      NaN
                2018-09-30      NaN      NaN
...                             ...      ...

In [52]:
data.index

MultiIndex(levels=[['标题', '资产:货币资金(元)', '资产:应收账款(元)', '资产:其它应收款(元)', '资产:存货(元)', '资产:流动资产合计(元)', '资产:长期股权投资(元)', '资产:累计折旧(元)', '资产:固定资产(元)', '资产:无形资产(元)', '资产:资产总计(元)', '负债:应付账款(元)', '负债:预收账款(元)', '负债:存货跌价准备(元)', '负债:流动负债合计(元)', '负债:长期负债合计(元)', '负债:负债合计(元)', '权益:实收资本(或股本)(元)', '权益:资本公积金(元)', '权益:盈余公积金(元)', '权益:股东权益合计(元)', '流动比率', '企业编号'], ['2017-06-30', '2017-09-30', '2017-12-31', '2018-03-31', '2018-06-30', '2018-09-30', '']],
           labels=[[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20], [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]],
           names=[None, '日期'])