In [1]:
from IPython.display import display
import pandas as pd
import csv
import random
import re
# import pyperclip
import numpy as np
import seaborn as sns
import requests
import matplotlib, matplotlib.pyplot as plt
import pprint
import os
import dateutil
import datetime
import glob

In [2]:
pd.options.display.max_rows = 10
sns.set()
matplotlib.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'sans-serif']

In [3]:
%matplotlib notebook

In [4]:
# def to_number(cell):
#     if isinstance(cell, tuple):
#         return True
#     return False

lst = []
for i in glob.glob('*.pickle'):
    if i != '企业评分.pickle' and i != '串联.pickle' and 'testing' in i and i != '串联测试集.pickle':
        lst.append(pd.read_pickle(i))
#         if lst[-1].applymap(to_number).any().any():
#             print(i)
#     print(i, lst[-1].shape, sep='\t')
# lst

In [6]:
concatenate = pd.concat(lst)
concatenate

企业编号,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,...,4516,4517,4518,4519,4520,4521,4522,4523,4524,4525
纳税人资格_一般纳税人,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
纳税人资格_其他,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
纳税人资格_内资企业采购国产设备,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
纳税人资格_出口退（免）税企业,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
纳税人资格_增值税一般纳税人,0,0,1,1,1,1,0,0,1,1,...,0,1,1,0,1,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
企业规模_500-2000人,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
企业规模_5000-10000人,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
运营状态_融资中,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
运营状态_运营中,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
项目成立时间,-6518,-8804,-5548,-7995,-5976,-6971,-4625,-5107,NaN,-5942,...,-4351,-3850,-5935,-2636,-3100,-4219,-6335,-4123,-2882,-7344

In [7]:
needtodel=[4133,4175,4181,4214,4400]

In [8]:
kk=concatenate.drop(needtodel,axis=1,inplace=True)

In [9]:
concatenate.to_pickle('串联测试集.pickle')