In [40]:
import pandas as pd
import numpy as np
import re
import datetime
import dateutil

In [41]:
data=pd.read_excel('赛题1测试数据集/作品著作权.xlsx',index_col=0)
data

          作品著作权类别   作品著作权登记日期 作品著作权创作完成日期 作品著作权首次发布日期
企业编号
4001           美术  2017-02-10  2016-07-01  2016-07-10
4001           美术  2015-02-16  2014-11-07         NaN
4001           美术  2015-02-16  2014-11-07         NaN
4001           美术  2015-02-16  2014-11-07         NaN
4001           美术  2015-02-17  2014-06-16  2014-08-18
4001           美术  2015-02-17  2014-12-09         NaN
4001           美术  2015-02-17  2011-06-16  2011-08-18
4001           美术  2017-04-01  2016-07-01  2016-07-10
4001           美术  2015-02-17  2014-12-09         NaN
4001           美术  2015-02-16  2014-11-01         NaN
4001           美术  2015-02-16  2014-11-01         NaN
4001           美术  2015-02-17  2014-07-18  2014-12-08
4011           美术  2013-03-07  2005-07-01         NaN
4011           美术  2013-03-07  2005-07-01         NaN
4011           美术  2013-03-07  2005-07-01         NaN
4011           美术  2013-03-07  2005-07-01         NaN
4014           美术  2015-09-22  2015-06-25         NaN
4015           美术  2012-11-08   1998-12-8  1998-12-24
4015           美术  2016-02-29  2015-04-10  2015-04-14
4015           美术  2016-02-29  2015-04-10  2015-04-14
4015           美术  2016-02-29  2015-04-10  2015-04-14
4015           美术  2016-02-29  2015-04-10  2015-04-14
4016           美术  2015-03-02  2004-08-12         NaN
4023         F 美术  2011-12-24  2011-09-27  2011-10-21
4023         F 美术  2011-12-24  2011-09-27  2011-10-21
4023         F 美术  2011-12-24  2011-08-24  2011-09-01
4023           美术  2016-06-16  2014-06-30  2014-09-01
4023         F 美术  2011-12-24  2011-09-27  2011-10-21
4023         F 美术  2011-12-24  2011-09-27  2011-10-21
4023           美术  2015-01-20  2014-06-30  2014-09-01
...           ...         ...         ...         ...
4500       地图、示意图  2014-01-17  2013-02-01         NaN
4500       地图、示意图  2014-01-17  2013-02-01         NaN
4500       地图、示意图  2014-01-17  2013-02-01         NaN
4500           美术  2018-10-10  2018-01-05         NaN
4507  工程设计图、产品设计图  2015-05-21  2014-07-01  2015-01-24
4507           美术  2018-02-02  2014-07-01  2015-01-24
4507           美术  2018-02-02  2010-09-01  2011-02-11
4507           美术  2018-02-02  2013-10-09  2013-11-11
4507           美术  2018-02-02  2014-10-01  2014-10-14
4507           美术  2018-02-02  1996-09-09  1996-10-10
4510           美术  2013-05-31  2012-12-29         NaN
4510           美术  2017-04-21  2016-12-17         NaN
4510           美术  2017-05-27  2007-07-31         NaN
4510           美术  2018-09-18  2018-03-16         NaN
4510           美术  2017-05-27  2010-01-01         NaN
4510           美术  2016-12-06  2016-07-08         NaN
4510           美术  2018-10-24  2018-06-25  2018-06-27
4510           美术  2017-02-06  2016-11-28         NaN
4510           美术  2017-04-12  2017-01-06         NaN
4515           美术  2018-04-04  2010-08-01         NaN
4518           美术  2017-12-07  2017-06-02         NaN
4518           美术  2013-04-08  2012-10-07  2012-10-07
4518           美术  2017-12-07  2017-06-09         NaN
4518           美术  2016-12-22  2016-08-09  2016-08-09
4522           其他  2018-03-21  2008-12-01         NaN
4523         F 美术         NaN  2008-07-01         NaN
4523           美术  2015-04-20  2009-10-15         NaN
4523           美术  2015-04-20  2008-07-01         NaN
4523         F 美术  2018-04-19  2017-07-01  2017-08-01
4523         F 美术  2018-04-19  2017-07-01  2017-08-01

[19614 rows x 4 columns]

In [42]:
#去除同一公司信息相同的行
data.drop_duplicates(keep='first',inplace=True)

In [43]:
count=pd.DataFrame(data.index.value_counts()).T.reindex(columns=list(range(4001,4526))).fillna(0)
count.index=pd.Index(['作品著作权_count'])

In [44]:
typelist=['美术','文字','F 美术','类似摄制电影方法创作的作品','其他','工程设计图、产品设计图','L 其他作品']
data=data[data['作品著作权类别'].isin(typelist)]

In [45]:
data

          作品著作权类别   作品著作权登记日期 作品著作权创作完成日期 作品著作权首次发布日期
企业编号
4001           美术  2017-02-10  2016-07-01  2016-07-10
4001           美术  2015-02-16  2014-11-07         NaN
4001           美术  2015-02-17  2014-06-16  2014-08-18
4001           美术  2015-02-17  2014-12-09         NaN
4001           美术  2015-02-17  2011-06-16  2011-08-18
4001           美术  2017-04-01  2016-07-01  2016-07-10
4001           美术  2015-02-16  2014-11-01         NaN
4001           美术  2015-02-17  2014-07-18  2014-12-08
4011           美术  2013-03-07  2005-07-01         NaN
4014           美术  2015-09-22  2015-06-25         NaN
4015           美术  2012-11-08   1998-12-8  1998-12-24
4015           美术  2016-02-29  2015-04-10  2015-04-14
4016           美术  2015-03-02  2004-08-12         NaN
4023         F 美术  2011-12-24  2011-09-27  2011-10-21
4023         F 美术  2011-12-24  2011-08-24  2011-09-01
4023           美术  2016-06-16  2014-06-30  2014-09-01
4023           美术  2015-01-20  2014-06-30  2014-09-01
4027           文字  2014-12-09  2014-08-20         NaN
4030           美术  2014-12-17  2014-04-03  2014-05-05
4030           美术  2014-12-17  2014-04-15  2014-05-05
4030           美术  2018-10-19  2003-05-30  2003-06-30
4033           美术  2012-01-22  2002-10-16  2002-11-16
4033           美术  2013-06-24  2010-12-26   2011-2-14
4033           美术  2012-01-22  2002-12-26  2003-02-14
4037           美术  2010-11-19  2004-08-24  2004-11-17
4040           美术  2017-01-09    2012-1-1    2012-1-1
4040           美术  2018-11-12  2018-07-31         NaN
4042           美术  2015-07-15  2015-03-11         NaN
4042           美术  2015-11-19  2015-04-24         NaN
4054           其他  2014-11-18  2014-10-20         NaN
...           ...         ...         ...         ...
4500           美术  2018-09-06  2016-07-11  2016-07-16
4500           美术  2018-10-10  2018-01-17  2018-01-17
4500           美术  2018-09-06  2015-08-16         NaN
4500           美术  2018-09-06  2016-04-14  2016-04-14
4500           美术  2018-09-06  2016-08-15  2016-08-16
4507  工程设计图、产品设计图  2015-05-21  2014-07-01  2015-01-24
4507           美术  2018-02-02  2014-07-01  2015-01-24
4507           美术  2018-02-02  2010-09-01  2011-02-11
4507           美术  2018-02-02  2013-10-09  2013-11-11
4507           美术  2018-02-02  2014-10-01  2014-10-14
4507           美术  2018-02-02  1996-09-09  1996-10-10
4510           美术  2013-05-31  2012-12-29         NaN
4510           美术  2017-04-21  2016-12-17         NaN
4510           美术  2017-05-27  2007-07-31         NaN
4510           美术  2018-09-18  2018-03-16         NaN
4510           美术  2017-05-27  2010-01-01         NaN
4510           美术  2016-12-06  2016-07-08         NaN
4510           美术  2018-10-24  2018-06-25  2018-06-27
4510           美术  2017-02-06  2016-11-28         NaN
4510           美术  2017-04-12  2017-01-06         NaN
4515           美术  2018-04-04  2010-08-01         NaN
4518           美术  2017-12-07  2017-06-02         NaN
4518           美术  2013-04-08  2012-10-07  2012-10-07
4518           美术  2017-12-07  2017-06-09         NaN
4518           美术  2016-12-22  2016-08-09  2016-08-09
4522           其他  2018-03-21  2008-12-01         NaN
4523         F 美术         NaN  2008-07-01         NaN
4523           美术  2015-04-20  2009-10-15         NaN
4523           美术  2015-04-20  2008-07-01         NaN
4523         F 美术  2018-04-19  2017-07-01  2017-08-01

[782 rows x 4 columns]

In [46]:
data_1=pd.get_dummies(data['作品著作权类别'],prefix='作品著作权类别').groupby('企业编号').sum().T.reindex(columns=list(range(4001,4526))).fillna(0)

In [47]:
#处理时间间隔
def to_datetime(cell):
    if not isinstance(cell, str):
        return cell
    try:
        return (dateutil.parser.parse(cell) - datetime.datetime(2019, 3, 5)).days
    except:
        print(cell)

In [48]:
data['作品著作权登记日期'].value_counts()

2015-08-14    142
2015-08-18     41
2018-03-06     24
2015-10-21     23
2015-08-17     23
2015-10-20     19
2016-02-17     15
2012-06-18     14
2015-10-19     13
2015-12-24     11
2012-10-11      9
2015-09-23      9
2018-05-22      9
2017-10-12      8
2014-12-11      8
2018-09-06      7
2011-12-27      7
2018-09-25      7
2016-02-16      6
2018-11-19      6
2016-05-25      5
2018-02-02      5
2017-09-26      5
2018-09-13      5
2015-08-28      5
2016-11-09      4
2015-02-17      4
2016-10-12      4
2018-11-07      4
2015-09-17      4
             ...
2012-05-02      1
2017-10-17      1
2017-05-04      1
2014-10-10      1
2013-08-30      1
2017-06-28      1
2014-05-08      1
2012-08-01      1
2018-11-26      1
2018-07-19      1
2018-11-16      1
2018-04-02      1
2011-08-26      1
2014-09-09      1
2016-12-21      1
2018-02-28      1
2018-11-12      1
2018-04-03      1
2018-10-22      1
2013-04-08      1
2014-05-19      1
2010-11-19      1
2018-11-08      1
2017-12-04      1
2018-08-06      1
2011-11-14      1
2011-08-25      1
2015-03-27      1
2016-12-06      1
2017-04-12      1
Name: 作品著作权登记日期, Length: 268, dtype: int64

In [49]:
data.replace(['国作登字-2012-A-00066200','国作登字-2013-F-00084814','国作登字-2013-F-00083953','国作登字-2012-A-00066200','国作登字-2013-F-00084814','国作登字-2013-F-00083953'],np.nan,inplace=True)

In [50]:
data_2=data[['作品著作权登记日期']].applymap(to_datetime).groupby('企业编号').mean().T.reindex(columns=list(range(4001,4526)))

In [51]:
data_3=data[['作品著作权创作完成日期']].applymap(to_datetime).groupby('企业编号').mean().T.reindex(columns=list(range(4001,4526)))

In [52]:
data['作品著作权首次发布日期'].replace('42285',np.nan,inplace=True)

In [53]:
data_4=data[['作品著作权首次发布日期']].applymap(to_datetime).groupby('企业编号').mean().T.reindex(columns=list(range(4001,4526)))

In [54]:
data=pd.concat([data_1,data_2,data_3,data_4,count])

In [55]:
filldata=['作品著作权类别_F 美术', '作品著作权类别_L 其他作品', '作品著作权类别_其他', '作品著作权类别_工程设计图、产品设计图',
       '作品著作权类别_文字', '作品著作权类别_类似摄制电影方法创作的作品', '作品著作权类别_美术', '作品著作权登记日期',
       '作品著作权创作完成日期', '作品著作权首次发布日期', '作品著作权_count']

In [56]:
data=data.reindex(filldata)
data.loc['作品著作权类别_L 其他作品',:]=data.loc['作品著作权类别_L 其他作品',:].fillna(0)

In [57]:
data

企业编号,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,...,4516,4517,4518,4519,4520,4521,4522,4523,4524,4525
作品著作权类别_F 美术,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,2.0,0.0,0.0
作品著作权类别_L 其他作品,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
作品著作权类别_其他,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
作品著作权类别_工程设计图、产品设计图,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
作品著作权类别_文字,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
作品著作权类别_类似摄制电影方法创作的作品,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
作品著作权类别_美术,8.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.00,0.0,0.0,0.0,0.0,2.0,0.0,0.0
作品著作权登记日期,-1290.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-966.50,NaN,NaN,NaN,-349.0,-1050.0,NaN,NaN
作品著作权创作完成日期,-1612.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-1138.25,NaN,NaN,NaN,-3746.0,-2959.5,NaN,NaN
作品著作权首次发布日期,-1580.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-1639.00,NaN,NaN,NaN,NaN,-581.0,NaN,NaN
作品著作权_count,8.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.00,0.0,0.0,0.0,1.0,4.0,0.0,0.0

In [58]:
data.to_pickle('作品著作权-testing.pickle')

In [59]:
data.index

Index(['作品著作权类别_F 美术', '作品著作权类别_L 其他作品', '作品著作权类别_其他', '作品著作权类别_工程设计图、产品设计图',
       '作品著作权类别_文字', '作品著作权类别_类似摄制电影方法创作的作品', '作品著作权类别_美术', '作品著作权登记日期',
       '作品著作权创作完成日期', '作品著作权首次发布日期', '作品著作权_count'],
      dtype='object')