In [1]:
from IPython.display import display
import pandas as pd
import csv
import random
import re
# import pyperclip
import numpy as np
import seaborn as sns
import requests
import matplotlib, matplotlib.pyplot as plt
import pprint
import os
import dateutil
import datetime

data=pd.read_excel("赛题1测试数据集/年报-社保信息.xlsx").drop_duplicates(keep='first').replace(
    "企业选择不公示",np.nan).replace("选择不公示",np.nan)
                                                                 
data

,企业编号,城镇职工基本养老保险人数,失业保险人数,职工基本医疗保险人数,工伤保险人数,生育保险人数,单位参加城镇职工基本养老保险缴费基数,单位参加失业保险缴费基数,单位参加职工基本医疗保险缴费基数,单位参加工伤保险缴费基数,...,参加失业保险本期实际缴费金额,参加职工基本医疗保险本期实际缴费金额,参加工伤保险本期实际缴费金额,参加生育保险本期实际缴费金额,单位参加城镇职工基本养老保险累计欠缴金额,单位参加失业保险累计欠缴金额,单位参加职工基本医疗保险累计欠缴金额,单位参加工伤保险累计欠缴金额,单位参加生育保险累计欠缴金额,年报年份
0,4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
1,4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2,4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
3,4001,666人,666人,666人,666人,666人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
4,4001,615人,615人,615人,615人,615人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
5,4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
6,4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
7,4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
8,4002,288人,373人,373人,373人,373人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
9,4002,370人,370人,370人,370人,370人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
10,4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
11,4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
12,4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
13,4003,468人,468人,468人,468人,468人,0.18198万元,0.18198万元,0.18198万元,NaN,...,18.2万元,127.4万元,23.7万元,18.2万元,0万元,0万元,0万元,0万元,0万元,2016
14,4003,472人,472人,472人,472人,472人,7049万元,7049万元,7049万元,NaN,...,1.6778万元,15.0997万元,2.18107万元,0.167747万元,0万元,0万元,0万元,0万元,0万元,2017
15,4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
16,4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
17,4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
18,4004,1120人,1120人,1121人,1120人,1120人,5923万元,5923万元,5928万元,NaN,...,97万元,666万元,39万元,30万元,0万元,0万元,0万元,0万元,0万元,2016
19,4004,1036人,1036人,1037人,1036人,1036人,5982万元,5982万元,5987万元,NaN,...,71万元,673万元,24万元,30万元,0万元,0万元,0万元,0万元,0万元,2017
20,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
21,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
22,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
23,4005,684人,678人,678人,678人,678人,211.106万元,211.106万元,211.106万元,NaN,...,37.0331万元,222.1803万元,24.6867万元,12.3464万元,0万元,0万元,0万元,0万元,0万元,2016
24,4005,700人,700人,700人,700人,700人,190.05万元,190.05万元,190.05万元,NaN,...,24.21万元,230.01万元,24.47万元,12.24万元,0万元,0万元,0万元,0万元,0万元,2017
25,4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
26,4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
27,4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
28,4006,777人,777人,777人,777人,777人,2614.76万元,2614.76万元,2615.445万元,NaN,...,39.0672万元,300.773425万元,39.21008万元,13.0738万元,0万元,0万元,0万元,0万元,0万元,2016
29,4006,726人,726人,726人,726人,726人,2603.19万元,1743.93万元,2603.19万元,NaN,...,13.02万元,234.29万元,36.44万元,13.02万元,0万元,0万元,0万元,0万元,0万元,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2605,4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2606,4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2607,4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
2608,4520,254人,254人,254人,254人,254人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
2609,4520,391人,391人,391人,391人,391人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
2610,4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2611,4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
2612,4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2613,4521,1543人,1543人,1543人,1543人,1543人,3258.37万元,3897.6万元,12309.01万元,NaN,...,54.28万元,759.99万元,19.46万元,19.9万元,0万元,0万元,0万元,0万元,0万元,2016
2614,4521,2096人,2096人,2095人,2096人,2095人,4679.348万元,4502.703万元,15387.3883万元,NaN,...,67.239902万元,96.421534万元,29.476257万元,23.384855万元,0万元,0万元,0万元,0万元,0万元,2017
2615,4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2616,4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2617,4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
2618,4522,238人,238人,238人,238人,238人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
2619,4522,301人,301人,301人,301人,301人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
2620,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
2621,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2622,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2623,4523,667人,667人,667人,667人,667人,0万元,0万元,0万元,NaN,...,0万元,0万元,0万元,0万元,0万元,0万元,0万元,0万元,0万元,2016
2624,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
2625,4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2626,4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
2627,4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2628,4524,2062人,2062人,2062人,2062人,2062人,0.000000万元,0.000000万元,0.000000万元,0.000000万元,...,7.140000万元,328.280000万元,5.710000万元,14.270000万元,1427.330000万元,1427.330000万元,1427.330000万元,NaN,1427.330000万元,2016
2629,4524,258人,258人,258人,258人,258人,0.000000万元,0.000000万元,0.000000万元,0.000000万元,...,10.510000万元,468.250000万元,8.400000万元,21.020000万元,2102.269000万元,2102.269000万元,2102.269000万元,NaN,2102.269000万元,2017
2630,4525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
2631,4525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
2632,4525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
2633,4525,3072人,3072人,3072人,3072人,3072人,28493.45万元,7687.41万元,29625.12万元,NaN,...,107.62万元,2427.85万元,112.91万元,143.41万元,0万元,0万元,0万元,0万元,0万元,2016
2634,4525,3221人,3221人,3221人,3221人,3221人,29695.5万元,7695.77万元,30671.77万元,NaN,...,114.82万元,2514.49万元,187.09万元,148.41万元,0万元,0万元,0万元,0万元,0万元,2017

In [2]:
def change(cell):
    return float(cell)
data["年报年份"]=data[["年报年份"]].applymap(change)
data

,企业编号,城镇职工基本养老保险人数,失业保险人数,职工基本医疗保险人数,工伤保险人数,生育保险人数,单位参加城镇职工基本养老保险缴费基数,单位参加失业保险缴费基数,单位参加职工基本医疗保险缴费基数,单位参加工伤保险缴费基数,...,参加失业保险本期实际缴费金额,参加职工基本医疗保险本期实际缴费金额,参加工伤保险本期实际缴费金额,参加生育保险本期实际缴费金额,单位参加城镇职工基本养老保险累计欠缴金额,单位参加失业保险累计欠缴金额,单位参加职工基本医疗保险累计欠缴金额,单位参加工伤保险累计欠缴金额,单位参加生育保险累计欠缴金额,年报年份
0,4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
1,4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2,4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
3,4001,666人,666人,666人,666人,666人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0
4,4001,615人,615人,615人,615人,615人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.0
5,4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
6,4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
7,4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
8,4002,288人,373人,373人,373人,373人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0
9,4002,370人,370人,370人,370人,370人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.0
10,4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
11,4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
12,4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
13,4003,468人,468人,468人,468人,468人,0.18198万元,0.18198万元,0.18198万元,NaN,...,18.2万元,127.4万元,23.7万元,18.2万元,0万元,0万元,0万元,0万元,0万元,2016.0
14,4003,472人,472人,472人,472人,472人,7049万元,7049万元,7049万元,NaN,...,1.6778万元,15.0997万元,2.18107万元,0.167747万元,0万元,0万元,0万元,0万元,0万元,2017.0
15,4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
16,4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
17,4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
18,4004,1120人,1120人,1121人,1120人,1120人,5923万元,5923万元,5928万元,NaN,...,97万元,666万元,39万元,30万元,0万元,0万元,0万元,0万元,0万元,2016.0
19,4004,1036人,1036人,1037人,1036人,1036人,5982万元,5982万元,5987万元,NaN,...,71万元,673万元,24万元,30万元,0万元,0万元,0万元,0万元,0万元,2017.0
20,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
21,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
22,4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
23,4005,684人,678人,678人,678人,678人,211.106万元,211.106万元,211.106万元,NaN,...,37.0331万元,222.1803万元,24.6867万元,12.3464万元,0万元,0万元,0万元,0万元,0万元,2016.0
24,4005,700人,700人,700人,700人,700人,190.05万元,190.05万元,190.05万元,NaN,...,24.21万元,230.01万元,24.47万元,12.24万元,0万元,0万元,0万元,0万元,0万元,2017.0
25,4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
26,4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
27,4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
28,4006,777人,777人,777人,777人,777人,2614.76万元,2614.76万元,2615.445万元,NaN,...,39.0672万元,300.773425万元,39.21008万元,13.0738万元,0万元,0万元,0万元,0万元,0万元,2016.0
29,4006,726人,726人,726人,726人,726人,2603.19万元,1743.93万元,2603.19万元,NaN,...,13.02万元,234.29万元,36.44万元,13.02万元,0万元,0万元,0万元,0万元,0万元,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2605,4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
2606,4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2607,4520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
2608,4520,254人,254人,254人,254人,254人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0
2609,4520,391人,391人,391人,391人,391人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.0
2610,4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2611,4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
2612,4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
2613,4521,1543人,1543人,1543人,1543人,1543人,3258.37万元,3897.6万元,12309.01万元,NaN,...,54.28万元,759.99万元,19.46万元,19.9万元,0万元,0万元,0万元,0万元,0万元,2016.0
2614,4521,2096人,2096人,2095人,2096人,2095人,4679.348万元,4502.703万元,15387.3883万元,NaN,...,67.239902万元,96.421534万元,29.476257万元,23.384855万元,0万元,0万元,0万元,0万元,0万元,2017.0
2615,4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
2616,4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2617,4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
2618,4522,238人,238人,238人,238人,238人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0
2619,4522,301人,301人,301人,301人,301人,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.0
2620,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
2621,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2622,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
2623,4523,667人,667人,667人,667人,667人,0万元,0万元,0万元,NaN,...,0万元,0万元,0万元,0万元,0万元,0万元,0万元,0万元,0万元,2016.0
2624,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.0
2625,4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2626,4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
2627,4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
2628,4524,2062人,2062人,2062人,2062人,2062人,0.000000万元,0.000000万元,0.000000万元,0.000000万元,...,7.140000万元,328.280000万元,5.710000万元,14.270000万元,1427.330000万元,1427.330000万元,1427.330000万元,NaN,1427.330000万元,2016.0
2629,4524,258人,258人,258人,258人,258人,0.000000万元,0.000000万元,0.000000万元,0.000000万元,...,10.510000万元,468.250000万元,8.400000万元,21.020000万元,2102.269000万元,2102.269000万元,2102.269000万元,NaN,2102.269000万元,2017.0
2630,4525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.0
2631,4525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.0
2632,4525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.0
2633,4525,3072人,3072人,3072人,3072人,3072人,28493.45万元,7687.41万元,29625.12万元,NaN,...,107.62万元,2427.85万元,112.91万元,143.41万元,0万元,0万元,0万元,0万元,0万元,2016.0
2634,4525,3221人,3221人,3221人,3221人,3221人,29695.5万元,7695.77万元,30671.77万元,NaN,...,114.82万元,2514.49万元,187.09万元,148.41万元,0万元,0万元,0万元,0万元,0万元,2017.0

In [3]:
data=data.set_index('年报年份').loc[[2016.0,2017.0],:].reset_index()
data

,年报年份,企业编号,城镇职工基本养老保险人数,失业保险人数,职工基本医疗保险人数,工伤保险人数,生育保险人数,单位参加城镇职工基本养老保险缴费基数,单位参加失业保险缴费基数,单位参加职工基本医疗保险缴费基数,...,参加城镇职工基本养老保险本期实际缴费金额,参加失业保险本期实际缴费金额,参加职工基本医疗保险本期实际缴费金额,参加工伤保险本期实际缴费金额,参加生育保险本期实际缴费金额,单位参加城镇职工基本养老保险累计欠缴金额,单位参加失业保险累计欠缴金额,单位参加职工基本医疗保险累计欠缴金额,单位参加工伤保险累计欠缴金额,单位参加生育保险累计欠缴金额
0,2016.0,4001,666人,666人,666人,666人,666人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016.0,4002,288人,373人,373人,373人,373人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016.0,4003,468人,468人,468人,468人,468人,0.18198万元,0.18198万元,0.18198万元,...,327.6万元,18.2万元,127.4万元,23.7万元,18.2万元,0万元,0万元,0万元,0万元,0万元
3,2016.0,4004,1120人,1120人,1121人,1120人,1120人,5923万元,5923万元,5928万元,...,1649万元,97万元,666万元,39万元,30万元,0万元,0万元,0万元,0万元,0万元
4,2016.0,4005,684人,678人,678人,678人,678人,211.106万元,211.106万元,211.106万元,...,710.45万元,37.0331万元,222.1803万元,24.6867万元,12.3464万元,0万元,0万元,0万元,0万元,0万元
5,2016.0,4006,777人,777人,777人,777人,777人,2614.76万元,2614.76万元,2615.445万元,...,723.42455万元,39.0672万元,300.773425万元,39.21008万元,13.0738万元,0万元,0万元,0万元,0万元,0万元
6,2016.0,4007,2280人,2280人,2281人,2280人,2280人,829.6835万元,829.6835万元,830.4435万元,...,1922.9671万元,116.2425万元,740.0215万元,89.4976万元,99.4417万元,0万元,0万元,0万元,0万元,0万元
7,2016.0,4008,236人,236人,236人,236人,236人,0.32万元,0.28万元,0.28万元,...,284.78万元,12.08万元,92.1万元,7.15万元,6.28万元,0万元,0万元,0万元,0万元,0万元
8,2016.0,4009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2016.0,4010,68人,68人,68人,68人,68人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2016.0,4011,138人,138人,138人,138人,138人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2016.0,4012,895人,895人,895人,895人,895人,415.39万元,415.39万元,415.39万元,...,821.85万元,45.66万元,319.61万元,49.31万元,22.83万元,0万元,0万元,0万元,0万元,0万元
12,2016.0,4013,497人,497人,497人,497人,497人,4769.86万元,4769.86万元,4769.86万元,...,953.97万元,47.69万元,476.99万元,49.61万元,47.69万元,0万元,0万元,0万元,0万元,0万元
13,2016.0,4014,693人,693人,693人,693人,693人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2016.0,4015,83人,83人,83人,83人,83人,0.203万元,0.203万元,0.6753万元,...,4.05539万元,0.252735万元,1.1469万元,0.093121万元,0.095万元,0万元,0万元,0万元,0万元,0万元
15,2016.0,4016,672人,672人,674人,672人,672人,2237.08万元,2237.08万元,2244.25万元,...,610.57万元,32.4万元,224.28万元,55.93万元,11.19万元,0万元,0万元,0万元,0万元,0万元
16,2016.0,4017,451人,451人,451人,451人,451人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2016.0,4018,290人,290人,290人,290人,290人,2175.51202万元,1885.0821万元,2175.51202万元,...,609.16981万元,28.29537万元,246.56768万元,7.03225万元,18.85087万元,0万元,0万元,0万元,0万元,0万元
18,2016.0,4019,761人,761人,761人,761人,761人,0.4178万元,0.4178万元,0.4765万元,...,1030.14万元,38.15万元,524.91万元,34.81万元,34.81万元,0,0,0,0,0
19,2016.0,4020,1389人,1389人,1389人,1389人,1389人,3928.3404万元,3227.2726万元,6697.6154万元,...,547.1745万元,39.0286万元,241.88万元,16.416万元,20.845万元,0万元,0万元,0万元,0万元,0万元
20,2016.0,4021,1155人,1155人,1155人,1155人,1155人,403.15万元,403.15万元,403.15万元,...,1227.15万元,69.7万元,418.24万元,96.72万元,32.53万元,0万元,0万元,0万元,0万元,0万元
21,2016.0,4022,382人,382人,382人,540人,382人,NaN,万元,万元,...,万元,万元,万元,万元,万元,万元,万元,万元,万元,万元
22,2016.0,4023,187人,188人,188人,188人,188人,899.0108万元,452.487万元,1309.6542万元,...,42.31万元,0.0882万元,4.008519万元,0.001525万元,0.02261万元,0万元,0万元,0万元,0万元,0万元
23,2016.0,4024,210人,210人,210人,210人,210人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2016.0,4025,595人,595人,595人,595人,595人,0万元,0万元,0万元,...,546.48万元,31.52万元,189.16万元,28.37万元,27.01万元,0万元,0万元,0万元,0万元,0万元
25,2016.0,4026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2016.0,4027,403人,403人,408人,415人,406人,128.73万元,131.46万元,169.22万元,...,285万元,21万元,116万元,3万元,9万元,0万元,0万元,0万元,0万元,0万元
27,2016.0,4028,452人,452人,452人,452人,452人,1443.7005万元,1443.7005万元,1443.7005万元,...,279.246517万元,14.456255万元,115.57556万元,26.021292万元,7.228421万元,0万元,0万元,0万元,0万元,0万元
28,2016.0,4029,604人,604人,604人,604人,604人,2395.81万元,1338.41万元,4284.34万元,...,505.29万元,18.74万元,50.72万元,8.13万元,11.98万元,0万元,0万元,0万元,0万元,0万元
29,2016.0,4030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,2017.0,4496,757人,757人,757人,757人,757人,2076.0156万元,1665.773万元,3488.5562万元,...,437.695492万元,24.735687万元,286.061718万元,13.159412万元,10.444251万元,0万元,0万元,0万元,0万元,0万元
1017,2017.0,4497,283人,283人,283人,283人,283人,1573.85万元,1573.85万元,1573.85万元,...,435.84万元,18.72万元,177.56万元,6.46万元,12.91万元,0万元,0万元,0万元,0万元,0万元
1018,2017.0,4498,442人,415人,428人,442人,428人,0.2695万元,0.2695万元,0.34677万元,...,362.85205万元,10.846942万元,181.714978万元,21.60975万元,1.018416万元,0万元,0万元,0万元,0万元,0万元
1019,2017.0,4499,164人,164人,164人,165人,164人,746196.8万元,47099.14万元,476527.1万元,...,746196.8万元,47099.14万元,476527.1万元,60690.1万元,27125万元,0万元,0万元,0万元,0万元,0万元
1020,2017.0,4500,1482人,1482人,1482人,1482人,1482人,454.7315万元,454.7315万元,454.7315万元,...,63.6624万元,2.2736万元,40.9257万元,6.1388万元,3.1831万元,0万元,0万元,0万元,0万元,0万元
1021,2017.0,4501,653人,653人,653人,653人,653人,2275.35万元,2275.35万元,2273.73万元,...,666.39万元,24.78万元,246.58万元,11.89万元,17.28万元,0万元,0万元,0万元,0万元,0万元
1022,2017.0,4502,276人,276人,276人,276人,276人,757.8919万元,633.094万元,2101.0605万元,...,160.6465万元,9.4964万元,27.1507万元,4.7827万元,3.7956万元,0万元,0万元,0万元,0万元,0万元
1023,2017.0,4503,701人,701人,700人,701人,700人,7374.64万元,9180.21万元,9529.56万元,...,1303.38万元,70.22万元,630.92万元,28.61万元,78.47万元,0万元,0万元,0万元,0万元,0万元
1024,2017.0,4504,1378人,1378人,1378人,1380人,1378人,0.228万元,0.3067万元,0.3067万元,...,922.147766万元,49.423731万元,334.135223万元,34.498719万元,28.06192万元,0万元,0万元,0万元,0万元,0万元
1025,2017.0,4505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026,2017.0,4506,159人,159人,159人,159人,159人,0.5万元,0.5万元,0.5万元,...,481万元,20万元,250万元,10万元,20万元,0万元,0万元,0万元,0万元,0万元
1027,2017.0,4507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028,2017.0,4508,201人,201人,201人,201人,201人,0.4万元,0.36万元,0.4万元,...,112.66万元,4.2万元,73.68万元,1.53万元,8.45万元,0万元,0万元,0万元,0万元,0万元
1029,2017.0,4509,1184人,1184人,1184人,1184人,1183人,2963万元,2887.8万元,8866.1万元,...,623.7万元,43.9万元,134.1万元,15.7万元,16万元,0万元,0万元,0万元,0万元,0万元
1030,2017.0,4510,9人,9人,9人,9人,9人,54.9205万元,54.9205万元,54.9305万元,...,14.8285万元,0.5492万元,5.493万元,0.4507万元,0.3844万元,0万元,0万元,0万元,0万元,0万元
1031,2017.0,4511,5人,5人,5人,5人,5人,56.7076万元,56.7076万元,56.7076万元,...,15.1798万元,0.52414万元,5.6222万元,0.39355万元,0.28111万元,0万元,0万元,0万元,0万元,0万元
1032,2017.0,4512,501人,501人,501人,501人,501人,2563.87万元,2563.87万元,2563.87万元,...,441.67万元,15.8万元,185.81万元,6.54万元,13.09万元,0万元,0万元,0万元,0万元,0万元
1033,2017.0,4513,301人,301人,301人,301人,301人,282.21万元,13.32万元,187.34万元,...,282.21万元,13.32万元,187.34万元,12.25万元,20.16万元,0万元,0万元,0万元,0万元,0万元
1034,2017.0,4514,1049人,1049人,1049人,1049人,1049人,3406.0697万元,2427.486万元,8169.4947万元,...,719.138024万元,36.095204万元,91.703547万元,16.692767万元,17.028607万元,0万元,0万元,0万元,0万元,0万元
1035,2017.0,4515,1260人,1260人,1260人,1260人,1260人,NaN,万元,万元,...,万元,万元,万元,万元,万元,万元,万元,万元,万元,万元
1036,2017.0,4516,804人,804人,804人,804人,804人,3057.79万元,2981.27万元,2981.27万元,...,852.72万元,30.76万元,323.69万元,19.97万元,22.16万元,0万元,0万元,0万元,0万元,0万元
1037,2017.0,4517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038,2017.0,4518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1039,2017.0,4519,11981人,11980人,11979人,12008人,11970人,56889.332012万元,56239.088193万元,72582.442894万元,...,15141.276969万元,560.870996万元,7358.84256万元,730.799145万元,384.989832万元,0万元,0万元,0万元,0万元,0万元
1040,2017.0,4520,391人,391人,391人,391人,391人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1041,2017.0,4521,2096人,2096人,2095人,2096人,2095人,4679.348万元,4502.703万元,15387.3883万元,...,985.64764万元,67.239902万元,96.421534万元,29.476257万元,23.384855万元,0万元,0万元,0万元,0万元,0万元
1042,2017.0,4522,301人,301人,301人,301人,301人,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1043,2017.0,4523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1044,2017.0,4524,258人,258人,258人,258人,258人,0.000000万元,0.000000万元,0.000000万元,...,105.110000万元,10.510000万元,468.250000万元,8.400000万元,21.020000万元,2102.269000万元,2102.269000万元,2102.269000万元,NaN,2102.269000万元
1045,2017.0,4525,3221人,3221人,3221人,3221人,3221人,29695.5万元,7695.77万元,30671.77万元,...,6431.33万元,114.82万元,2514.49万元,187.09万元,148.41万元,0万元,0万元,0万元,0万元,0万元

In [4]:
def get_number(cell):
    if not isinstance(cell, str):
        return cell
    _ = re.findall(r'[\d.]+',cell)
    if not _:
        return None
    return float(_[0])
df=data.applymap(get_number).set_index(["企业编号","年报年份"])
df

,,城镇职工基本养老保险人数,失业保险人数,职工基本医疗保险人数,工伤保险人数,生育保险人数,单位参加城镇职工基本养老保险缴费基数,单位参加失业保险缴费基数,单位参加职工基本医疗保险缴费基数,单位参加工伤保险缴费基数,单位参加生育保险缴费基数,参加城镇职工基本养老保险本期实际缴费金额,参加失业保险本期实际缴费金额,参加职工基本医疗保险本期实际缴费金额,参加工伤保险本期实际缴费金额,参加生育保险本期实际缴费金额,单位参加城镇职工基本养老保险累计欠缴金额,单位参加失业保险累计欠缴金额,单位参加职工基本医疗保险累计欠缴金额,单位参加工伤保险累计欠缴金额,单位参加生育保险累计欠缴金额
企业编号,年报年份,,,,,,,,,,,,,,,,,,,,
4001,2016.0,666.0,666.0,666.0,666.0,666.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4002,2016.0,288.0,373.0,373.0,373.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4003,2016.0,468.0,468.0,468.0,468.0,468.0,0.181980,0.181980,0.181980,NaN,0.181980,327.600000,18.200000,127.400000,23.700000,18.200000,0.000,0.000,0.000,0.0,0.000
4004,2016.0,1120.0,1120.0,1121.0,1120.0,1120.0,5923.000000,5923.000000,5928.000000,NaN,5923.000000,1649.000000,97.000000,666.000000,39.000000,30.000000,0.000,0.000,0.000,0.0,0.000
4005,2016.0,684.0,678.0,678.0,678.0,678.0,211.106000,211.106000,211.106000,NaN,211.106000,710.450000,37.033100,222.180300,24.686700,12.346400,0.000,0.000,0.000,0.0,0.000
4006,2016.0,777.0,777.0,777.0,777.0,777.0,2614.760000,2614.760000,2615.445000,NaN,2614.760000,723.424550,39.067200,300.773425,39.210080,13.073800,0.000,0.000,0.000,0.0,0.000
4007,2016.0,2280.0,2280.0,2281.0,2280.0,2280.0,829.683500,829.683500,830.443500,NaN,829.683500,1922.967100,116.242500,740.021500,89.497600,99.441700,0.000,0.000,0.000,0.0,0.000
4008,2016.0,236.0,236.0,236.0,236.0,236.0,0.320000,0.280000,0.280000,NaN,0.280000,284.780000,12.080000,92.100000,7.150000,6.280000,0.000,0.000,0.000,0.0,0.000
4009,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4010,2016.0,68.0,68.0,68.0,68.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4011,2016.0,138.0,138.0,138.0,138.0,138.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4012,2016.0,895.0,895.0,895.0,895.0,895.0,415.390000,415.390000,415.390000,NaN,415.390000,821.850000,45.660000,319.610000,49.310000,22.830000,0.000,0.000,0.000,0.0,0.000
4013,2016.0,497.0,497.0,497.0,497.0,497.0,4769.860000,4769.860000,4769.860000,NaN,4769.860000,953.970000,47.690000,476.990000,49.610000,47.690000,0.000,0.000,0.000,0.0,0.000
4014,2016.0,693.0,693.0,693.0,693.0,693.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4015,2016.0,83.0,83.0,83.0,83.0,83.0,0.203000,0.203000,0.675300,NaN,0.203000,4.055390,0.252735,1.146900,0.093121,0.095000,0.000,0.000,0.000,0.0,0.000
4016,2016.0,672.0,672.0,674.0,672.0,672.0,2237.080000,2237.080000,2244.250000,NaN,2237.080000,610.570000,32.400000,224.280000,55.930000,11.190000,0.000,0.000,0.000,0.0,0.000
4017,2016.0,451.0,451.0,451.0,451.0,451.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4018,2016.0,290.0,290.0,290.0,290.0,290.0,2175.512020,1885.082100,2175.512020,NaN,1885.082100,609.169810,28.295370,246.567680,7.032250,18.850870,0.000,0.000,0.000,0.0,0.000
4019,2016.0,761.0,761.0,761.0,761.0,761.0,0.417800,0.417800,0.476500,NaN,0.476500,1030.140000,38.150000,524.910000,34.810000,34.810000,0.000,0.000,0.000,0.0,0.000
4020,2016.0,1389.0,1389.0,1389.0,1389.0,1389.0,3928.340400,3227.272600,6697.615400,NaN,4168.940400,547.174500,39.028600,241.880000,16.416000,20.845000,0.000,0.000,0.000,0.0,0.000
4021,2016.0,1155.0,1155.0,1155.0,1155.0,1155.0,403.150000,403.150000,403.150000,NaN,403.150000,1227.150000,69.700000,418.240000,96.720000,32.530000,0.000,0.000,0.000,0.0,0.000
4022,2016.0,382.0,382.0,382.0,540.0,382.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4023,2016.0,187.0,188.0,188.0,188.0,188.0,899.010800,452.487000,1309.654200,NaN,904.410800,42.310000,0.088200,4.008519,0.001525,0.022610,0.000,0.000,0.000,0.0,0.000
4024,2016.0,210.0,210.0,210.0,210.0,210.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4025,2016.0,595.0,595.0,595.0,595.0,595.0,0.000000,0.000000,0.000000,NaN,0.000000,546.480000,31.520000,189.160000,28.370000,27.010000,0.000,0.000,0.000,0.0,0.000
4026,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4027,2016.0,403.0,403.0,408.0,415.0,406.0,128.730000,131.460000,169.220000,NaN,168.830000,285.000000,21.000000,116.000000,3.000000,9.000000,0.000,0.000,0.000,0.0,0.000
4028,2016.0,452.0,452.0,452.0,452.0,452.0,1443.700500,1443.700500,1443.700500,NaN,1443.700500,279.246517,14.456255,115.575560,26.021292,7.228421,0.000,0.000,0.000,0.0,0.000
4029,2016.0,604.0,604.0,604.0,604.0,604.0,2395.810000,1338.410000,4284.340000,NaN,2395.470000,505.290000,18.740000,50.720000,8.130000,11.980000,0.000,0.000,0.000,0.0,0.000
4030,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496,2017.0,757.0,757.0,757.0,757.0,757.0,2076.015600,1665.773000,3488.556200,NaN,2088.729900,437.695492,24.735687,286.061718,13.159412,10.444251,0.000,0.000,0.000,0.0,0.000
4497,2017.0,283.0,283.0,283.0,283.0,283.0,1573.850000,1573.850000,1573.850000,NaN,1573.850000,435.840000,18.720000,177.560000,6.460000,12.910000,0.000,0.000,0.000,0.0,0.000
4498,2017.0,442.0,415.0,428.0,442.0,428.0,0.269500,0.269500,0.346770,NaN,0.346770,362.852050,10.846942,181.714978,21.609750,1.018416,0.000,0.000,0.000,0.0,0.000
4499,2017.0,164.0,164.0,164.0,165.0,164.0,746196.800000,47099.140000,476527.100000,NaN,27125.000000,746196.800000,47099.140000,476527.100000,60690.100000,27125.000000,0.000,0.000,0.000,0.0,0.000
4500,2017.0,1482.0,1482.0,1482.0,1482.0,1482.0,454.731500,454.731500,454.731500,NaN,454.731500,63.662400,2.273600,40.925700,6.138800,3.183100,0.000,0.000,0.000,0.0,0.000
4501,2017.0,653.0,653.0,653.0,653.0,653.0,2275.350000,2275.350000,2273.730000,NaN,2275.350000,666.390000,24.780000,246.580000,11.890000,17.280000,0.000,0.000,0.000,0.0,0.000
4502,2017.0,276.0,276.0,276.0,276.0,276.0,757.891900,633.094000,2101.060500,NaN,759.119900,160.646500,9.496400,27.150700,4.782700,3.795600,0.000,0.000,0.000,0.0,0.000
4503,2017.0,701.0,701.0,700.0,701.0,700.0,7374.640000,9180.210000,9529.560000,NaN,9529.560000,1303.380000,70.220000,630.920000,28.610000,78.470000,0.000,0.000,0.000,0.0,0.000
4504,2017.0,1378.0,1378.0,1378.0,1380.0,1378.0,0.228000,0.306700,0.306700,NaN,0.306700,922.147766,49.423731,334.135223,34.498719,28.061920,0.000,0.000,0.000,0.0,0.000
4505,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4506,2017.0,159.0,159.0,159.0,159.0,159.0,0.500000,0.500000,0.500000,NaN,0.500000,481.000000,20.000000,250.000000,10.000000,20.000000,0.000,0.000,0.000,0.0,0.000
4507,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4508,2017.0,201.0,201.0,201.0,201.0,201.0,0.400000,0.360000,0.400000,NaN,0.400000,112.660000,4.200000,73.680000,1.530000,8.450000,0.000,0.000,0.000,0.0,0.000
4509,2017.0,1184.0,1184.0,1184.0,1184.0,1183.0,2963.000000,2887.800000,8866.100000,NaN,3129.000000,623.700000,43.900000,134.100000,15.700000,16.000000,0.000,0.000,0.000,0.0,0.000
4510,2017.0,9.0,9.0,9.0,9.0,9.0,54.920500,54.920500,54.930500,NaN,54.920500,14.828500,0.549200,5.493000,0.450700,0.384400,0.000,0.000,0.000,0.0,0.000
4511,2017.0,5.0,5.0,5.0,5.0,5.0,56.707600,56.707600,56.707600,NaN,56.707600,15.179800,0.524140,5.622200,0.393550,0.281110,0.000,0.000,0.000,0.0,0.000
4512,2017.0,501.0,501.0,501.0,501.0,501.0,2563.870000,2563.870000,2563.870000,NaN,2563.870000,441.670000,15.800000,185.810000,6.540000,13.090000,0.000,0.000,0.000,0.0,0.000
4513,2017.0,301.0,301.0,301.0,301.0,301.0,282.210000,13.320000,187.340000,NaN,20.160000,282.210000,13.320000,187.340000,12.250000,20.160000,0.000,0.000,0.000,0.0,0.000
4514,2017.0,1049.0,1049.0,1049.0,1049.0,1049.0,3406.069700,2427.486000,8169.494700,NaN,3405.719700,719.138024,36.095204,91.703547,16.692767,17.028607,0.000,0.000,0.000,0.0,0.000
4515,2017.0,1260.0,1260.0,1260.0,1260.0,1260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4516,2017.0,804.0,804.0,804.0,804.0,804.0,3057.790000,2981.270000,2981.270000,NaN,2981.270000,852.720000,30.760000,323.690000,19.970000,22.160000,0.000,0.000,0.000,0.0,0.000
4517,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4518,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4519,2017.0,11981.0,11980.0,11979.0,12008.0,11970.0,56889.332012,56239.088193,72582.442894,NaN,73348.901664,15141.276969,560.870996,7358.842560,730.799145,384.989832,0.000,0.000,0.000,0.0,0.000
4520,2017.0,391.0,391.0,391.0,391.0,391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4521,2017.0,2096.0,2096.0,2095.0,2096.0,2095.0,4679.348000,4502.703000,15387.388300,NaN,4678.283000,985.647640,67.239902,96.421534,29.476257,23.384855,0.000,0.000,0.000,0.0,0.000
4522,2017.0,301.0,301.0,301.0,301.0,301.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4523,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4524,2017.0,258.0,258.0,258.0,258.0,258.0,0.000000,0.000000,0.000000,0.0,0.000000,105.110000,10.510000,468.250000,8.400000,21.020000,2102.269,2102.269,2102.269,NaN,2102.269
4525,2017.0,3221.0,3221.0,3221.0,3221.0,3221.0,29695.500000,7695.770000,30671.770000,NaN,29680.720000,6431.330000,114.820000,2514.490000,187.090000,148.410000,0.000,0.000,0.000,0.0,0.000

In [5]:
result=df.groupby(["企业编号","年报年份"]).mean().unstack().T
result

企业编号                          4001   4002         4003    4004      4005  \
                     年报年份
城镇职工基本养老保险人数         2016.0  666.0  288.0   468.000000  1120.0  684.0000
                     2017.0  615.0  370.0   472.000000  1036.0  700.0000
失业保险人数               2016.0  666.0  373.0   468.000000  1120.0  678.0000
                     2017.0  615.0  370.0   472.000000  1036.0  700.0000
职工基本医疗保险人数           2016.0  666.0  373.0   468.000000  1121.0  678.0000
                     2017.0  615.0  370.0   472.000000  1037.0  700.0000
工伤保险人数               2016.0  666.0  373.0   468.000000  1120.0  678.0000
                     2017.0  615.0  370.0   472.000000  1036.0  700.0000
生育保险人数               2016.0  666.0  373.0   468.000000  1120.0  678.0000
                     2017.0  615.0  370.0   472.000000  1036.0  700.0000
单位参加城镇职工基本养老保险缴费基数   2016.0    NaN    NaN     0.181980  5923.0  211.1060
                     2017.0    NaN    NaN  7049.000000  5982.0  190.0500
单位参加失业保险缴费基数         2016.0    NaN    NaN     0.181980  5923.0  211.1060
                     2017.0    NaN    NaN  7049.000000  5982.0  190.0500
单位参加职工基本医疗保险缴费基数     2016.0    NaN    NaN     0.181980  5928.0  211.1060
                     2017.0    NaN    NaN  7049.000000  5987.0  190.0500
单位参加工伤保险缴费基数         2016.0    NaN    NaN          NaN     NaN       NaN
                     2017.0    NaN    NaN          NaN     NaN       NaN
单位参加生育保险缴费基数         2016.0    NaN    NaN     0.181980  5923.0  211.1060
                     2017.0    NaN    NaN  7049.000000  5982.0  190.0500
参加城镇职工基本养老保险本期实际缴费金额 2016.0    NaN    NaN   327.600000  1649.0  710.4500
                     2017.0    NaN    NaN   475.000000  1636.0  599.2100
参加失业保险本期实际缴费金额       2016.0    NaN    NaN    18.200000    97.0   37.0331
                     2017.0    NaN    NaN     1.677800    71.0   24.2100
参加职工基本医疗保险本期实际缴费金额   2016.0    NaN    NaN   127.400000   666.0  222.1803
                     2017.0    NaN    NaN    15.099700   673.0  230.0100
参加工伤保险本期实际缴费金额       2016.0    NaN    NaN    23.700000    39.0   24.6867
                     2017.0    NaN    NaN     2.181070    24.0   24.4700
参加生育保险本期实际缴费金额       2016.0    NaN    NaN    18.200000    30.0   12.3464
                     2017.0    NaN    NaN     0.167747    30.0   12.2400
单位参加城镇职工基本养老保险累计欠缴金额 2016.0    NaN    NaN     0.000000     0.0    0.0000
                     2017.0    NaN    NaN     0.000000     0.0    0.0000
单位参加失业保险累计欠缴金额       2016.0    NaN    NaN     0.000000     0.0    0.0000
                     2017.0    NaN    NaN     0.000000     0.0    0.0000
单位参加职工基本医疗保险累计欠缴金额   2016.0    NaN    NaN     0.000000     0.0    0.0000
                     2017.0    NaN    NaN     0.000000     0.0    0.0000
单位参加工伤保险累计欠缴金额       2016.0    NaN    NaN     0.000000     0.0    0.0000
                     2017.0    NaN    NaN     0.000000     0.0    0.0000
单位参加生育保险累计欠缴金额       2016.0    NaN    NaN     0.000000     0.0    0.0000
                     2017.0    NaN    NaN     0.000000     0.0    0.0000

企业编号                                4006       4007        4008  4009  4010  \
                     年报年份
城镇职工基本养老保险人数         2016.0   777.000000  2280.0000  236.000000   NaN  68.0
                     2017.0   726.000000  2190.0000  201.000000   NaN  69.0
失业保险人数               2016.0   777.000000  2280.0000  236.000000   NaN  68.0
                     2017.0   726.000000  2190.0000  201.000000   NaN  69.0
职工基本医疗保险人数           2016.0   777.000000  2281.0000  236.000000   NaN  68.0
                     2017.0   726.000000  2190.0000  201.000000   NaN  69.0
工伤保险人数               2016.0   777.000000  2280.0000  236.000000   NaN  68.0
                     2017.0   726.000000  2190.0000  201.000000   NaN  69.0
生育保险人数               2016.0   777.000000  2280.0000  236.000000   NaN  68.0
                     2017.0   726.000000  2190.0000  201.000000   NaN  69.0
单位参加城镇职工基本养老保险缴费基数   2016.0  2614.760000   829.6835    0.320000   NaN   NaN
                     2017.0  2603.190000   812.0000    0.309330   NaN   NaN
单位参加失业保险缴费基数         2016.0  2614.760000   829.6835    0.280000   NaN   NaN
                     2017.0  1743.930000   812.0000    0.309330   NaN   NaN
单位参加职工基本医疗保险缴费基数     2016.0  2615.445000   830.4435    0.280000   NaN   NaN
                     2017.0  2603.190000   812.0000    0.309330   NaN   NaN
单位参加工伤保险缴费基数         2016.0          NaN        NaN         NaN   NaN   NaN
                     2017.0          NaN        NaN         NaN   NaN   NaN
单位参加生育保险缴费基数         2016.0  2614.760000   829.6835    0.280000   NaN   NaN
                     2017.0  2603.190000     0.0000    0.309330   NaN   NaN
参加城镇职工基本养老保险本期实际缴费金额 2016.0   723.424550  1922.9671  284.780000   NaN   NaN
                     2017.0   494.610000   154.0000   17.025462   NaN   NaN
参加失业保险本期实际缴费金额       2016.0    39.067200   116.2425   12.080000   NaN   NaN
                     2017.0    13.020000     0.0020    0.630514   NaN   NaN
参加职工基本医疗保险本期实际缴费金额   2016.0   300.773425   740.0215   92.100000   NaN   NaN
                     2017.0   234.290000    65.0000    6.305734   NaN   NaN
参加工伤保险本期实际缴费金额       2016.0    39.210080    89.4976    7.150000   NaN   NaN
                     2017.0    36.440000     7.3000    0.529608   NaN   NaN
参加生育保险本期实际缴费金额       2016.0    13.073800    99.4417    6.280000   NaN   NaN
                     2017.0    13.020000     0.0000    0.441340   NaN   NaN
单位参加城镇职工基本养老保险累计欠缴金额 2016.0     0.000000     0.0000    0.000000   NaN   NaN
                     2017.0     0.000000     0.0000    0.000000   NaN   NaN
单位参加失业保险累计欠缴金额       2016.0     0.000000     0.0000    0.000000   NaN   NaN
                     2017.0     0.000000     0.0000    0.000000   NaN   NaN
单位参加职工基本医疗保险累计欠缴金额   2016.0     0.000000     0.0000    0.000000   NaN   NaN
                     2017.0     0.000000     0.0000    0.000000   NaN   NaN
单位参加工伤保险累计欠缴金额       2016.0     0.000000     0.0000    0.000000   NaN   NaN
                     2017.0     0.000000     0.0000    0.000000   NaN   NaN
单位参加生育保险累计欠缴金额       2016.0     0.000000     0.0000    0.000000   NaN   NaN
                     2017.0     0.000000     0.0000    0.000000   NaN   NaN

企业编号                           ...            4516  4517  4518          4519  \
                     年报年份      ...
城镇职工基本养老保险人数         2016.0    ...      477.000000   NaN   NaN   9718.000000
                     2017.0    ...      804.000000   NaN   NaN  11981.000000
失业保险人数               2016.0    ...      477.000000   NaN   NaN   9718.000000
                     2017.0    ...      804.000000   NaN   NaN  11980.000000
职工基本医疗保险人数           2016.0    ...      477.000000   NaN   NaN   9720.000000
                     2017.0    ...      804.000000   NaN   NaN  11979.000000
工伤保险人数               2016.0    ...      477.000000   NaN   NaN   9751.000000
                     2017.0    ...      804.000000   NaN   NaN  12008.000000
生育保险人数               2016.0    ...      477.000000   NaN   NaN   9720.000000
                     2017.0    ...      804.000000   NaN   NaN  11970.000000
单位参加城镇职工基本养老保险缴费基数   2016.0    ...     1660.325760   NaN   NaN  30973.570000
                     2017.0    ...     3057.790000   NaN   NaN  56889.332012
单位参加失业保险缴费基数         2016.0    ...     1527.211600   NaN   NaN  30973.570000
                     2017.0    ...     2981.270000   NaN   NaN  56239.088193
单位参加职工基本医疗保险缴费基数     2016.0    ...     1527.211600   NaN   NaN  40539.730000
                     2017.0    ...     2981.270000   NaN   NaN  72582.442894
单位参加工伤保险缴费基数         2016.0    ...             NaN   NaN   NaN           NaN
                     2017.0    ...             NaN   NaN   NaN           NaN
单位参加生育保险缴费基数         2016.0    ...     1527.211600   NaN   NaN  40539.730000
                     2017.0    ...     2981.270000   NaN   NaN  73348.901664
参加城镇职工基本养老保险本期实际缴费金额 2016.0    ...      355.033319   NaN   NaN   5584.150000
                     2017.0    ...      852.720000   NaN   NaN  15141.276969
参加失业保险本期实际缴费金额       2016.0    ...       14.893487   NaN   NaN    334.140000
                     2017.0    ...       30.760000   NaN   NaN    560.870996
参加职工基本医疗保险本期实际缴费金额   2016.0    ...      135.866380   NaN   NaN   3191.420000
                     2017.0    ...      323.690000   NaN   NaN   7358.842560
参加工伤保险本期实际缴费金额       2016.0    ...        8.937726   NaN   NaN    386.750000
                     2017.0    ...       19.970000   NaN   NaN    730.799145
参加生育保险本期实际缴费金额       2016.0    ...       11.916992   NaN   NaN    209.290000
                     2017.0    ...       22.160000   NaN   NaN    384.989832
单位参加城镇职工基本养老保险累计欠缴金额 2016.0    ...        0.000000   NaN   NaN      0.000000
                     2017.0    ...        0.000000   NaN   NaN      0.000000
单位参加失业保险累计欠缴金额       2016.0    ...        0.000000   NaN   NaN      0.000000
                     2017.0    ...        0.000000   NaN   NaN      0.000000
单位参加职工基本医疗保险累计欠缴金额   2016.0    ...        0.000000   NaN   NaN      0.000000
                     2017.0    ...        0.000000   NaN   NaN      0.000000
单位参加工伤保险累计欠缴金额       2016.0    ...        0.000000   NaN   NaN      0.000000
                     2017.0    ...        0.000000   NaN   NaN      0.000000
单位参加生育保险累计欠缴金额       2016.0    ...        0.000000   NaN   NaN      0.000000
                     2017.0    ...        0.000000   NaN   NaN      0.000000

企业编号                          4520          4521   4522   4523      4524  \
                     年报年份
城镇职工基本养老保险人数         2016.0  254.0   1543.000000  238.0  667.0  2062.000
                     2017.0  391.0   2096.000000  301.0    NaN   258.000
失业保险人数               2016.0  254.0   1543.000000  238.0  667.0  2062.000
                     2017.0  391.0   2096.000000  301.0    NaN   258.000
职工基本医疗保险人数           2016.0  254.0   1543.000000  238.0  667.0  2062.000
                     2017.0  391.0   2095.000000  301.0    NaN   258.000
工伤保险人数               2016.0  254.0   1543.000000  238.0  667.0  2062.000
                     2017.0  391.0   2096.000000  301.0    NaN   258.000
生育保险人数               2016.0  254.0   1543.000000  238.0  667.0  2062.000
                     2017.0  391.0   2095.000000  301.0    NaN   258.000
单位参加城镇职工基本养老保险缴费基数   2016.0    NaN   3258.370000    NaN    0.0     0.000
                     2017.0    NaN   4679.348000    NaN    NaN     0.000
单位参加失业保险缴费基数         2016.0    NaN   3897.600000    NaN    0.0     0.000
                     2017.0    NaN   4502.703000    NaN    NaN     0.000
单位参加职工基本医疗保险缴费基数     2016.0    NaN  12309.010000    NaN    0.0     0.000
                     2017.0    NaN  15387.388300    NaN    NaN     0.000
单位参加工伤保险缴费基数         2016.0    NaN           NaN    NaN    NaN     0.000
                     2017.0    NaN           NaN    NaN    NaN     0.000
单位参加生育保险缴费基数         2016.0    NaN   3979.060000    NaN    0.0     0.000
                     2017.0    NaN   4678.283000    NaN    NaN     0.000
参加城镇职工基本养老保险本期实际缴费金额 2016.0    NaN    684.630000    NaN    0.0    71.370
                     2017.0    NaN    985.647640    NaN    NaN   105.110
参加失业保险本期实际缴费金额       2016.0    NaN     54.280000    NaN    0.0     7.140
                     2017.0    NaN     67.239902    NaN    NaN    10.510
参加职工基本医疗保险本期实际缴费金额   2016.0    NaN    759.990000    NaN    0.0   328.280
                     2017.0    NaN     96.421534    NaN    NaN   468.250
参加工伤保险本期实际缴费金额       2016.0    NaN     19.460000    NaN    0.0     5.710
                     2017.0    NaN     29.476257    NaN    NaN     8.400
参加生育保险本期实际缴费金额       2016.0    NaN     19.900000    NaN    0.0    14.270
                     2017.0    NaN     23.384855    NaN    NaN    21.020
单位参加城镇职工基本养老保险累计欠缴金额 2016.0    NaN      0.000000    NaN    0.0  1427.330
                     2017.0    NaN      0.000000    NaN    NaN  2102.269
单位参加失业保险累计欠缴金额       2016.0    NaN      0.000000    NaN    0.0  1427.330
                     2017.0    NaN      0.000000    NaN    NaN  2102.269
单位参加职工基本医疗保险累计欠缴金额   2016.0    NaN      0.000000    NaN    0.0  1427.330
                     2017.0    NaN      0.000000    NaN    NaN  2102.269
单位参加工伤保险累计欠缴金额       2016.0    NaN      0.000000    NaN    0.0       NaN
                     2017.0    NaN      0.000000    NaN    NaN       NaN
单位参加生育保险累计欠缴金额       2016.0    NaN      0.000000    NaN    0.0  1427.330
                     2017.0    NaN      0.000000    NaN    NaN  2102.269

企业编号                             4525
                     年报年份
城镇职工基本养老保险人数         2016.0   3072.00
                     2017.0   3221.00
失业保险人数               2016.0   3072.00
                     2017.0   3221.00
职工基本医疗保险人数           2016.0   3072.00
                     2017.0   3221.00
工伤保险人数               2016.0   3072.00
                     2017.0   3221.00
生育保险人数               2016.0   3072.00
                     2017.0   3221.00
单位参加城镇职工基本养老保险缴费基数   2016.0  28493.45
                     2017.0  29695.50
单位参加失业保险缴费基数         2016.0   7687.41
                     2017.0   7695.77
单位参加职工基本医疗保险缴费基数     2016.0  29625.12
                     2017.0  30671.77
单位参加工伤保险缴费基数         2016.0       NaN
                     2017.0       NaN
单位参加生育保险缴费基数         2016.0  28681.59
                     2017.0  29680.72
参加城镇职工基本养老保险本期实际缴费金额 2016.0   6171.31
                     2017.0   6431.33
参加失业保险本期实际缴费金额       2016.0    107.62
                     2017.0    114.82
参加职工基本医疗保险本期实际缴费金额   2016.0   2427.85
                     2017.0   2514.49
参加工伤保险本期实际缴费金额       2016.0    112.91
                     2017.0    187.09
参加生育保险本期实际缴费金额       2016.0    143.41
                     2017.0    148.41
单位参加城镇职工基本养老保险累计欠缴金额 2016.0      0.00
                     2017.0      0.00
单位参加失业保险累计欠缴金额       2016.0      0.00
                     2017.0      0.00
单位参加职工基本医疗保险累计欠缴金额   2016.0      0.00
                     2017.0      0.00
单位参加工伤保险累计欠缴金额       2016.0      0.00
                     2017.0      0.00
单位参加生育保险累计欠缴金额       2016.0      0.00
                     2017.0      0.00

[40 rows x 523 columns]

In [6]:
result.to_pickle('年报-社保信息-testing.pickle')