In [125]:
import pandas as pd
import re
import numpy as np
data=pd.read_excel("赛题1数据材料\赛题1数据集\年报-股东（发起人）及出资信息.xlsx")
data

,企业编号,股东类型,股东所占比例,认缴出资信息,实缴出资信息,年报年份
0,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：3945926.64万人民币\n认缴出资日期：20...,实缴出资方式：货币\n实缴出资额（万元）：3945926.64万人民币\n实缴出资日期：20...,2014.0
1,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：3945926.64万人民币\n认缴出资日期：20...,实缴出资方式：货币\n实缴出资额（万元）：3945926.64万人民币\n实缴出资日期：20...,2013.0
2,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：3945926.645375万人民币\n认缴出资日...,实缴出资方式：货币\n实缴出资额（万元）：3945926.645375万人民币\n实缴出资日...,2015.0
3,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：3945926.645375万人民币\n认缴出资日...,实缴出资方式：货币\n实缴出资额（万元）：3945926.645375万人民币\n实缴出资日...,2016.0
4,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：1114395.6096万人民币\n认缴出资日期：...,实缴出资方式：股权\n实缴出资额（万元）：1114395.6096万人民币\n实缴出资日期：...,2016.0
5,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：336000万人民币\n认缴出资日期：2016-0...,实缴出资方式：股权\n实缴出资额（万元）：336000万人民币\n实缴出资日期：2016-0...,2016.0
6,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：84000万人民币\n认缴出资日期：2016-03-18,实缴出资方式：股权\n实缴出资额（万元）：84000万人民币\n实缴出资日期：2016-03-18,2016.0
7,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：22402.1952万人民币\n认缴出资日期：20...,实缴出资方式：股权\n实缴出资额（万元）：22402.1952万人民币\n实缴出资日期：20...,2016.0
8,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：22398.9024万人民币\n认缴出资日期：20...,实缴出资方式：股权\n实缴出资额（万元）：22398.9024万人民币\n实缴出资日期：20...,2016.0
9,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：11201.0976万人民币\n认缴出资日期：20...,实缴出资方式：股权\n实缴出资额（万元）：11201.0976万人民币\n实缴出资日期：20...,2016.0
10,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：11201.0976万人民币\n认缴出资日期：20...,实缴出资方式：股权\n实缴出资额（万元）：11201.0976万人民币\n实缴出资日期：20...,2016.0
11,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：11201.0976万人民币\n认缴出资日期：20...,实缴出资方式：股权\n实缴出资额（万元）：11201.0976万人民币\n实缴出资日期：20...,2016.0
12,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：8959.9776万人民币\n认缴出资日期：201...,实缴出资方式：股权\n实缴出资额（万元）：8959.9776万人民币\n实缴出资日期：201...,2016.0
13,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：6719.4624万人民币\n认缴出资日期：201...,实缴出资方式：股权\n实缴出资额（万元）：6719.4624万人民币\n实缴出资日期：201...,2016.0
14,1001,NaN,NaN,认缴出资方式：股权\n认缴出资额（万元）：6719.4624万人民币\n认缴出资日期：201...,实缴出资方式：股权\n实缴出资额（万元）：6719.4624万人民币\n实缴出资日期：201...,2016.0
15,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：633132.2671万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：633132.2671万人民币\n实缴出资日期：2...,2017.0
16,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：533489.2824万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：533489.2824万人民币\n实缴出资日期：2...,2017.0
17,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：277943.7274万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：277943.7274万人民币\n实缴出资日期：2...,2017.0
18,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：176323.2325万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：176323.2325万人民币\n实缴出资日期：2...,2017.0
19,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：139557.1025万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：139557.1025万人民币\n实缴出资日期：2...,2017.0
20,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：127042.8648万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：127042.8648万人民币\n实缴出资日期：2...,2017.0
21,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：121697.9451万人民币\n认缴出资日期：2...,实缴出资方式：货币\n实缴出资额（万元）：121697.9451万人民币\n实缴出资日期：2...,2017.0
22,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：94556.899万人民币\n认缴出资日期：201...,实缴出资方式：货币\n实缴出资额（万元）：94556.899万人民币\n实缴出资日期：201...,2017.0
23,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：88613.134万人民币\n认缴出资日期：201...,实缴出资方式：货币\n实缴出资额（万元）：88613.134万人民币\n实缴出资日期：201...,2017.0
24,1001,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：39852.1409万人民币\n认缴出资日期：20...,实缴出资方式：货币\n实缴出资额（万元）：39852.1409万人民币\n实缴出资日期：20...,2017.0
25,1002,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：43740.85万人民币\n认缴出资日期：2007...,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...,2013.0
26,1002,NaN,NaN,认缴出资方式：货币、实物、土地使用权\n认缴出资额（万元）：71259.15万人民币\n认缴...,实缴出资方式：货币、实物、土地使用权\n实缴出资额（万元）：71259.15万人民币\n实缴...,2013.0
27,1002,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：43740.85万人民币\n认缴出资日期：2007...,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...,2014.0
28,1002,NaN,NaN,认缴出资方式：货币、实物、土地使用权\n认缴出资额（万元）：71259.15万人民币\n认缴...,实缴出资方式：货币、实物、土地使用权\n实缴出资额（万元）：71259.15万人民币\n实缴...,2014.0
29,1002,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：43740.85万人民币\n认缴出资日期：2007...,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...,2015.0
...,...,...,...,...,...,...
105874,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：250万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2015.0
105875,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：500万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2015.0
105876,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：1787万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2014.0
105877,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：250万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2014.0
105878,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：60万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2014.0
105879,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：500万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2014.0
105880,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：375万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2014.0
105881,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：10万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2014.0
105882,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：18万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2014.0
105883,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：10万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2013.0
105884,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：250万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2013.0
105885,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：375万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2013.0
105886,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：18万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2013.0
105887,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：60万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2013.0
105888,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：500万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2013.0
105889,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：1787万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2013.0
105890,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：500万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2016.0
105891,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：60万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2016.0
105892,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：18万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2016.0
105893,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：1787万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2016.0
105894,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：10万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2016.0
105895,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：250万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2016.0
105896,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：375万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2016.0
105897,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：1787万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2017.0
105898,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：250万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2017.0
105899,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：375万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2017.0
105900,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：500万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2017.0
105901,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：60万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2017.0
105902,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：18万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2017.0
105903,4000,NaN,NaN,认缴出资方式：货币\n认缴出资额（万元）：10万人民币\n认缴出资日期：2001-08-15,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2017.0

In [126]:
str1="认缴出资方式：货币\n认缴出资额（万元）：3945926万人民币\n认缴出资日期：20.."
re.search('\d+', str1, flags=0)

In [127]:
for i in range(len(data)):
    if (type(data.iloc[i,3])==np.float):
        continue    
    data.iloc[i,3]=float(re.search('\d+', data.iloc[i,3], flags=0).group())
data

,企业编号,股东类型,股东所占比例,认缴出资信息,实缴出资信息,年报年份
0,1001,NaN,NaN,3.94593e+06,实缴出资方式：货币\n实缴出资额（万元）：3945926.64万人民币\n实缴出资日期：20...,2014.0
1,1001,NaN,NaN,3.94593e+06,实缴出资方式：货币\n实缴出资额（万元）：3945926.64万人民币\n实缴出资日期：20...,2013.0
2,1001,NaN,NaN,3.94593e+06,实缴出资方式：货币\n实缴出资额（万元）：3945926.645375万人民币\n实缴出资日...,2015.0
3,1001,NaN,NaN,3.94593e+06,实缴出资方式：货币\n实缴出资额（万元）：3945926.645375万人民币\n实缴出资日...,2016.0
4,1001,NaN,NaN,1.1144e+06,实缴出资方式：股权\n实缴出资额（万元）：1114395.6096万人民币\n实缴出资日期：...,2016.0
5,1001,NaN,NaN,336000,实缴出资方式：股权\n实缴出资额（万元）：336000万人民币\n实缴出资日期：2016-0...,2016.0
6,1001,NaN,NaN,84000,实缴出资方式：股权\n实缴出资额（万元）：84000万人民币\n实缴出资日期：2016-03-18,2016.0
7,1001,NaN,NaN,22402,实缴出资方式：股权\n实缴出资额（万元）：22402.1952万人民币\n实缴出资日期：20...,2016.0
8,1001,NaN,NaN,22398,实缴出资方式：股权\n实缴出资额（万元）：22398.9024万人民币\n实缴出资日期：20...,2016.0
9,1001,NaN,NaN,11201,实缴出资方式：股权\n实缴出资额（万元）：11201.0976万人民币\n实缴出资日期：20...,2016.0
10,1001,NaN,NaN,11201,实缴出资方式：股权\n实缴出资额（万元）：11201.0976万人民币\n实缴出资日期：20...,2016.0
11,1001,NaN,NaN,11201,实缴出资方式：股权\n实缴出资额（万元）：11201.0976万人民币\n实缴出资日期：20...,2016.0
12,1001,NaN,NaN,8959,实缴出资方式：股权\n实缴出资额（万元）：8959.9776万人民币\n实缴出资日期：201...,2016.0
13,1001,NaN,NaN,6719,实缴出资方式：股权\n实缴出资额（万元）：6719.4624万人民币\n实缴出资日期：201...,2016.0
14,1001,NaN,NaN,6719,实缴出资方式：股权\n实缴出资额（万元）：6719.4624万人民币\n实缴出资日期：201...,2016.0
15,1001,NaN,NaN,633132,实缴出资方式：货币\n实缴出资额（万元）：633132.2671万人民币\n实缴出资日期：2...,2017.0
16,1001,NaN,NaN,533489,实缴出资方式：货币\n实缴出资额（万元）：533489.2824万人民币\n实缴出资日期：2...,2017.0
17,1001,NaN,NaN,277943,实缴出资方式：货币\n实缴出资额（万元）：277943.7274万人民币\n实缴出资日期：2...,2017.0
18,1001,NaN,NaN,176323,实缴出资方式：货币\n实缴出资额（万元）：176323.2325万人民币\n实缴出资日期：2...,2017.0
19,1001,NaN,NaN,139557,实缴出资方式：货币\n实缴出资额（万元）：139557.1025万人民币\n实缴出资日期：2...,2017.0
20,1001,NaN,NaN,127042,实缴出资方式：货币\n实缴出资额（万元）：127042.8648万人民币\n实缴出资日期：2...,2017.0
21,1001,NaN,NaN,121697,实缴出资方式：货币\n实缴出资额（万元）：121697.9451万人民币\n实缴出资日期：2...,2017.0
22,1001,NaN,NaN,94556,实缴出资方式：货币\n实缴出资额（万元）：94556.899万人民币\n实缴出资日期：201...,2017.0
23,1001,NaN,NaN,88613,实缴出资方式：货币\n实缴出资额（万元）：88613.134万人民币\n实缴出资日期：201...,2017.0
24,1001,NaN,NaN,39852,实缴出资方式：货币\n实缴出资额（万元）：39852.1409万人民币\n实缴出资日期：20...,2017.0
25,1002,NaN,NaN,43740,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...,2013.0
26,1002,NaN,NaN,71259,实缴出资方式：货币、实物、土地使用权\n实缴出资额（万元）：71259.15万人民币\n实缴...,2013.0
27,1002,NaN,NaN,43740,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...,2014.0
28,1002,NaN,NaN,71259,实缴出资方式：货币、实物、土地使用权\n实缴出资额（万元）：71259.15万人民币\n实缴...,2014.0
29,1002,NaN,NaN,43740,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...,2015.0
...,...,...,...,...,...,...
105874,4000,NaN,NaN,250,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2015.0
105875,4000,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2015.0
105876,4000,NaN,NaN,1787,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2014.0
105877,4000,NaN,NaN,250,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2014.0
105878,4000,NaN,NaN,60,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2014.0
105879,4000,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2014.0
105880,4000,NaN,NaN,375,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2014.0
105881,4000,NaN,NaN,10,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2014.0
105882,4000,NaN,NaN,18,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2014.0
105883,4000,NaN,NaN,10,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2013.0
105884,4000,NaN,NaN,250,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2013.0
105885,4000,NaN,NaN,375,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2013.0
105886,4000,NaN,NaN,18,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2013.0
105887,4000,NaN,NaN,60,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2013.0
105888,4000,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2013.0
105889,4000,NaN,NaN,1787,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2013.0
105890,4000,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2016.0
105891,4000,NaN,NaN,60,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2016.0
105892,4000,NaN,NaN,18,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2016.0
105893,4000,NaN,NaN,1787,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2016.0
105894,4000,NaN,NaN,10,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2016.0
105895,4000,NaN,NaN,250,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2016.0
105896,4000,NaN,NaN,375,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2016.0
105897,4000,NaN,NaN,1787,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15,2017.0
105898,4000,NaN,NaN,250,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15,2017.0
105899,4000,NaN,NaN,375,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15,2017.0
105900,4000,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15,2017.0
105901,4000,NaN,NaN,60,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15,2017.0
105902,4000,NaN,NaN,18,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15,2017.0
105903,4000,NaN,NaN,10,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15,2017.0

In [128]:
data=data.set_index("年报年份").loc[[2013.0,2014.0,2015.0,2016.0,2017.0],:].reset_index()
data

,年报年份,企业编号,股东类型,股东所占比例,认缴出资信息,实缴出资信息
0,2013.0,1001,NaN,NaN,3.94593e+06,实缴出资方式：货币\n实缴出资额（万元）：3945926.64万人民币\n实缴出资日期：20...
1,2013.0,1002,NaN,NaN,43740,实缴出资方式：货币\n实缴出资额（万元）：43740.85万人民币\n实缴出资日期：2007...
2,2013.0,1002,NaN,NaN,71259,实缴出资方式：货币、实物、土地使用权\n实缴出资额（万元）：71259.15万人民币\n实缴...
3,2013.0,1003,NaN,NaN,120200,实缴出资方式：货币\n实缴出资额（万元）：120200万元\n实缴出资日期：2006-10-13
4,2013.0,1004,NaN,NaN,80728,实缴出资方式：\n实缴出资额（万元）：80728.2534万元\n实缴出资日期：2006-1...
5,2013.0,1005,股权,NaN,130929,实缴出资方式：股权\n实缴出资额（万元）：130929.1709万元\n实缴出资日期：200...
6,2013.0,1005,股权,NaN,89070,实缴出资方式：股权\n实缴出资额（万元）：89070.8291万元\n实缴出资日期：2013...
7,2013.0,1006,NaN,NaN,102617,实缴出资方式：其他\n实缴出资额（万元）：102617.7895万人民币\n实缴出资日期：1...
8,2013.0,1006,NaN,NaN,90078,实缴出资方式：货币\n实缴出资额（万元）：90078.0553万人民币\n实缴出资日期：19...
9,2013.0,1007,NaN,NaN,642364,实缴出资方式：货币\n实缴出资额（万元）：642364.3659万\n实缴出资日期：2013...
10,2013.0,1007,NaN,NaN,157894,实缴出资方式：货币\n实缴出资额（万元）：157894.7368万\n实缴出资日期：2013...
11,2013.0,1008,NaN,NaN,333,实缴出资方式：货币\n实缴出资额（万元）：333.3333万人民币\n实缴出资日期：2007...
12,2013.0,1008,NaN,NaN,41650,实缴出资方式：货币\n实缴出资额（万元）：41650万人民币\n实缴出资日期：2006-12-31
13,2013.0,1008,NaN,NaN,30150,实缴出资方式：货币\n实缴出资额（万元）：30150万人民币\n实缴出资日期：2006-12-31
14,2013.0,1008,NaN,NaN,60300,实缴出资方式：货币\n实缴出资额（万元）：60300万人民币\n实缴出资日期：2006-12-31
15,2013.0,1008,NaN,NaN,506666,实缴出资方式：货币\n实缴出资额（万元）：506666.2118万人民币\n实缴出资日期：2...
16,2013.0,1008,NaN,NaN,38861,实缴出资方式：货币\n实缴出资额（万元）：38861.9936万人民币\n实缴出资日期：20...
17,2013.0,1008,NaN,NaN,6004,实缴出资方式：货币\n实缴出资额（万元）：6004.7426万人民币\n实缴出资日期：201...
18,2013.0,1008,NaN,NaN,37446,实缴出资方式：货币\n实缴出资额（万元）：37446.75万人民币\n实缴出资日期：2013...
19,2013.0,1009,NaN,NaN,116559,实缴出资方式：货币\n实缴出资额（万元）：116559.98万人民币\n实缴出资日期：199...
20,2013.0,1009,NaN,NaN,49301,实缴出资方式：货币\n实缴出资额（万元）：49301.02万人民币\n实缴出资日期：1996...
21,2013.0,1010,NaN,NaN,30000,实缴出资方式：货币\n实缴出资额（万元）：30000万人民币\n实缴出资日期：1996-03-13
22,2013.0,1010,NaN,NaN,40000,实缴出资方式：货币\n实缴出资额（万元）：40000万人民币\n实缴出资日期：1996-03-13
23,2013.0,1010,NaN,NaN,9500,实缴出资方式：货币\n实缴出资额（万元）：9500万人民币\n实缴出资日期：1996-03-13
24,2013.0,1010,NaN,NaN,1000,实缴出资方式：货币\n实缴出资额（万元）：1000万人民币\n实缴出资日期：1996-03-13
25,2013.0,1010,NaN,NaN,1000,实缴出资方式：货币\n实缴出资额（万元）：1000万人民币\n实缴出资日期：1996-03-13
26,2013.0,1010,NaN,NaN,35000,实缴出资方式：货币\n实缴出资额（万元）：35000万人民币\n实缴出资日期：1996-03-13
27,2013.0,1010,NaN,NaN,10000,实缴出资方式：货币\n实缴出资额（万元）：10000万人民币\n实缴出资日期：1996-03-13
28,2013.0,1010,NaN,NaN,15000,实缴出资方式：货币\n实缴出资额（万元）：15000万人民币\n实缴出资日期：1996-03-13
29,2013.0,1010,NaN,NaN,1000,实缴出资方式：货币\n实缴出资额（万元）：1000万人民币\n实缴出资日期：1996-03-13
...,...,...,...,...,...,...
105830,2017.0,3993,NaN,NaN,46692,实缴出资方式：货币\n实缴出资额（万元）：46692.8837万人民币\n实缴出资日期：20...
105831,2017.0,3993,NaN,NaN,1088,实缴出资方式：货币\n实缴出资额（万元）：1088.3417万人民币\n实缴出资日期：201...
105832,2017.0,3994,NaN,NaN,300,实缴出资方式：货币\n实缴出资额（万元）：300万元\n实缴出资日期：1999-08-01
105833,2017.0,3994,NaN,NaN,700,实缴出资方式：货币\n实缴出资额（万元）：700万元\n实缴出资日期：1999-08-01
105834,2017.0,3994,NaN,NaN,300,实缴出资方式：货币\n实缴出资额（万元）：300万元\n实缴出资日期：1999-08-01
105835,2017.0,3994,NaN,NaN,1600,实缴出资方式：货币\n实缴出资额（万元）：1600万元\n实缴出资日期：1999-08-01
105836,2017.0,3994,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万元\n实缴出资日期：1999-08-01
105837,2017.0,3994,NaN,NaN,650,实缴出资方式：货币\n实缴出资额（万元）：650万元\n实缴出资日期：1999-08-01
105838,2017.0,3994,NaN,NaN,450,实缴出资方式：货币\n实缴出资额（万元）：450万元\n实缴出资日期：1999-08-01
105839,2017.0,3995,NaN,NaN,26330,实缴出资方式：货币\n实缴出资额（万元）：26330.85万人民币\n实缴出资日期：2016...
105840,2017.0,3995,NaN,NaN,12203,实缴出资方式：货币\n实缴出资额（万元）：12203.1万人民币\n实缴出资日期：2016-...
105841,2017.0,3995,NaN,NaN,9956,实缴出资方式：货币\n实缴出资额（万元）：9956.7万人民币\n实缴出资日期：2016-0...
105842,2017.0,3995,NaN,NaN,10009,实缴出资方式：货币\n实缴出资额（万元）：10009.35万人民币\n实缴出资日期：2016...
105843,2017.0,3996,NaN,NaN,5300,实缴出资方式：货币\n实缴出资额（万元）：21759.434万人民币\n实缴出资日期：201...
105844,2017.0,3996,NaN,NaN,7597,实缴出资方式：货币\n实缴出资额（万元）：42750.266万人民币\n实缴出资日期：201...
105845,2017.0,3998,NaN,NaN,6208,实缴出资方式：货币\n实缴出资额（万元）：6208.4881万元人民币\n实缴出资日期：20...
105846,2017.0,3998,NaN,NaN,3586,实缴出资方式：货币\n实缴出资额（万元）：3586.1566万元人民币\n实缴出资日期：20...
105847,2017.0,3998,NaN,NaN,3269,实缴出资方式：货币\n实缴出资额（万元）：3269.772万元人民币\n实缴出资日期：200...
105848,2017.0,3998,NaN,NaN,3021,实缴出资方式：股权\n实缴出资额（万元）：3021.9256万元人民币\n实缴出资日期：20...
105849,2017.0,3998,NaN,NaN,13125,实缴出资方式：货币\n实缴出资额（万元）：13125.8893万元人民币\n实缴出资日期：2...
105850,2017.0,3999,NaN,NaN,21276,实缴出资方式：股权\n实缴出资额（万元）：21276.62万人民币\n实缴出资日期：2017...
105851,2017.0,3999,NaN,NaN,17252,实缴出资方式：股权\n实缴出资额（万元）：17252.76万人民币\n实缴出资日期：2018...
105852,2017.0,3999,NaN,NaN,9892,实缴出资方式：股权\n实缴出资额（万元）：9892.61万人民币\n实缴出资日期：2017-...
105853,2017.0,4000,NaN,NaN,1787,实缴出资方式：货币\n实缴出资额（万元）：1787万人民币\n实缴出资日期：2001-08-15
105854,2017.0,4000,NaN,NaN,250,实缴出资方式：货币\n实缴出资额（万元）：250万人民币\n实缴出资日期：2001-08-15
105855,2017.0,4000,NaN,NaN,375,实缴出资方式：货币\n实缴出资额（万元）：375万人民币\n实缴出资日期：2001-08-15
105856,2017.0,4000,NaN,NaN,500,实缴出资方式：货币\n实缴出资额（万元）：500万人民币\n实缴出资日期：2001-08-15
105857,2017.0,4000,NaN,NaN,60,实缴出资方式：货币\n实缴出资额（万元）：60万人民币\n实缴出资日期：2001-08-15
105858,2017.0,4000,NaN,NaN,18,实缴出资方式：货币\n实缴出资额（万元）：18万人民币\n实缴出资日期：2001-08-15
105859,2017.0,4000,NaN,NaN,10,实缴出资方式：货币\n实缴出资额（万元）：10万人民币\n实缴出资日期：2001-08-15

In [129]:
df=data.iloc[:,[0,1,4]]
df

          年报年份  企业编号       认缴出资信息
0       2013.0  1001  3.94593e+06
1       2013.0  1002        43740
2       2013.0  1002        71259
3       2013.0  1003       120200
4       2013.0  1004        80728
5       2013.0  1005       130929
6       2013.0  1005        89070
7       2013.0  1006       102617
8       2013.0  1006        90078
9       2013.0  1007       642364
10      2013.0  1007       157894
11      2013.0  1008          333
12      2013.0  1008        41650
13      2013.0  1008        30150
14      2013.0  1008        60300
15      2013.0  1008       506666
16      2013.0  1008        38861
17      2013.0  1008         6004
18      2013.0  1008        37446
19      2013.0  1009       116559
20      2013.0  1009        49301
21      2013.0  1010        30000
22      2013.0  1010        40000
23      2013.0  1010         9500
24      2013.0  1010         1000
25      2013.0  1010         1000
26      2013.0  1010        35000
27      2013.0  1010        10000
28      2013.0  1010        15000
29      2013.0  1010         1000
...        ...   ...          ...
105830  2017.0  3993        46692
105831  2017.0  3993         1088
105832  2017.0  3994          300
105833  2017.0  3994          700
105834  2017.0  3994          300
105835  2017.0  3994         1600
105836  2017.0  3994          500
105837  2017.0  3994          650
105838  2017.0  3994          450
105839  2017.0  3995        26330
105840  2017.0  3995        12203
105841  2017.0  3995         9956
105842  2017.0  3995        10009
105843  2017.0  3996         5300
105844  2017.0  3996         7597
105845  2017.0  3998         6208
105846  2017.0  3998         3586
105847  2017.0  3998         3269
105848  2017.0  3998         3021
105849  2017.0  3998        13125
105850  2017.0  3999        21276
105851  2017.0  3999        17252
105852  2017.0  3999         9892
105853  2017.0  4000         1787
105854  2017.0  4000          250
105855  2017.0  4000          375
105856  2017.0  4000          500
105857  2017.0  4000           60
105858  2017.0  4000           18
105859  2017.0  4000           10

[105860 rows x 3 columns]

In [133]:
result_13=df.groupby(["企业编号","年报年份"]).sum().unstack().T
result_13

企业编号                1001      1002      1003      1004      1005      1006  \
       年报年份
认缴出资信息 2013.0  3945926.0  114999.0  120200.0   80728.0  219999.0  192695.0
       2014.0  3945926.0  114999.0  120200.0   80728.0  219999.0  192695.0
       2015.0  3945926.0  114999.0  120200.0  100728.0  241030.0  192695.0
       2016.0  5581121.0  114999.0  120200.0  100728.0  241030.0  192695.0
       2017.0  2232204.0  206931.0  120200.0  100728.0  482061.0  192695.0

企业编号                1007          1008      1009      1010   ...       3991  \
       年报年份                                                  ...
认缴出资信息 2013.0   800258.0  7.214100e+05  165860.0  346084.0   ...     5593.0
       2014.0  1600517.0  7.210100e+05  165860.0  346084.0   ...     5593.0
       2015.0  3256073.0  7.216330e+05  165861.0  419804.0   ...     8472.0
       2016.0  3256073.0  7.232450e+05  165861.0  408858.0   ...     8472.0
       2017.0  1302428.0  7.137611e+09  165861.0  444897.0   ...    87608.0

企业编号              3992     3993    3994     3995     3996    3997     3998  \
       年报年份
认缴出资信息 2013.0  44490.0  24011.0  4517.0  12999.0  24439.0  5100.0  16000.0
       2014.0  44490.0  24011.0  4500.0  19499.0  25160.0     6.0  16000.0
       2015.0  45317.0  33616.0  4500.0  23398.0  64509.0     6.0  24491.0
       2016.0  43727.0  47568.0  4500.0  58498.0  72009.0     NaN  29209.0
       2017.0  45250.0  47780.0  4500.0  58498.0  12897.0     NaN  29209.0

企业编号              3999    4000
       年报年份
认缴出资信息 2013.0   5585.0  3000.0
       2014.0   1999.0  3000.0
       2015.0  26901.0  3000.0
       2016.0      0.0  3000.0
       2017.0  48420.0  3000.0

[5 rows x 2953 columns]