In [9]:
from IPython.display import display
import pandas as pd
import csv
import random
import re
# import pyperclip
import numpy as np
import seaborn as sns
import requests
import matplotlib, matplotlib.pyplot as plt
import pprint
import os
import dateutil
import datetime
data=pd.read_excel("赛题1数据材料\赛题1数据集\年报-股东（发起人）及出资信息.xlsx").drop_duplicates(keep='first'
                                                                         ).set_index(["企业编号","年报年份"])
data.columns=['股东类型', '股东所占比例', '$认缴出资信息', '实缴出资信息']

In [10]:
def get_number(cell):
    if not isinstance(cell, str):
        return cell
    _ = re.findall(r'[\d.]+',cell)
    if not _:
        return None
    return float(_[0])

In [11]:
df=data[["$认缴出资信息"]].applymap(get_number)

In [12]:
result=df.groupby(["企业编号","年报年份"]).sum().unstack().T
result

企业编号                    1001       1002      1003         1004         1005  \
        年报年份
$认缴出资信息 2013.0  3.945927e+06  115000.00  120200.0   80728.2534  220000.0000
        2014.0  3.945927e+06  115000.00  120200.0   80728.2534  220000.0000
        2015.0  3.945927e+06  115000.00  120200.0  100728.2534  241030.7062
        2016.0  5.552004e+06  115000.00  120200.0  100728.2534  241030.7062
        2017.0  2.232209e+06  206932.05  120200.0  100728.2534  482061.4124
        2018.0           NaN        NaN       NaN          NaN          NaN

企业编号                   1006          1007          1008      1009      1010  \
        年报年份
$认缴出资信息 2013.0  192695.8448  8.002591e+05  7.214130e+05  165861.0  307584.0
        2014.0  192695.8448  1.600518e+06  7.210130e+05  165861.0  307584.0
        2015.0  192695.8448  3.256074e+06  7.216363e+05  165861.0  398804.0
        2016.0  192695.8448  3.256074e+06  7.232481e+05  165861.0  387858.0
        2017.0  192695.8448  1.302430e+06  7.137611e+09  165861.0  426897.0
        2018.0          NaN           NaN           NaN       NaN       NaN

企业编号             ...        3991      3992        3993     3994     3995  \
        年报年份     ...
$认缴出资信息 2013.0   ...     5457.76  43854.84  24012.0000  4322.37  13000.0
        2014.0   ...     5457.76  43854.84  24012.0000  4200.00  19500.0
        2015.0   ...     7573.52  45318.14  33616.8000  4200.00  23400.0
        2016.0   ...     7564.72  43728.46  47568.2846  4200.00  58500.0
        2017.0   ...    87610.40  45251.74  47781.2254  4200.00  58500.0
        2018.0   ...         NaN       NaN         NaN      NaN      NaN

企业编号                  3996    3997        3998      3999    4000
        年报年份
$认缴出资信息 2013.0  24440.0000  5100.0  16000.0000   5585.00  3000.0
        2014.0  25161.1000     6.0  16000.0000   2000.00  3000.0
        2015.0  64509.7000     6.0  24493.0246  26901.00  3000.0
        2016.0  72009.8577     NaN  29212.2316      0.00  3000.0
        2017.0  12897.2400     NaN  29212.2316  48421.99  3000.0
        2018.0         NaN     NaN         NaN       NaN     NaN

[6 rows x 2953 columns]

In [13]:
result=result.reindex(columns=list(range(1001,4001)))
result.to_pickle('年报-股东（发起人）及出资信息.pickle')